### ISSUE TITLE
Join forces with Rakugo ?

### ISSUE THREAD

**Issue by Jeremi360** [nathanhoad/godot_dialogue_manager#1]
My friend and I are making then Rakugo project is a dialogue system inspired by Ren'Py,
but also Kits that bundles together other addons and ui with options/save/load for given game genre:
Visual Novel, Point & Click Adventure or JRPG.
Do you want to join our efforts ?

**Comment by nathanhoad** [comment]
It looks like Rakugo has a different use case to my dialogue manager.
