### ISSUE TITLE
"Loaded but not compiled" errors

### ISSUE THREAD

**Issue by BowsahBabeh** [nathanhoad/godot_dialogue_manager#104]
Hey, I'm still a total beginner so i don't really understand what the issue is (if it's on Godot's end or the plugin itself) just thought i'd throw that out here in case it's easily solvable. Tried to install Dialogue Manager in Godot 4, when i try to enable the plugin it gave me this message:

"Unable to load addon script from path: 'res://addons/dialogue_manager/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dialogue_manager/plugin.cfg' to prevent further errors."

Looking through the scripts (plugin.gd >import_plugin.gd>parser.gd>setting.gd) , it kept giving me "loaded but not compiled" errors, which i tracked all the way to the setting.gd

![fileaccess](https://user-images.githubusercontent.com/116997158/198865540-8f37e0d5-800d-4543-85e7-e070aaff5222.jpg)

As i said i'm but a humble noob, i have no idea how to fix this. :S

**Comment by nathanhoad** [comment]
It looks like you might have a version mismatch. What version of Godot are you using?

**Comment by BowsahBabeh** [comment]
v4.0.beta1.official [20d667284]

I downloaded Godot 4 just today from the beta site. I tried installing Dialogue Manager via the Asset Library (says version 2.3.0 there) which got me the error, so i manually downloaded it from the github & drag/dropped it into the project folder.... got me the same error message as well. Am i accidently using the version for Godot 3 or something? xD

**Comment by nathanhoad** [comment]
You'll need to get [Godot 4 beta 3](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-3).

Each beta introduces breaking changes so the latest Dialogue Manager is generally only compatible with the latest Godot 4 beta.
