### ISSUE TITLE
How do I move the dialog to the character's head?

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#107]
Like in your example
![image](https://user-images.githubusercontent.com/15027345/201525960-b4d4bdd7-ac2e-4aaf-ba98-81d7bbd6269b.png)

**Comment by nathanhoad** [comment]
I have a `Marker2D` node inside each character and convert it's world position into a local camera position (because of the "world" has big pixels but the UI doesn't) and then move the balloon to be at that point on the screen.
