### ISSUE TITLE
New Dialogue created blank(Suggestion)

### ISSUE THREAD

**Issue by Chevifier** [nathanhoad/godot_dialogue_manager#111]
Not a big deal but you could add a feature when the user creates a new dialogue the does not include the sample text.
maybe "Template with new Dialogues" check box enabled by default in the settings.

Basically disable it would then make new dialogues be created with no text at all.
Godot does something similar with creating scripts where you can set the template to empty

**Comment by Chevifier** [comment]
Added a pull request.[111](https://github.com/nathanhoad/godot_dialogue_manager/pull/112)

**Comment by nathanhoad** [comment]
Closed by #111
