### ISSUE TITLE
Dialogue appears over control node (Need help)

### ISSUE THREAD

**Issue by charlottegeo** [nathanhoad/godot_dialogue_manager#117]
I have a GUI control node in my main scene, when I make this GUI visible to pause the game, the dialogue balloon still shows up over the GUI. I want the control node to be on top of everything, how do I make it so the dialogue is under the GUI?

**Comment by nathanhoad** [comment]
The example dialogue sits on a `CanvasLayer` on layer 100. To put your UI over the top of it it needs to be on a higher layer (or a better solution is to create a custom balloon that fits with the rest of the UI controls).

**Comment by charlottegeo** [comment]
Reopening since putting the UI at a higher layer doesn't seem to work.
