### ISSUE TITLE
Quick font change

### ISSUE THREAD

**Issue by Abab-bk** [nathanhoad/godot_dialogue_manager#12]
Because this plugin does not change the font quickly by default, I had to make a copy of example balloon, which I hope will change.

**Comment by nathanhoad** [comment]
Do you mean the labels don't share a single font resource?

**Comment by Abab-bk** [comment]
> 您的意思是标签不共享单个字体资源吗？

No, I mean, if I just want to change the font, I have to duplicate the example balloon as well, which is time consuming, and I want it to change.
Also, I discovered a new bug: even when I use a Chinese font, the branch choice does not display Chinese.

**Comment by nathanhoad** [comment]
Having to duplicate the example balloon to make changes is what you should be doing anyhow. Changing anything within the `addons` directory is not recommended.

As for the branch choice issue, can you attach an example project so I can see what's happening?

**Comment by Abab-bk** [comment]
> 无论如何，必须复制示例气球进行更改是您应该做的。 改变内的任何东西 `addons`不推荐目录。
> 
> 至于分支选择问题，您能否附上一个示例项目，以便我了解发生了什么？

Of course, I'll send it to your email

**Comment by Abab-bk** [comment]
> You should be able to attach it the issue as a zip.
Sorry, but I still can't find where to operate, do you mean the markdown link?

**Comment by Abab-bk** [comment]
[example.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/8047438/example.zip)
oh , thanks
