### ISSUE TITLE
Single-letter variables not allowed

### ISSUE THREAD

**Issue by Kinsman** [nathanhoad/godot_dialogue_manager#123]
**Describe the bug**
Typing a variable that's a single letter (such as 'x') is not allowed by the parser.

**Comments**
I think it's due to this line.
	DialogueConstants.TOKEN_VARIABLE: RegEx.create_from_string("^[a-zA-Z_][a-zA-Z_0-9]+"),
If the regular expression ended in *, then a single letter variable would be allowed.
(Note it would also allow '_' as a legal variable name, which seems strange, but worked without problems in my tests.)

**Comment by Kinsman** [comment]
I noticed some similar problems in the regular expressions for `DialogueConstants.TOKEN_FUNCTION` and `DialogueConstants.TOKEN_DICTIONARY_REFERENCE`.
They don't allow for a single-letter variable to be indexed, or called as a function.

**Comment by nathanhoad** [comment]
I've updated them to allow for single characters 👍
