### ISSUE TITLE
(Re)importing *.dialogue asset freezes and crashes Godot

### ISSUE THREAD

**Issue by PrinceMerluza** [nathanhoad/godot_dialogue_manager#125]
**Describe the bug**
There are cases when you want to delete the .godot/imported and force a reimport. Or if you're cloning a fresh directory.
In this sample case, whenever the project is opened in Godot and initiates the (re)import, it freezes and crashes.
There are 2 dialogue files and 1 file imports from the other. Not sure if the dialogue import is significant.

GDM 2.8.1
Godot beta 10

Also shows this error in cli:
```
ERROR: Unable to open file: res://.godot/imported/update.svg-f1628866ed4eb2e13e3b81f75443687e.ctex.
   at: (scene/resources/texture.cpp:812)
ERROR: Failed loading resource: res://.godot/imported/update.svg-f1628866ed4eb2e13e3b81f75443687e.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Failed loading resource: res://addons/dialogue_manager/assets/update.svg. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: res://addons/dialogue_manager/components/download_update_panel.tscn:35 - Parse Error: [ext_resource] referenced non-loaded resource at: res://addons/dialogue_manager/assets/update.svg
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:178)
ERROR: Unable to open file: res://.godot/imported/icon.svg-17eb5d3e2a3cfbe59852220758c5b7bd.editor.ctex.
   at: (scene/resources/texture.cpp:812)
ERROR: Failed loading resource: res://.godot/imported/icon.svg-17eb5d3e2a3cfbe59852220758c5b7bd.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Failed loading resource: res://addons/dialogue_manager/assets/icon.svg. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Unable to open file: res://.godot/imported/icon.svg-17eb5d3e2a3cfbe59852220758c5b7bd.editor.ctex.
   at: (scene/resources/texture.cpp:812)
ERROR: Failed loading resource: res://.godot/imported/icon.svg-17eb5d3e2a3cfbe59852220758c5b7bd.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Failed loading resource: res://addons/dialogue_manager/assets/icon.svg. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Method/function failed.
   at: get_dependencies (scene/resources/resource_format_text.cpp:1693)
ERROR: Method/function failed.
   at: get_dependencies (scene/resources/resource_format_text.cpp:1693)
ERROR: Could not switch OpenGL context to other window: Error 170: The requested resource is in use.

   at: window_make_current (platform/windows/gl_manager_windows.cpp:279)
```

**To Reproduce**

Minimal project to reproduce: [gdm_bug.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/10401441/gdm_bug.zip)
Open project in Godot and it will crash.

If the 2 dialogue files are not included upon first opening in Godot it will not crash.

**Expected behavior**
Shouldn't crash

**Screenshots**
![2023-01-12 20_14_22-(_) gdm_bug - Godot Engine (Not Responding)](https://user-images.githubusercontent.com/22146579/212065096-921e0af9-38b3-4727-9a9e-08131279e28e.png)
![2023-01-12 20_14_30-(_) gdm_bug - Godot Engine (Not Responding)](https://user-images.githubusercontent.com/22146579/212065101-e77795c5-958a-4836-bc71-4b7e0fa3c5bf.png)

**Comment by nathanhoad** [comment]
I've made a few changes to the import plugins priority and order. Can you see if that makes any difference?

(I've also updated all UUIDs for beta 12 though I'm not sure if that does anything)

**Comment by PrinceMerluza** [comment]
I'm still getting the same thing with the sample project 
[gdm_bug.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/10417338/gdm_bug.zip)

Tested with Godot b12 and latest [commit](https://github.com/nathanhoad/godot_dialogue_manager/commit/088e641e19d4dc29f25ecd8411c880b1b20b083d) of the repo.

Removing dialogue files before opening it on Godot 12 and the godot project doesn't experience the freeze and crash so it's really crashing when trying to import the dialogue files.

![2023-01-14 20_51_26-(_) gdm bug - Godot Engine (Not Responding)](https://user-images.githubusercontent.com/22146579/212472545-aedc0b39-9f21-4fc4-a113-927675ff625c.png)

![2023-01-14 20_51_41-(_) gdm bug - Godot Engine (Not Responding)](https://user-images.githubusercontent.com/22146579/212472549-519f0d6c-af05-4882-a343-a678f16feaf5.png)

**Comment by PrinceMerluza** [comment]
Yep still getting the same bug with the sample project.
[gdm_bug.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/10417352/gdm_bug.zip)


Tested with Godot b12 and the latest commit.

![2023-01-14 20_59_34-(_) gdm_bug - Godot Engine (Not Responding)](https://user-images.githubusercontent.com/22146579/212472786-17388037-6a07-4046-9dac-b48b6772101f.png)

![2023-01-14 20_59_40-(_) gdm_bug - Godot Engine (Not Responding)](https://user-images.githubusercontent.com/22146579/212472783-134f896d-8716-463b-91d6-f07b8f0de944.png)

**Comment by nathanhoad** [comment]
I'm not sure if there's much more I can do at this stage. It appears to be a longstanding bug in Godot (even before version 4).

The (kind of) good news is that it does appear to actually correct itself after the initial editor crash.

I'm going to close this issue for now until something changes on Godot's end.

**Comment by nathanhoad** [comment]
[This](https://github.com/godotengine/godot/pull/70668) might be related (in Godot 4 beta 13).
