### ISSUE TITLE
Dialogue Resource not found in current scope

### ISSUE THREAD

**Issue by acegiak** [nathanhoad/godot_dialogue_manager#130]
**Describe the bug**
Loading Example Balloon with Godot Beta 13 and v 2.8.3 results in "Dialogue Resource Not Found In Current Scope" on line 12 o example_balloon.gd
![Screenshot_2023-01-19_21-10-49](https://user-images.githubusercontent.com/698430/213421802-83c9f017-a948-4095-8737-5c800c970d8f.png)

**Comment by nathanhoad** [comment]
I have 2.8.3 on beta 13 and I can't seem to replicate this. Godot might just need a restart.

**Comment by Jorgiz** [comment]
Same happenned to me. I even tried to reinstall the plugin and even test it in a new project. But does not work. I noticed that my .diolgue files from my previous projects are now gone and the plugin's tab also doesn't work.
![image](https://user-images.githubusercontent.com/109821453/213560023-c09923d1-496c-41a7-801f-945e98e7a4e3.png)

I'm using the compability renderer, godot 4 beta 13.

also, the plugin was downloaded via assetlib,

**Comment by nathanhoad** [comment]
@Jorgiz I think your issue might be unrelated - Dialogue Manager pre 2.8.3 doesn't work in beta 13. I have a pending update for the AssetLib but it takes a bit of time to get approved so it's still the broken one at the moment.

In the mean time you can get a copy from [the release page](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.8.3).

**Comment by Jorgiz** [comment]
![image](https://user-images.githubusercontent.com/109821453/213587338-3496f557-a613-4a93-ae87-1e62d33a108e.png)

**Comment by acegiak** [comment]
I managed to replicate it in a test project with nothing in it but the plugin, but splitting the content of line 2 on the DialogueResource script out like this fixed it for me?
`@icon("./assets/icon.svg")
extends Resource
class_name DialogueResource
`

**Comment by nathanhoad** [comment]
I wonder if that just forced Godot to reevaluate the known classes list for you (the class list has moved to the `.godot` folder instead of `project.godot`).

I just made two blank projects - one getting Dialogue Manager from GitHub and one getting it from the AssetLib (which is now 2.8.3). Both of them seemed to work fine.
