### ISSUE TITLE
Godot 4 Beta 15 error - Invalid type in function 'open_resource'

### ISSUE THREAD

**Issue by wp2000x** [nathanhoad/godot_dialogue_manager#132]
Describe the bug
The new version of Godot, Version 4.0 beta 15, causes a bug to appear in plugin.gd

res://addons/dialogue_manager/plugin.gd:78 - Invalid type in function 'open_resource' in base 'Control ()'. The Object-derived class of argument 1 (null instance) is not a subclass of the expected argument class.

![2023-01-25_18-45-04](https://user-images.githubusercontent.com/70962730/214641547-7dbc1375-5c25-402b-9719-1efcf78cced5.png)

**Comment by nathanhoad** [comment]
I can't seem to reproduce that error. When does it show up for you?

**Comment by Flynsarmy** [comment]
When I attempted to enable the v2.8.5 build in beta 15 I got the following
![image](https://user-images.githubusercontent.com/334808/214813621-c9019599-71e1-4e6b-b2c5-9bdc246ddc9e.png)
Opening plugin.gd results in the following
![image](https://user-images.githubusercontent.com/334808/214813912-83ffb77e-209a-4194-b5d7-02b29d98764f.png)

**Comment by wp2000x** [comment]
> I can't seem to reproduce that error. When does it show up for you?

I cant reproduce it too. But it happens, when i installed the plugin for the first time and created first dialog file.

**Comment by nathanhoad** [comment]
I just made a fresh project, installed the addon, and created/run dialogue without seeing the error.

I'll close this until it can be reproduced.

**Comment by nathanhoad** [comment]
I just managed to replicate it.
