### ISSUE TITLE
Godot 4 Beta 17 brings a type error in dialogue_line.gd

### ISSUE THREAD

**Issue by EnhancedJunk** [nathanhoad/godot_dialogue_manager#134]
**Describe the bug**
Trying to trigger dialogue causes this error to fire at line 33 of dialogue_line.gd:
`Trying to assign an array of type "Array" to a variable of type "Array[Dictionary]".`

It seems related to the many breaking changes in array type hinting. Some other variable assignments further down the script will also fire the same error, and even using workarounds seems to reveal different errors in other files.

**Affected version**

- Dialogue Manager version: v2.8.7
- Godot version: Godot 4 Beta 17

**To Reproduce**
1. Just trigger any dialogue or use the example balloon.

**Comment by nathanhoad** [comment]
This should be fixed now in [v2.8.8](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.8.8).
