### ISSUE TITLE
Mutations are still affected by Array changes in beta17

### ISSUE THREAD

**Issue by PrinceMerluza** [nathanhoad/godot_dialogue_manager#135]
**Describe the bug**
Getting a type error 
`Trying to assign an array of type "Array" to a variable of type Array[Dictionary]`
in line 289 of dialogue_manager.gd

```gdscript
# Make a change to game state or run a method
func mutate(mutation: Dictionary, extra_game_states: Array) -> void:
	var expression: Array[Dictionary] = mutation.expression
	
```

**Affected version**

Godot: 4 b17
GDM: 2.8.9

**To Reproduce**
Do a dialogue with a mutation function call

**Expected behavior**
Shouldn't happen

**Comment by nathanhoad** [comment]
I can't seem to replicate this error. Can you provide a dialogue snippet or a tiny project that demonstrates the issue?

**Comment by Christopotamus** [comment]
This was happening to me at first, but then after trying to replicate it in a new project I couldn't... and then I went back to my original project and it has stopped happening to me there.

The underlying issue may be related to this: https://github.com/godotengine/godot/issues/72620 but I dunno if this is a bug in godot or the dialogue manager. I'll continue to try to replicate it later today.

**Comment by nathanhoad** [comment]
I'll close this until it can be replicated.
