### ISSUE TITLE
Mutation "do"  can't turn off move

### ISSUE THREAD

**Issue by Strefiks** [nathanhoad/godot_dialogue_manager#136]
I can't turn off move with mutation "do" and function

Dialogue Manager: 1.18.0
Godot: 3.5.1

1.Make player and move system like I

```
export var acceleration = 1000
export var maxspeed = 300 
export var friction = 2000

var velocity = Vector2.ZERO

func _physics_process(delta):
	move(delta)

func move(delta):
	var input_vector = Vector2.ZERO
	input_vector.x = Input.get_action_strength("ui_right") - Input.get_action_strength("ui_left")
	input_vector.y = Input.get_action_strength("ui_down") - Input.get_action_strength("ui_up")
	input_vector = input_vector.normalized()
	
	if input_vector != Vector2.ZERO:
		velocity = velocity.move_toward(input_vector*maxspeed,acceleration*delta)

	else:
		velocity = velocity.move_toward(Vector2.ZERO,friction*delta)
	
	velocity = move_and_slide(velocity)
	
	rotation = get_global_mouse_position().angle_to_point(position)
```
2.Make two functions in the script:
```
func stop():
    set_physics_process(false)
    print("umbra")
```
```
func start():
    set_physics_process(true)
    print("lis")
```
3.Now made short dialogue with mutation "do" and functions, like this:
```
~ T0
do stop()
Todd
Todd: My name is Todd
- Bye
do start()
=> END
```
Now you can start dialogue and move during dialogue

I just wanted prevent movement player during dialogue but code doesn't work 
The video below showing how physics stop works with buttons and dialogue
https://user-images.githubusercontent.com/124451639/216820869-e9aec3f0-bd48-4aa7-844e-91342a1af4a1.mp4
Sorry if i did something wrong but i'm new

**Comment by nathanhoad** [comment]
Where you're calling `show_example_dialogue_balloon` you can probably pass in `self` as the third parameter to give the balloon access to the calling scene.

**Comment by Strefiks** [comment]
I tried it and now I see new problem.
![image](https://user-images.githubusercontent.com/124451639/217734050-f1b68348-5a2c-4787-97b2-7e2516fb5018.png)
I tried to do something about it but it doesn't work.

**Comment by nathanhoad** [comment]
Ah sorry, I meant '[self]' - the third argument is an array.

**Comment by Strefiks** [comment]
Everything works now.  Thank you so much for helping me. :)

**Comment by 3ter** [comment]
I just wanted to add that I had the same issue and could solve it as well with your hint.

Call to example balloon
```gd
func _on_interaction_area_interact(interacting: Node) -> void:
	assert(interacting is State, "Non supported interaction of node %s" % interacting.name)

	DialogueManager.show_example_dialogue_balloon(dialogue_resource, dialogue_title, [interacting.character])
```

Example dialogue
```gd
~ this_is_a_node_title

set is_rooted = true
Nathan: [[Hi|Hello|Howdy]], this is some dialogue.
Nathan: Here are some choices.
- First one
	Nathan: You picked the first one.
- Second one
	Nathan: You picked the second one.
- Start again => this_is_a_node_title
- End the conversation => end_and_release_player
Nathan: For more information see the online documentation.
=> end_and_release_player

~ end_and_release_player

set is_rooted = false
=> END
```
