### ISSUE TITLE
(Feature Request) A "pointer" that signals that a text has finished being written out

### ISSUE THREAD

**Issue by nKatsuhira** [nathanhoad/godot_dialogue_manager#14]
I don't how I could describe it better than as it stands in the title and this image below:
![image](https://user-images.githubusercontent.com/57991867/153726557-b89a9699-2b6e-4664-a7e8-e962c75e173e.png)

Maybe making a pull request with this feature in the coming days after finding how to do pull requests and how this add-on works.

**Comment by nathanhoad** [comment]
The `DialogueLabel` emits a `finished` signal when it has finished typing. You can use that to implement a button prompt.

https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/dialogue_label.gd#L42
