### ISSUE TITLE
"Generate line IDs" shows only the ids in Test dialogue mode

### ISSUE THREAD

**Issue by wp2000x** [nathanhoad/godot_dialogue_manager#140]
**Describe the bug**
The line IDs affect the displayed text. This was not the case in older versions. Removing the IDs allows the text to be shown again.

**Affected version**

- Dialogue Manager version: v2.8.12
- Godot version: 4.0 RC1

**To Reproduce**

1. Create new dialog file
2. Trigger "Translations->Generate line IDs"
3. Run generated example in test mode or in own scene

**Expected behavior**
Text is not displayed, but only their ids.

**Screenshots**
![2023-02-13_13-17-10](https://user-images.githubusercontent.com/70962730/218455932-e3cce663-9aec-4ece-babf-7fb8f30d82cc.png)

Edit: Oh ok nvm, i figured out i need to add the PO by hand in "Localisation" tab. Does it make sense that this gets automatized at every export? (Or that as fallback the default one is used and not IDs?) By the way, the PO export function is throwing an error:

![2023-02-13_14-01-11](https://user-images.githubusercontent.com/70962730/218465082-ff8458d2-6ac5-4923-a425-ac2fc203a4c3.png)

**Comment by nathanhoad** [comment]
I'll look at auto-setting up the translation project settings. I'd prefer that over a fallback which would make it harder to notice lines that are missing translations amongst those that do.
