### ISSUE TITLE
Relase of version with fix for "Cannot call method 'file_exists' on a null value." when exporting a .po file?

### ISSUE THREAD

**Issue by MarcusRiemer** [nathanhoad/godot_dialogue_manager#142]
**Describe the bug**
I just found out that you already fixed the usage of the wrong object `file.file_exists(path)` to the proper `static` use of `FileAccess.file_exists` on `main`. Is there an ETA for that version landing?

**Affected version**

- Dialogue Manager version: 2.8.12
- Godot version: 4.0 RC2

**Comment by nathanhoad** [comment]
I'm working a couple of other things before I'll push out a new minor version bump.

**Comment by nathanhoad** [comment]
This is now available in [v2.9.0](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.9.0).
