### ISSUE TITLE
Godot crash at startup

### ISSUE THREAD

**Issue by sgervais333** [nathanhoad/godot_dialogue_manager#146]
**Describe the bug**
Godot just crash when I try to open the projet with the new version. If we check the error. The file translations.en.translation does not exist in the folder l10n in the new version.

**Affected version**

- Dialogue Manager version: v2.10.0
- Godot version: Godot 4 RC 4

**To Reproduce**

1. Update the addons
2. Open Godot in terminal mode (to see the error)

**Expected behavior**
Not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/6784639/221065406-65d2a8b5-bf83-4653-9c87-b68eea167db2.png)

**Comment by sgervais333** [comment]
I have now this error after some tweak:
![image](https://user-images.githubusercontent.com/6784639/221079461-4bfd5594-c23a-42a2-8fd4-dd5096ed1ff9.png)

**Comment by nathanhoad** [comment]
This is fixed in [v2.10.1](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.10.1).
