### ISSUE TITLE
Write Chinese crash

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#147]
Write Chinese crash!
godot no response!

**Comment by nathanhoad** [comment]
You'll need to provide more information. What version of Godot and Dialogue Manager? And can you provide some example text that I can copy/paste?

**Comment by wayrboy** [comment]
godot 4.0 rc4
![image](https://user-images.githubusercontent.com/15027345/221191169-98e760b5-09cc-44bf-8102-203c2ace41a2.png)


content:
~ 默认

刘小山: 你好公子,这里是 克金村,我是这里村长 刘小山
- 初入克金村 [if ! Manager.task_list.is_completed_task("初入克金村")]
	if Manager.task_list.is_satisfy_task("初入克金村")
		刘小山: 公子干的不错!
		刘小山: 公子我来想你介绍,这是我们的 拓拔寂寥
		do Manager.task_list.completed_task("初入克金村")
	elif ! Manager.task_list.is_accept_task("初入克金村")
		刘小山: 这位公子,如果你想入我们克金村,需要去外围击败10名流匪来证明你
		do Manager.task_list.add_task("初入克金村")
	else
		刘小山: 快去完成任务吧

=> END
