### ISSUE TITLE
Internationalization 

### ISSUE THREAD

**Issue by XavierH622** [nathanhoad/godot_dialogue_manager#148]
When saving a dialogue files translations to a preexisting .csv file the addon deletes the contents of the top row which defines which translations are what language
so.
```
,en,es
KEY_HELLO, hello, Hola
```
becomes
`KEY_HELLO, hello, Hola`

**Comment by felbecker** [comment]
Can't reproduce with an up to date copy of the repo.

In my case the first line was `key,de,en` so maybe putting something in the first cell makes the difference?

**Comment by nathanhoad** [comment]
The first line should have `key` as the first column.

If that doesn't work then you'll need to specify what version of Dialogue Manager and what version of Godot you're using.

**Comment by XavierH622** [comment]
putting `key` in the first row/column fixed the issue. thanks
