### ISSUE TITLE
Translate character names

### ISSUE THREAD

**Issue by felbecker** [nathanhoad/godot_dialogue_manager#149]
Currently, as far as I am aware, character names can not be translated. In some cases this might be necessary, for example with titles or nicknames.

Ideally, character IDs will be generated along with line IDs and pushed to the translation `.csv`.

**Comment by nathanhoad** [comment]
Character names aren't strictly a dialogue thing and should be handled with the game's own translations. In your custom balloon you can then use `tr()` to translate their name if needed.

**Comment by paxer** [comment]
just found the same issue, it would really improve dev/i18n experience if character names could be included to the titles as @felbecker mentioned

**Comment by nathanhoad** [comment]
I can include character names in the CSV export but they won't have generated IDs because there isn't a way to reliably map them without adding a lot of complexity.

**Comment by paxer** [comment]
ok I see, maybe improving the docs in this case regarding how to handle character names i18n will help, since there is nothing about it there yet..

**Comment by felbecker** [comment]
I will post a solution here of how a custom balloon can `tr`character names once I have time to look into it.

**Comment by paxer** [comment]
it is pretty straight forward, for me - I've just replaced

```
character_label.bbcode_text = dialogue.character
```
with 

```
character_label.bbcode_text = tr(dialogue.character)
```
in my custom balloon and created a new i18n csv file with all character names.

however, what is not straight forward - is when I read a documentation and export the csv file from the dialog manager, I kind of have an expectation that I can translate the names as well with this export, and this makes me think maybe I am missing something or how can I do it properly in the context of dialog manager CSV export. So, just adding a few explanation to the Translation documentation would be good enough to understand how to handle the i18n character names.

**Comment by paxer** [comment]
as an idea, would be nice to be able to optionally export a i18n csv file with all character names already pre-filled with the keys as names of the characters in the dialogs, and update all balloons examples by adding `tr()` for the character name label, this will make a lot easier to translate names if needed.

**Comment by nathanhoad** [comment]
I'm thinking I'll add an "export character names CSV" to the translations menu.

**Comment by nathanhoad** [comment]
This has now been added to both 1.x and 2.x
