### ISSUE TITLE
Unable to Enable Plugin

### ISSUE THREAD

**Issue by jonathan-vogt** [nathanhoad/godot_dialogue_manager#150]
**Describe the bug**
I'm unable to enable the dialogue manager plugin in the Project Settings menu of Godot. I am met with this warning: "Unable to load addon script from path: 'res://addons/godot_dialogue_manager-1.x/addons/dialogue_manager/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/godot_dialogue_manager-1.x/addons/dialogue_manager/plugin.cfg' to prevent further errors."

**Affected version**

- Dialogue Manager version: 1.18.0 (this bug has been observed with 1.17.1 as well)
- Godot version: v3.4.4.stable.official Mac OSX

**To Reproduce**
Unzip contents of dialogue manager plugin, move unzipped folder into my project's "addons" folder, and attempt to enable in project settings menu.

**Expected behavior**
The plugin out to be enabled.

**Screenshots**
If applicable, add screenshots to help explain your problem. Try to include as much detail as possible.

**Comment by nathanhoad** [comment]
There's a couple of things going on here:

1. The current stable [Godot 3 is 3.5.1](https://godotengine.org/download/macos/). Dialogue Manager doesn't support Godot 3.4.
2. The addon path should be `res://addons/dialogue_manager`, not `'res://addons/godot_dialogue_manager-1.x/addons/dialogue_manager`
