### ISSUE TITLE
example_balloon gets freed too fast, resulting in a 2+ frame blink

### ISSUE THREAD

**Issue by nKatsuhira** [nathanhoad/godot_dialogue_manager#16]
If a 'continue' input has been made, example_balloon deletes itself before the a new one gets added to the scene tree, resulting in a very noticeable and disrupting text experience. Even though the 'actioned' signal gets emitted first. 

With V-Sync ON and 60Hz monitor the 'blink' is most of the time two frames long. But can be longer depending on the machine and if its a 'menu' or not.
https://user-images.githubusercontent.com/57991867/153765869-b8408f13-f3a0-4cf6-b1f1-404ce10bc3b6.mp4

EDIT: I'm an idiot, I found out how make this work. (Made a pull request)

**Comment by nathanhoad** [comment]
This is by design to make things simple in the example balloon. If you want to remove the delay then it would be something you would implement in the balloons in your own game.
