### ISSUE TITLE
placeholder name or set name?

### ISSUE THREAD

**Issue by Lightnet** [nathanhoad/godot_dialogue_manager#160]
Is there way to place holder name instead of fixed name? One reason is npc shop same message for greeting.

Just saying that tmp name or change the npc name? One reason is have random name in place when generate npc name.

**Comment by MrKrivtsov** [comment]
Hi. Try to do this. place the name as a string in a separate singleton as a string and remove it from the dialog.

An example in singleton.
`@export var player_name = "" `

An example in the dialog.
`{{player_name}}: My name is {{player_name}}`

**Comment by nathanhoad** [comment]
Like MrKrivtsov said - you can have variable character names by wrapping a variable in `{{` and `}}` when writing their name:

```
{{character_name}}: Hello!
```
