### ISSUE TITLE
Assertion failed with GDExtension

### ISSUE THREAD

**Issue by ShomyKohai** [nathanhoad/godot_dialogue_manager#163]
**Describe the bug**
The game crashes when calling a gdextension method of a singleton that is not in the scene tree:
I made a gdextension that contains the logic to save the game. When i talk to the NPC that sould make me save the game, when `SaveManager.save()` get's called the game throws an error at [this assert statement](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/dialogue_manager.gd#L429)

**Affected version**

- Dialogue Manager version: 2.12.0
- Godot version: 4.0.1

**To Reproduce**
Have a gdextension loaded as a singleton of the engine and not added in the scene tree.
In a dialogue then call any method of the gdextension module.

**Expected behavior**
The function gets called and i can save the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/61943525/227744159-8d2af64c-88af-4c66-9ca9-776ef0c87979.png)

**Comment by nathanhoad** [comment]
Are you able to attach a tiny project that demonstrates the issue?

**Comment by ShomyKohai** [comment]
> Are you able to attach a tiny project that demonstrates the issue?

I'll try to make one

**Comment by ShomyKohai** [comment]
Here's the project. I already compiled the module for windows but I also included the source code if necessary

[Test GDEXT.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/11070399/Test.GDEXT.zip)
