### ISSUE TITLE
Various crashes causing tilemap data loss - only possibly related.

### ISSUE THREAD

**Issue by Loufe** [nathanhoad/godot_dialogue_manager#166]
**Describe the bug**
Several other people and I seem to be [experiencing a bug](https://github.com/godotengine/godot/issues/73674) causing crashes and losses of tileset data with Godot 4. Github user SGT indicates that the problem only appeared with the plugin present, though nothing concrete. Nathan, would you mind taking a look if you could spare the time? If not your plugin's fault we'd all still be very appreciative of some attention given to the issue.

**Affected version**
Latest plugin versions: 2.14.0
Latest Godot 4 versions: 4.0.0 + 4.0.1

**To Reproduce**
Screenshots, test data, and more available in linked issue on Godot Github.

**Comment by nathanhoad** [comment]
This _should_ be fixed by the workaround in [v2.14.1](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.14.1).
