### ISSUE TITLE
Allow for submodule cloning of "addons/dialogue_manager"

### ISSUE THREAD

**Issue by Selenyhr** [nathanhoad/godot_dialogue_manager#167]
**Is your feature request related to a problem? Please describe.**
When adding the plugin to a project that is managed with Git, using submodule would be awesome. It allows for including and keeping the plugin up-to-date in an easy fashion.

**Describe the solution you'd like**
Have a branch that contains only the contents of `addons/dialogue_manager` that can be cloned with `git submodule add -b <branch_name> git@github.com:nathanhoad/godot_dialogue_manager.git ./addons/dialogue_manager`.
You could also make it so that the "main" branch includes the submodule. It will increase the number of commits you will have to do when making changes however (one for the branch with the changes themselves, and another one on the main branch for it to include the new commit from the submodule).

**Describe alternatives you've considered**
I'm not sure git allows for carving out the rest of the project to just keep specific folders. Dirty hacks could be done using symbolic links, but I'm not sure it would work on every platform.

**Additional context**
[Submodule documentation](https://git-scm.com/docs/git-submodule)

**Comment by nathanhoad** [comment]
I'm not usually a fan of Git submodules. The Dialogue Manager already has an easy mechanism to keep itself up-to-date that doesn't require maintaining an additional branch:

![updates](https://user-images.githubusercontent.com/78984/230541534-222e4665-f38b-4d77-b263-5eb30208d040.png)
