### ISSUE TITLE
Does the dialog system support the ability to add a character avatar like this?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [nathanhoad/godot_dialogue_manager#171]
![Dialog  Textboxes Godot 4](https://user-images.githubusercontent.com/12076232/232261726-4f36754a-891b-4b80-9ed5-f040d007153f.png)

Does the dialog system support the ability to add a character avatar like this?

**Comment by nathanhoad** [comment]
Dialogue Manager defers to the game itself for any presentation of dialogue so it can do anything that Godot can do with UI. There's an example in the repository of using character portraits in custom balloons.
