### ISSUE TITLE
Cannot enable Addon

### ISSUE THREAD

**Issue by HammerKoopa** [nathanhoad/godot_dialogue_manager#176]
**Describe the bug**
Cannot enable the addon after installing it either manually or through the Asset Library. The output terminal shows as follows.

res://addons/dialogue_manager/dialogue_manager.gd:120 - Parse Error: Could not resolve member "parse".
  res://addons/dialogue_manager/views/main_view.gd:446 - Parse Error: Could not resolve member "parse".
  res://addons/dialogue_manager/import_plugin.gd:60 - Parse Error: "Error" was not found in the current scope.
  res://addons/dialogue_manager/import_plugin.gd:64 - Parse Error: "Error" was not found in the current scope.
  res://addons/dialogue_manager/import_plugin.gd:73 - Parse Error: "Error" was not found in the current scope.
  res://addons/dialogue_manager/import_plugin.gd:73 - Parse Error: Could not resolve member "parse".
  res://addons/dialogue_manager/plugin.gd:180 - Parse Error: Could not resolve member "compile_file".
  res://addons/dialogue_manager/test_scene.gd:16 - Parse Error: Identifier "DialogueManager" not declared in the current scope.
  res://addons/dialogue_manager/test_scene.gd:18 - Parse Error: Identifier "DialogueManager" not declared in the current scope.

**Affected version**

- Dialogue Manager version: 2.15.3
- Godot version: v4.0.rc1

**To Reproduce**
Steps to reproduce the behavior: Install Dialogue Manager through the asset library or manually.

**Expected behavior** 
Being able to install and run the addon

**Comment by nathanhoad** [comment]
You appear to be using Godot 4.0 RC1. The current version of Godot 4 is [4.0.2](https://godotengine.org/download).
