### ISSUE TITLE
Using "Toggle comment" keybind

### ISSUE THREAD

**Issue by Selenyhr** [nathanhoad/godot_dialogue_manager#177]
**Describe the bug**
When using the "Script Text Editor > Toggle comment" keybind (default <kbd>Ctrl</kbd>+<kbd>K</kbd>) on the dialogue panel, the line will be replaced by the corresponding letter. Pressing <kbd>Ctrl</kbd>+<kbd>Z</kbd> to undo the change results in the line being correctly comment-toggled.

**Affected version**

- Dialogue Manager version: 2.15.5
- Godot version: 4.0.2

Running on ArchLinux 6.2.13-arch1-1 with Wayland. AZERTY french keyboard.

**To Reproduce**

1. Reset the "Script Text Editor > Toggle comment" keybind to default.
2. Make a new `.dialogue` file with any content in it.
3. Press <kbd>Ctrl</kbd>+<kbd>K</kbd> on the selected line.

The line then disappears and is replaced by a single `k`.
If undoing with <kbd>Ctrl</kbd>+<kbd>Z</kbd>, the `k` will disappear, and the comment-toggled line will properly come back. Undoing once more makes the string go back to origin.

**Expected behavior**
Selected line should be comment-toggled, without any other modification.

**Screenshots**
![image](https://user-images.githubusercontent.com/31015897/235989103-dfb8fa15-25a3-4e16-9a46-ebe008fd6086.png)

**Comment by nathanhoad** [comment]
I don't have access to a Linux install at the moment so I can't really check anything yet. It's odd that it does have the commented line in the undo history.
