### ISSUE TITLE
Dialogue manager causes errors [Cannot erase nonexistent section "params"] when exporting.

### ISSUE THREAD

**Issue by MadFlyFish** [nathanhoad/godot_dialogue_manager#185]
**Describe the bug**
When I try to export on Windows/Android/Linux, it raises errors [Cannot erase nonexistent section "params"]
Afer I disable the Dialogue manager plugin, the problem is solved.
Maybe It's related to some kind of resource importing  problem?
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36298330/08e93c8a-5ae0-4182-99aa-05df9ac8fad5)

**Affected version**

- Dialogue Manager version:  v2.15.8 for Godot 4
- Godot version: Godot 4.0.3 rc2 ,Godot 4.0.2 stable

**Comment by MadFlyFish** [comment]
Here is another error when I delete the cache file of the dialogue manager pugin and then reactiave the plugin.
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36298330/4b0d00ce-182b-48af-b825-7168064d83c4)

**Comment by nathanhoad** [comment]
The "nonexistent params" thing is an issue with Godot when import plugins contain no options. It isn't an actual error and doesn't stop anything from working. I've added a hidden option to the import plugin so once the dialogue files are re-imported that error will go away.

I can't seem to replicate the importer error that you're seeing.

**Comment by shyn01** [comment]
re-imported that error will go away,great!
