### ISSUE TITLE
Editor stops working when switching to Dialogue Balloon

### ISSUE THREAD

**Issue by KevinHougesen** [nathanhoad/godot_dialogue_manager#187]
This happens when I make a dialogue balloon. The dialogues still work, I just cannot use the editor to add new, edit, etc.

I haven't changed anything in the original scripts except adding a new function to the DialogueManager.gd script for adding the dialogue balloon to the scene. 

After my first time encountering this bug, I figured I messed something up in the code and decided to reinstall the plugin. It works till I restart/reload my project, then every feature "disappears". 

I can still create new files and open old dialogue files, but they won't show up in the editor.

<img width="897" alt="Skærmbillede 2023-05-21 kl  17 39 37" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/83435086/5931900d-7296-454d-ba27-70e77fd844b9">
<img width="891" alt="Skærmbillede 2023-05-21 kl  17 39 24" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/83435086/3c11f7ad-9cdf-495d-a743-7582298c1874">

**Comment by nathanhoad** [comment]
What version of Godot are you using?

**Comment by KevinHougesen** [comment]
Latest release

søn. 21. maj 2023 23.17 skrev Nathan Hoad ***@***.***>:

**Comment by nathanhoad** [comment]
So 4.0.3?

**Comment by KevinHougesen** [comment]
Hadn't seen that has been released.

I am currently using 4.0.2

I'll get back to you tomorrow after updating.

man. 22. maj 2023 03.08 skrev Nathan Hoad ***@***.***>:

**Comment by KevinHougesen** [comment]
I forgot to text you back.

The issue is still present after updating to 4.0.3

Den man. 22. maj 2023 kl. 03.16 skrev kevin hougesen <
***@***.***>:

**Comment by nathanhoad** [comment]
Is there an error in the Output tab?

**Comment by nathanhoad** [comment]
I'm closing this until it can be replicated or there is more information.
