### ISSUE TITLE
Error when two files try to import each other

### ISSUE THREAD

**Issue by Conrad-N** [nathanhoad/godot_dialogue_manager#189]
![Screenshot from 2023-05-24 18-30-13](https://github.com/nathanhoad/godot_dialogue_manager/assets/23300594/b5577091-f62e-4607-a765-02a3546e58db)
![Screenshot from 2023-05-24 18-32-03](https://github.com/nathanhoad/godot_dialogue_manager/assets/23300594/43bde0db-8f38-4361-91b9-d508a3dbe9c6)

When I have two Dialogue files try and import each other they give very vague errors.

Should I not be able to do this?

What is the intended way to achieve this functionality?

**Comment by CodeWithMa** [comment]
> Should I not be able to do this?

No. It's not possible.

> What is the intended way to achieve this functionality?

The question is why do you want to do this and what problem do you want to solve by doing it?
If you want to share dialogue between the two files you could create a third file for snippets that are used by both of your files.
