### ISSUE TITLE
import doesn't work for a nested file path

### ISSUE THREAD

**Issue by LIIhasz** [nathanhoad/godot_dialogue_manager#191]
**Describe the bug**
import "res://name_of_dialogue.dialogue" as snippets -- this works just fine, however
import "res://another_folder/name_of_dialogue.dialogue" as snippets -- this throws the error "There are errors in this imported file."

**Affected version**

- Dialogue Manager version: 2.15.9
- Godot version: 4.0.1

**To Reproduce**
1. create a folder inside of project, "Dialogue" for example
2. create a "snippets.dialogue" and give it a properly formatted title and body, "=> END" at the end.
3. create a new dialogue "main.dialogue" for example.
4. import snippets.dialogue into main.dialogue, and you will see that the import fails when the dialogue is not in the root of the project. See Error.
5. move snippets to project root, update import statement to remove folder name - error should go away.

**Expected behavior**
I would expect to be able to load a dialogue file from any file path inside of the godot project.

**Screenshots**
![Screen Shot 2023-05-31 at 08 49 06 AM](https://github.com/nathanhoad/godot_dialogue_manager/assets/43663654/f3d02b9d-58ac-4f80-b032-85d552f91d07)

*there are no errors in the misc.dialogue file"

**Comment by nathanhoad** [comment]
I can't seem to replicate this from the instructions. Can you try Godot 4.0.3 and see if you still have an error?

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/78984/ed4bf9b0-7baf-4064-9ffd-9a4442d829a3)

**Comment by LIIhasz** [comment]
Upgraded Godot to 4.0.3, no longer seeing the error with the given steps above. However I was still seeing the error in my project, but I went into the imported file and saved without editing anything and now its importing properly.
Not entirely sure what that problem was, hopefully this issue doesn't crop back up. I love the plugin though, great work so far!

**Comment by LIIhasz** [comment]
WAIT! I am able to recreate the import issue by adding some white space after => END
![Screen Shot 2023-06-01 at 08 14 33 AM](https://github.com/nathanhoad/godot_dialogue_manager/assets/43663654/e7d00b80-307c-498c-b50f-696b2db3c1fb)
in the above screen shot, the white space (highlighted) is present and so is the import error. If I remove it, import goes back to normal. This happens consistently no matter which => END I give whitespace to. I can also recreate this issue in an empty project. 
Follow the original bug steps to reproduce, but in the snippets file add some trailing white space after "=> END " and you should see the import error. I'm not sure why I thought this issue was related to the file path, as experimenting shows that with the white space error import will fail no matter the path.

**Comment by nathanhoad** [comment]
Turns out I wasn't stripping whitespace when comparing known jump titles.
