### ISSUE TITLE
 The node doesn't automatically end itself before another title is encountered or the end of the file.

### ISSUE THREAD

**Issue by NNBnh** [nathanhoad/godot_dialogue_manager#193]
**Describe the bug**

On the [Writing Dialogue documentation](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md) it's said:

> All dialogue exists within nodes. A node is started with a line beginning with a "~ ".
>
> ```
> ~ talk_to_nathan
> ```
>
> <b><i><ins>A node will continue until another title is encountered or the end of the file.</ins></i></b>

But it doesn't automatically end the node. If I don't end a node with `=> END`, it will just jump to the next node, or worst, Godot will panic if the next node is empty.

**Affected version**

- Dialogue Manager version: v2.15.10
- Godot version: v4.0.2

**To Reproduce**

Write `panic.dialogue` and test dialogue:

```dialogue
~ foo

Foo: test
Foo: Jump to bar

~ bar

Bar: test
Bar: Here come the panic!!!

~ empty_node

~ baz
```

**Expected behavior**
The node automatically ended itself before another title is encountered or the end of the file.

The dialogue will just close itself if it encountered an empty node.

**Screenshots**

Godot panic when dialogue encountered an empty node:

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/43980777/1e9bbf48-e1b5-4c8e-903d-ae6c69a54ce3)

```
Invalid get index 'next_id' (on base: 'Nil').
```

---

If this not a bug, could automatically end node be a feature please, thanks!

**Comment by nathanhoad** [comment]
I've updated the docs and fixed the crash when a title at the end of the file has no content.

The automatic end node was an option in earlier versions of Dialogue Manager but it was removed in favour of treating titles as markers and not as block delimiters (which was not only what more people seemed to want but also reduces the code complexity).
