### ISSUE TITLE
Add possibility to send current file name and current title/section to mutations

### ISSUE THREAD

**Issue by mgc8** [nathanhoad/godot_dialogue_manager#194]
Thank you for the awesome and well thought-out add-on, it's perfect for so many use-cases!

**Is your feature request related to a problem? Please describe.**

We can currently call mutations from the dialogue, which execute global functions in our main code, but it's not possible to send them any data about the current status of the dialogue. It would be very useful to be able to add parameters that tell these functions which part of the dialogue tree called them, such as the name of the file and the specific title/section inside.

**Describe the solution you'd like**

Ideally, this would be an option in the settings that turns on the variable passing automatically (so that existing code is not affected, but only people specifically choosing that option will get the new behaviour). Alternatively, it can be implemented through default local variables available to the dialogue calls.

Consider the following example:

```
# Filename: story.dialogue

~ start
Narrator: Welcome!

~ sceneM1_0
Narrator: Choose your destiny.
- Take lantern
	do pick_up_item("lantern")
	You took the lantern, good choice!
	=> sceneM1_1
- Take shovel
	do pick_up_item("shovel")
	You chose the shovel, eh?
	=> sceneM1_2`

~ sceneM1_1
do add_scene_items("key", "phone")

~ sceneM1_2
do start_digging()
```

- With the option variant, if turned on the functions `pick_up_item()`, `add_scene_items()` and `start_digging()` would all receive two extra parameters at the beginning, separate from any specified by the user, in the following style: `pick_up_item(dialogue_filename = "story.dialogue", current_title = "sceneM1_0", ...)`
- WIth the variable solution, they should be set behind the scenes by the DialogueManager, and the user would type in the mutation call: `do pick_up_item(dialogue_filename, current_title, "lantern")`. Of course, this would potentially be more problematic due to conflicts with those variables in global namespaces which need to be taken into account.

**Describe alternatives you've considered**

It is possible currently to hard-code these values directly in the mutation calls, doing something like `do pick_up_item("story.dialogue", "sceneM1_0", "lantern"), etc.`; but that is extremely tedious, ugly and becomes difficult to maintain for larger dialogue files the moment any change/re-ordering/re-factor is necessary.

**Additional context**

If there is an existing method for passing dynamic information from the dialogue to the mutations, I'd be interested to find out.

**Comment by nathanhoad** [comment]
The Dialogue Manager runtime is stateless so there isn't really a concept of "current title". I've been thinking about adding another signal for when a title marker is encountered while stepping through dialogue which might make it easier for you to track in your balloon code.

**Comment by mgc8** [comment]
Thank you for looking into this!

Would it not be an option to add something like `game_states[DialogManager].current_title = key` to this bit of `get_line()`?

```
(...)
# See if it is a title
	if key.begins_with("~ "):
		key = key.substr(2)
	if resource.titles.has(key):
		key = resource.titles.get(key)
(...)
```

It could then be pushed into the beginning of the `state.emit_signal(...)` lines in `mutate()`.

I realise it's a bit of work to implement, I'd be happy to work on a patch if that helps...

The signal emitted on a new title would be an useful as well, of course; it's just mean managing the state on the other side of the script then. The main issue I see with that is that it would not be possible to discern from the signal *which* dialogue emitted it in the situation of having several dialogue files running in parallel. Perhaps adding the file name in every title would be a workaround for that, but it would not be very clean/elegant.

Is the statelessness a desired quality of the dialogue manager, to keep things simple? I could see ways to make the mutations more useful if they do keep some form of state.

**Comment by nathanhoad** [comment]
The stateless nature of the dialogue manager is a fundamental design decision.

I feel like relying on knowing which resource called a mutation is introducing a coupling that is going to present architectural problems down the line anyhow.

**Comment by mgc8** [comment]
Thank you for the clarification, makes sense in that case. I just noticed that you added the signal in the latest 2.16.0 release, much appreciated!
