### ISSUE TITLE
[C#] GetNextDialogueLine should return a DialogueLine object instead of a RefCounted

### ISSUE THREAD

**Issue by GovermanGambo** [nathanhoad/godot_dialogue_manager#195]
**Is your feature request related to a problem? Please describe.**
I mainly use C# in my game, and I'm creating a custom dialogue UI manager that interacts with the rest of the game's systems. GetNextDialogueLine only returns a RefCounted object, which I'm unsure how to use.

**Describe the solution you'd like**
The GetNextDialogueLine should return a DialogueLine object, like it does in GDscript.

**Describe alternatives you've considered**
I've tried manually creating a dialogue line object and casting the RefCounted object to it, but I'm not sure on the proper signature of the class.

**Additional context**
None.

**Comment by GovermanGambo** [comment]
I just now realized I could create my own wrapper for the object :) But it would still be nice if the built-in C# wrapper returned the related typed objects.

**Comment by nathanhoad** [comment]
The C# version should now return a `DialogueLine` object 👍  (Note: It's technically a totally different kind of object to the GDScript one but for most uses Godot shouldn't be too bothered by it)
