### ISSUE TITLE
Improve conditional handling when user accidentally uses `else if` instead of `elif`

### ISSUE THREAD

**Issue by emulrooney** [nathanhoad/godot_dialogue_manager#197]
**Is your feature request related to a problem? Please describe.**
I forgot that conditionals should be written using `elif` rather than `else if`. This behaves weirdly: it'll basically always run the first `else if`, I'm assuming because the interpretter reads `else` and just executes everything that should be in that block. This happens even if the condition in the `else if` is false.

It's not a major issue, but it's potentially confusing and causes friction when trying to debug conditionals that otherwise look right.

**Describe the solution you'd like**
Error in the dialogue editor if the line containing `else` keyword contains any other content.

**Describe alternatives you've considered**
Having `else if` as a valid alternative to `elif` might be more natural for users who write in C#.

**Additional context**
Running:
* Godot 3.5.2 
* Dialogue Manager v1.19.0

This happened with dialogue samples using raw values as well as those brought in from methods on an autoload:
```gdscript
~ choice
# Assumption is that we would see Result C, but instead I see Result B.
if (3 == 1)
	Result A.
else if (5 == 1)
	Result B.
else if (1 == 1)
	Result C.

~ choice_using_script
# This is the custom method I wrote on my autoload, which returned 1: again, expecting C but getting B.
if (GetFlagValue("my_flag") == 3)
	Result A.
else if (GetFlagValue("my_flag") == 5)
	Result B.
else if (GetFlagValue("my_flag") == 1)
	Result C.
```

**Comment by nathanhoad** [comment]
This is now available in [v1.19.1 for Godot 3](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v1.19.1).
