### ISSUE TITLE
Random crash when beginning dialogue

### ISSUE THREAD

**Issue by SpaceAttorney** [nathanhoad/godot_dialogue_manager#199]
**Describe the bug**
Occasionally, the project will crash when I begin a dialogue sequence. When the crash occurs, it is always after the first character is typed out.
Nothing is printed to the IDE's output when the crash occurs. Sometimes (but not every time) the following will be printed to the console twice on crash:
```
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
at: get_instance (./core/object/object.h:972)
```
I am _decently_ sure the crash occurs somewhere in `DialogueLabel._process()` or `DialogueLabel.type_next()`, but I can't pinpoint it exactly since the problem stops occurring if I add breakpoints or diagnostic print statements to these functions.

**Affected version**

- Dialogue Manager version: 2.16.0
- Godot version: 4.0.3.stable
I've been grappling with this across multiple versions of both, however.

I know this is a longshot since it looks like more of a Godot thing, but it only occurs during dialogue so I was hoping you might have some insight.

**Comment by nathanhoad** [comment]
I can't replicate this and without more information it's going to be hard to work out what's up. I'll close it for now but feel free to open again if you can find a way to reliably replicate.
