### ISSUE TITLE
Change the syntax for `goto`?

### ISSUE THREAD

**Issue by Sslaxx** [nathanhoad/godot_dialogue_manager#2]
Currently, `goto` syntax is `goto # Some title`. This makes it look like a comment, considering that Godot uses `#` to designate them.

Maybe eliminate the symbol altogether?

**Comment by nathanhoad** [comment]
That's a good point. I'll remove the `#` from the `goto` statements once I finish up another new feature I've been working on.

Speaking of titles, though, I'm also thinking of changing titles to be underscore separated (eg. `# some_title`) in preparation for Godot 4 which now lets me have control-click for titles to jump to them in the editor.
