### ISSUE TITLE
Missing required editor-specific import metadata for a texture; please, reimport.

### ISSUE THREAD

**Issue by stesproject** [nathanhoad/godot_dialogue_manager#200]
I just updated my project that uses Dialogue Manager from Godot 4.0 to version 4.1 and I keep seeing this error in the console.
Everything just works fine like before, but this error is spamming in the console.
I tried to re-download the plugin, but it does not fix the error.
I found out the problem was the Dialogue Manager plugin because I deleted all the assets from my project and re-downloaded them one by one (I just had two plugins by the way) until I saw the error in the console again.

- Dialogue Manager version: 2.16.0
- Godot version: 4.1.stable

1. Install Dialogue Manager in a Godot 4.0 project
2. Upgrade the project from Godot 4.0 to 4.1
3. Check the console

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/32966173/7738d506-1ea0-4962-add5-4954057391e6)

**Comment by TheWalruzz** [comment]
This is not a GDM-specific issue, you have to re-import all textures in your project (including GDM). The quickest way to do so is to close the editor, delete .godot/imported directory and open the editor with your project again.
