### ISSUE TITLE
Can't access Array members (or Dictionary members w/ integer keys) in dialog

### ISSUE THREAD

**Issue by ascripter** [nathanhoad/godot_dialogue_manager#201]
**Describe the bug**
I have an Array as property of a global Singleton. When I try to access it via indexing, i.e. `do debug(my_global.my_array[0])` from the dialog script, I get instead `my_global` returned.

I've also tried `do debug(my_global.my_array.0)` which returns `my_array`, but not element `0` of it.

Same goes for a Dictionary with integer keys *and* with numbers in String-format like `"0"`.

**Affected version**
- Dialogue Manager version: 2.16.0
- Godot version: 4.1 RC1

**To Reproduce**
1. Create Singleton in project's Autoload named `my_global` containing:
```
extends Node
var my_array := [4,5,6]
var my_dict := {0: 4, 1: 5, 2: 6}
var my_dict_str := {"0": 4, "a": 5}
```
2. Create a dialog with the aboves debug lines and check the output when hitting "Test dialogue" from the Dialogue editor
```
~start
do debug(my_global.my_array[0])
do debug(my_global.my_array.0)
do debug(my_global.my_dict[0])
do debug(my_global.my_dict.0)
do debug(my_global.my_dict_str["0"])
do debug(my_global.my_dict_str.0)
do debug(my_global.my_dict_str["a"])
do debug(my_global.my_dict_str.a)  # <-- this is the only one that works as expected
```

**Expected behavior**
Should output `4` ( or maybe `Debug: [4]`)

**Comment by nathanhoad** [comment]
I've fixed that up 👍  Previously, using `some_array.0` wasn't a supported way to reference array values but I've added it as part of the fix anyway.

**Comment by DenkevichOleg** [comment]
Still actual for Color type. Try:

` do debag(some_color.r)`

Got error: `Invalid call. Nonexistent function 'get' in base 'Color'.`

Can it be safely fixed by use `caller["value"] = caller.value[property]` for all types, not only for array?
