### ISSUE TITLE
Variables from translated files are taken as part of text instead of variables.

### ISSUE THREAD

**Issue by woyosensei** [nathanhoad/godot_dialogue_manager#202]
**Describe the bug**
I'm using translated files from .csv format as different language versions in my game. Everything works great except included variables in translated files. If I have a line as [[KEY_finishConversation_01]]:
`So be it, {{globalPlayer.rank}} {{globalPlayer.playerName}}. I have a mission for you.`
the output is exactly as the in the line above, no variables are used. Of course, when I use normal text and include variables in it then output is as it should, when variable names are replaced by their values.

**Affected version**

- Dialogue Manager version: 2.16.1
- Godot version: 4.1.stable

**To Reproduce**
1. Create .csv file in Excel or Google Sheets as its used for translation and include any singleton in it then use that key in the dialog.

**Expected behavior**
Variables included in translated lines [[KEY_TO_TRANSLATION_FILE]] should be read in the same way as any other line of text with variables.

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/10698370/5679db3e-404e-4b83-9797-a6c314395a7e)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/10698370/0f6f8b25-1722-42d6-b28f-350767c1e371)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/10698370/96b90def-0bee-44c2-bee7-f1c57ea7b3b7)

I hope it's not a bug and I'm doing something wrong and stupid, but if it is a bug I will be extremely grateful for fixing it.
Best Regards
WoYo-Sensei

**Comment by nathanhoad** [comment]
How are you parsing the translations? The syntax in your example isn't part of Dialogue Manager (which uses Godot's built-in translation handling [via line IDs](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Translations.md#exporting-lines-as-csv)).

**Comment by woyosensei** [comment]
I'm using standard `set_locale(lang)` for setting the language I want. TBH I don't remember the reason behind double brackets [[KEY]], I remember that I've tried few solutions to make it work with my game, but this solution works and it's faster for typing than [ID:KEY]. And for the issue above both give the same result, which you can see on the screenshots. For starting the dialog I'm using one balloon.tscn which can be created from `Project -> Tools` menu. I'm trying to keep everything as close as possible to your examples/tutorials (for now, untill I figure it out how to adjust it to my needs later on) and the only problem is with translations which include variables in them. Any other translation key (without variables {{var}} ) is translated as it should and works perfectly. And as I've mentioned before, If I use variables in the editor itself it works as it should and that's fine. In the screenshots under my first post you can see how I keep translation lines in the Google Sheet .csv file, how I have it implemented in-game and how the result looks like.
Best Regards

**Comment by nathanhoad** [comment]
Parsing your own translations manually like that will mean you'll also have to manually [run `get_resolved_text`](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/dialogue_manager.gd#L134) in order to get the variables replaced. That method takes a string (the line's `text` or `character`) and then an array of replacements (the line's `text_replacements` or `character_replacements`) and then an optional argument for any extra game states.

**Comment by woyosensei** [comment]
Thank you for the solution. However I have a problem with implementing it. If I have a code:
`var res = load("res://data/dialogs/characters/admStamford.dialogue")
var balloon = load("res://data/dialogs/balloon.tscn").instantiate()
add_child(balloon)
balloon.start(res, "beginning")
`
where that function `get_resolved_text` should go? I've tried
`DialogueManager.get_resolved_text("npcStamfordWelcomeAboard_00", ["{{rank}}"], [globalPlayer.rank])`
just under `start(res, "beginning")` but I get an error saying:
_"Invalid get index 'expression' (on base: 'String')."_
