### ISSUE TITLE
[C#] DialogueManager singleton is sometimes not available

### ISSUE THREAD

**Issue by wp2000x** [nathanhoad/godot_dialogue_manager#210]
**Describe the bug**
The C# DialogueManager singleton is sometimes not available, when i try to connect the signals in my code. Probably because the .NET runtime runs ahead of the GDScript plugin?
When the project is started, it fails it about ~1 out of 50 cases.

**Affected version**

- Dialogue Manager version: 2.16.2
- Godot version: 4.1.1

**To Reproduce**
- Change scene (example. menu scene to main scene via "SceneTree.ChangeSceneToFile()")
- Try to get the DialogueManager singleton via "Engine.GetSingleton()" in C# code.

**Expected behavior**
GetSingleton will return null.

**Screenshots**
When it fails:
![2023-07-25_17-13-51](https://github.com/nathanhoad/godot_dialogue_manager/assets/70962730/38e930d4-b848-4de7-a675-62d11157cc86)

When it works:
![2023-07-25_17-12-33](https://github.com/nathanhoad/godot_dialogue_manager/assets/70962730/fc5d4fe8-c7ab-4f66-973d-27142e199932)

**Comment by nathanhoad** [comment]
I've moved where the singleton gets registered to hopefully make it available earlier.

**Comment by wp2000x** [comment]
@nathanhoad I tried the newest version with the hotfix, but the problem is still there. I also tried to get the singleton with an loop (when it returned null) until it gets one from Godot but... it never gets one?
![2023-07-28_13-55-02](https://github.com/nathanhoad/godot_dialogue_manager/assets/70962730/24c50266-f6d6-407a-912e-cc21c5f4cbc1)

**Comment by nathanhoad** [comment]
Is there a reason you're connecting signals in the constructor anyhow? Normally I'd expect to see them connected in the `_Ready` function.

**Comment by wp2000x** [comment]
No not really, i just started to write code in the constructor initially and left it there. Good idea!
Tested it multiple times and seems to fix it.

**Comment by nathanhoad** [comment]
I've added a `GetSingleton()` method that might help in this scenario. It works [like this](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/examples/test_scenes/TestScene.cs#L21) (it has to be `await`ed because it tries to wait until the singleton is available).
