### ISSUE TITLE
Adding audio track id that is not related to i18n id

### ISSUE THREAD

**Issue by Gueckmooh** [nathanhoad/godot_dialogue_manager#213]
I'm working on a game project that has pre recorded sounds for dialogues. There is less audio tracks than dialogue lines and they can be used for several dialogue lines, and some dialogue lines will not have associated sound. Using the i18n id [ID:something] does not fit well for this purpose.

I would like to have a separate kind of id such as [AUDIO:somekey] to cover this issue.

I've done this change on my side, but I don't know if it is a good idea. If you find this idea acceptable I can create the pull request.

**Comment by nathanhoad** [comment]
That's a bit too use case specific to include in the stock Dialogue Manager I think. The situation you've described sounds like it would still work with line IDs if they were mapped in a dictionary to the appropriate sound file (if there was one). That way you don't need one for all lines and some files can be for multiple lines.
