### ISSUE TITLE
Make it possible for mutations to be run at the end of a title, after all the text

### ISSUE THREAD

**Issue by gatomesa** [nathanhoad/godot_dialogue_manager#216]
**Is your feature request related to a problem? Please describe.**
In my project, I want to use mutations to call some functions when a dialogue ends. However, any mutations written after the last line of text in a title seem to be ignored.

**Describe the solution you'd like**
It would be useful if Dialogue Manager ran mutations at the end of a title, even if there are no lines after.

**Describe alternatives you've considered**
I implemented a hack in which I define a certain placeholder text ("///placeholder///"), and put all the mutations I want to run at the end of a title before that placeholder text. In my dialogue system, I check for this placeholder text and don't show it on screen, knowing that it's only there so that I can run mutations.

**Additional context**

**Comment by nathanhoad** [comment]
What version of Dialogue Manager and what version of Godot are you using? It's already possible to run mutations at the end of dialogue in the latest version.

**Comment by gatomesa** [comment]
I'm using Godot 4.1.1 and Dialogue Manager 2.17.0.

**Comment by nathanhoad** [comment]
That project doesn't actually run through the dialogue so I've modified the `_ready()` so that it does. When I do that it does run that final mutation:

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/78984/6b8cdca4-c717-4936-8f1b-73ea25abe1b4)

**Comment by gatomesa** [comment]
Hmm, strange. I'm pretty sure that that project does run through the dialogue, since if you insert a mutation _before_ the text, it is indeed run.
<img width="603" alt="Screenshot 2023-08-04 at 18 54 01" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/119363621/3a566d36-6b25-4664-bf46-6effdf3582f8">

But I think that the problem is only when you call `get_next_dialogue_line()` from a resource. In my project, I don't use the DialogueManager singleton. All calls to dialogue manager are made through resources, like in the MRP. From your comment, it does seem like the call through the singleton works as expected.

**Comment by nathanhoad** [comment]
Requesting dialogue from a resource does run through the DialogueManager the same way calling it directly does.

I think you might be misunderstanding how to use dialogue. Calling `get_next_dialogue_line()` will run through lines until it finds a printable line so any mutations before that line will be run. Once it finds one it will return it so that you can display it. It is then up to your balloon to request the next line, given the `next_id` from the last one. From there it will run any further mutations until it finds another printable line or the end.

**Comment by gatomesa** [comment]
...yes, it seems it was a misunderstanding on my part. Thanks for your help!
