### ISSUE TITLE
Float precision?

### ISSUE THREAD

**Issue by K-l6408** [nathanhoad/godot_dialogue_manager#219]
In a project of mine, at various points I'd need to display a float value, but ðe current implementation uses too many digits.
I'd like a way to specify ðe precision of float values.
(Maybe wið a notation similar to "`{{float_value}.2}`"?)

**Comment by nathanhoad** [comment]
Godot already has [a mechanism for doing something like that](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html) that you can use in Dialogue Manager expressions: `{{"%10.2f" % float_value}}`

**Comment by K-l6408** [comment]
Oh, i didn't know ðat. Þanks!
