### ISSUE TITLE
Expected identifier after "." for attribute access.

### ISSUE THREAD

**Issue by Weesoid** [nathanhoad/godot_dialogue_manager#229]
Upon launching my game, the following parser error outputs: 

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/133038580/fccf0c68-7fc3-49d8-9143-08d8195f172a)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/133038580/282d120a-89f5-4820-bd5a-c599b5fb32d1)

**Comment by nathanhoad** [comment]
What version of Godot and what version of Dialogue Manager are you using?

**Comment by Weesoid** [comment]
> 

v2.19.0 for Godot 4, sorry for the late reply

**Comment by githesp** [comment]
I have the same error, using Dialogue Manager v2.18.0 and Godot v.4.0-stable-official

**Comment by nathanhoad** [comment]
If you upgrade to the latest stable version of Godot (version 4.1) do you still have that error?

**Comment by sleepyhead-km** [comment]
For me the update to Godot v4.1.1 (was running 4.0.3 before) solved the issue with Dialogue Mangager v2.18.0 and it still works with v.2.19.0

**Comment by nathanhoad** [comment]
I'm closing this as it look likes the issue was due to running an older version of Godot.
