### ISSUE TITLE
Vertical scrolling with touch pad in dialogue editor is jittery (may be related to Godot's text editor, may be Mac specific)

### ISSUE THREAD

**Issue by Morpheu5** [nathanhoad/godot_dialogue_manager#232]
**Describe the bug**
When scrolling vertically in the dialogue editor with a touch pad, the editor doesn't scroll unless a certain scrolling speed is used. When the scrolling gesture is stopped, the editor stop scrolling abruptly as opposed to slowly coming to a halt. This makes navigating dialogue files a bit hard. Horizontal scrolling works just fine.

**Affected version**

- Dialogue Manager version: 2.19.0
- Godot version: 4.1.1 (stable, official)

**To Reproduce**
Steps to reproduce the behavior: as described above.

**Expected behavior**
As described above. This was happening in Godot's code editor too but seems to have been resolved since. There's an editor option (Text Editor > Behavior > Smooth Scrolling) that fixes the issue when turned on. There has been some discussion on Godot's repo regarding smooth scrolling, I can't point to a single issue as the discussion has been quite sparse, but turning that option on seems to do wonders.

**Comment by nathanhoad** [comment]
I've added some code to grab the main code editor smooth scrolling setting and apply it to the dialogue editor. I hope that helps 👍

**Comment by Morpheu5** [comment]
Just pasted that line in to test it out and it's smooth (…) sailings :) Thanks!
