### ISSUE TITLE
Selection Titles for multiple dialogues

### ISSUE THREAD

**Issue by feendrache** [nathanhoad/godot_dialogue_manager#236]
**Is your feature request related to a problem? Please describe.**
in my game it is possible that the npc has more than one dialogue stored. 
In this case i want to create a selection dialogue in code. 
I need a selection option that may not be the first conversation line or the title

**Describe the solution you'd like**
I would love to be able to add a selection title. With this i could create a selection dialogue to show if more than one dialogues are possible

**Describe alternatives you've considered**
i'm trying to use a non-titled first line but it's not really satisfiying

**Additional context**

**Comment by nathanhoad** [comment]
I'm not really sure what you're asking for.

**Comment by feendrache** [comment]
hmm... how to explain:
i have multiple dialogue files for my npc. These can be triggered by quests or storylines.
These assigned dialogues are stored by the npc in a dialogue array.
When the player speaks the npc that has more than one dialogue assigned, i want to create a selector dialogue that shows the dialogue options.

Example first dialgoue:
~ General_Dialogue
Emma: Hello, nice to meet you, what so you want to talk about?
.
.


Second dialogue:
~ Storyline_dialogue
Emma: There was a time when... 
.
.

so when i use the first conversation line or the title of the dialogue the selection dialogue would look weird.
Maybe having a selector-title line after of in front of the title would be awesome

Like: 
~ General_Dialogue
$ Talk about daily business
Emma: Hello....

~ Storyline_dialogue
$ Talk about the storyline
Emma: There was...

**Comment by nathanhoad** [comment]
I still might not be understanding this correctly but this can probably something solved by state variables (and each NPC only really needs one dialogue file)?

```
~ start

if SomeGameState.is_player_on_some_quest:
  Emma: Hello! I hear you're doing the Something quest.
else:
  Emma: Here is something about the story in general.

=> END
```

**Comment by feendrache** [comment]
Can i load complete dialogue files with this dynamically?

**Comment by feendrache** [comment]
If there are more than one dialogue i want to have a dialogue like this:
(preload all possible dialogues into the dialogue)
and then display:
Emma: what do you want to talk about?
- Storyline => jump to storyline dialogue
- GeneralStuff => jump to general dialogue

**Comment by nathanhoad** [comment]
You can have as many "titles" in a dialogue file as you need:

```
~ start

Emma: What do you want to talk about?
- Storyline => storyline
- General stuff => general

=> END


~ storyline

Emma: This is some storyline dialogue.

=> END


~ general

Emma: This is some general stuff.

=> END
```

**Comment by feendrache** [comment]
oh i found a way right this moment:
~ selector
Talk about some stuff
~ dialogue

Speak about...
Emma: Hello, this is just for testing the second dialogue

=> END

i can use the text in the ~selector for the selector dialogue and the ~dialogue for the actual dialogue

**Comment by feendrache** [comment]
Ok, so for anyone who wants to do this... this is my way now:
1. dialogue 1:
`~ selector

Start the Storyline

=> END

~ dialogue

Emma: Greetings!
Emma: Do you want to talk about the storyline?
- Yes [if !PlayerStats.quests.has_finished_quest(1)]
	do PlayerStats.quests.new_quest(1,1)
	do PlayerStats.storylines.start_storyline(1)
	Emma: Here we go, have fun
- Finish Quest [if PlayerStats.quests.has_finished_quest(1)]
	do PlayerStats.complete_quest(1)
	do PlayerStats.storylines.complete_current_step(1)
- No
	Emma: Ok, come back later.

=> END`

2. dialogue 2:
`~ selector

Talk about some stuff

=> END

~ dialogue

Emma: Hello, this is just for testing the second dialogue

=> END` 

and then i have a function that gets an array of dialogue-file-names
`func create_selector_dialogue(dialogues) -> DialogueResource:
	var import = ""
	var import_counter = 0
	var selector = "~ dialogue_selector"
	selector += "\n\n"
	selector += npc_stats.name+": What do you want to talk about?"
	selector += "\n"
	for d in dialogues:
		import += 'import "res://DataStorage/Dialogues/'+d+'.dialogue" as import_'+str(import_counter)+"\n"
		var d_load = load("res://DataStorage/Dialogues/"+d+".dialogue")
		var title_line = d_load.get_next_dialogue_line("selector")
		selector += "- "+title_line.text+" => import_"+str(import_counter)+"/dialogue"
		selector += "\n"
		import_counter += 1
	selector += "\n\n"
	selector += "=> END"
	selector = import + "\n" + selector
	var select_dialogue = DialogueManager.create_resource_from_text(selector)
	return select_dialogue`

**Comment by feendrache** [comment]
Thanks for your help, so this functionality is not needed
