### ISSUE TITLE
Unable to create dialogue through code

### ISSUE THREAD

**Issue by feendrache** [nathanhoad/godot_dialogue_manager#237]
**Describe the bug**
I followed the description in the docs on how to create a dialogue with code

**Affected version**

- Dialogue Manager version: current
- Godot version: 4.1.1

**To Reproduce**
1.
create the string:
var selector = "~ dialogue_selector"
selector += "\n\n"
selector += npc_stats.name+": What do you want to talk about?"
selector += "\n"
selector += npc_stats.name+": Blablabla"
selector += "\n\n"
selector += "=> END"

var select_dialogue = DialogueManager.create_resource_from_text(selector)

i'm using the example bubble code and start the dialogue given above

balloon.start(resource, "0", [])
but it runs into an error in dialogue_manager.gd line 280
var data: Dictionary = resource.lines.get(key)
Trying to assign value of type 'Nil' to a variable of type 'Dictionary'.

**Comment by nathanhoad** [comment]
I think the problem you're running into is that "0" doesn't exist in that resource. You should be starting from "dialogue_selector":

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/78984/95c745ff-918c-4d48-88ba-fb0f5ed947fc)

Also, you don't need to dynamically create dialogue resources to have custom character names. You can use `{{GameState.some_character_name}}: This is the dialogue.` (where `GameState` is an example autoload in your game that stores state and `some_character_name` is an example property that stores that name).
