### ISSUE TITLE
Dialogue Manager can't find gd script?

### ISSUE THREAD

**Issue by audreyleighleigh** [nathanhoad/godot_dialogue_manager#257]
**Describe the bug**
There is a bug with referencing the dialogue manager from dialogue_resource

**Affected version**

- Dialogue Manager version: 4.21.1
- Godot version: v 4.0.2. stable

**To Reproduce**

1. List steps to see error Attempt to run a test script
2. See error, etc
3. Attempt to run a test script

**Expected behavior**
Dialogue Manager runs and plays test dialogue

Dialogue manager does not run.  Tried uninstalling and reinstalling several times and inspecting the filepaths carefully.

<img width="937" alt="Screen Shot 2023-09-08 at 1 29 05 PM" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/84555172/6e64828e-bafd-4da8-a42c-e620949f6734">

**Comment by nathanhoad** [comment]
Godot 4.1 is the latest stable release of Godot.

**Comment by audreyleighleigh** [comment]
Thanks so much! I downloaded the new version and it fixed the issue. Appreciate how fast you are with managing things.
