### ISSUE TITLE
Pixel Balloon in Examples

### ISSUE THREAD

**Issue by teamsuperpanda** [nathanhoad/godot_dialogue_manager#259]
**Is your feature request related to a problem? Please describe.**
Hi Nathan,
Was wondering if you could take the pixel balloon example from the [example_dialogue_balloons](https://github.com/nathanhoad/example_dialogue_balloons) repo for Godot 3 and bring it into this version? 
I never used Godot 3...

**Describe alternatives you've considered**
If you don't have the time the main one I'm not sure about from Godot 3 to 4 is this line here:
`export(NodePath) onready var response_template = get_node(response_template)`

Then I'll play around and create a pull request

**Comment by nathanhoad** [comment]
The pixel balloon is now just [part of the example balloon](https://github.com/nathanhoad/godot_dialogue_manager/tree/main/addons/dialogue_manager/example_balloon) (the "small example balloon"). It gets used if the [game window is less than 400px wide](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/dialogue_manager.gd#L203). The only real difference between it and the regular sized example balloon is the font and margin sizes.

That exported response template thing is no longer used. It has been replaced with a direct reference in the code to that response template (so now it does `@onready var response_template: RichTextLabel = %ResponseTemplate`).
