### ISSUE TITLE
Assertion failed ( mutations / functions) not a method on any game states

### ISSUE THREAD

**Issue by ceroblitz** [nathanhoad/godot_dialogue_manager#260]
**Describe the bug**
When using .dialogue files and mutations/functions, they don't seem to reference back to the code the function is in, following the example on your visual novel sample. 

eg.
```
~ start
do wait(0.5)
do testcommand()
do add_portrait("character", 0)
character: hello 
```

It will return back in dialog_manager.gd saying missing a method or property after the `do wait(0.5)`

**Affected version**

- Dialogue Manager version: 2.22.0
- Godot version: 4.1.1

**To Reproduce**
Specifically, I was following the tutorial on actionables and was able to get all integrated functions working, but when I modified the balloon.gd file to integrate the sound on textscroll and integrate portraits, I found out that even simple functions/mutations that only print a debug message would result in the same error. 

**Expected behavior**
I was hoping the command would run and show portraits, even the debug command would.

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/19851038/dc33ded4-677c-4a2d-a1cd-4314d8ed1e4c)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/19851038/b42d30bd-c8d9-4f0c-ae0e-f22b41d1e01d)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/19851038/1ae366c2-9023-4fae-b199-15506e1271cf)

**Comment by nathanhoad** [comment]
Inside the `start` method of your balloon are you missing a line that looks something like `temporary_game_states = extra_game_states + [self]`? It sounds like the balloon isn't being given as an extra game state.

**Comment by ceroblitz** [comment]
Looks like that was the issue! I only had 
`temporary_game_states = extra_game_states`
and changing it to
`temporary_game_states = extra_game_states + [self]`
worked!
Both the custom command and the portraits are working.
Thank you so much!
