### ISSUE TITLE
"docs" and "examples" folders are missing from the actual plugin in Godot

### ISSUE THREAD

**Issue by darth-biomech** [nathanhoad/godot_dialogue_manager#261]
Whether downloading from the Github as a zip, or from the Asset Library in Godot or on the site, the resulting plugin misses the documentation folder. 
Furthermore, I don't think I see an option to download them separately on Github either, due to them missing from the generated zip file...

**Comment by nathanhoad** [comment]
You have to clone the repository to get the examples and docs folders. They are stripped out of the release downloads automatically.
