### ISSUE TITLE
Plugin causes significant slowdown in large project

### ISSUE THREAD

**Issue by zen14774** [nathanhoad/godot_dialogue_manager#265]
**Describe the bug**
I have a project with an increasingly large number of files and saving anything (even a scene or a script) has been getting noticeably slower the more files I have.

It kept getting worse so I've looked into it and I've traced it back to this plugin. Specifically, to this line:
https://github.com/nathanhoad/godot_dialogue_manager/blob/3a4497059f1ebe3f2b0f2bb859c7590cb8e716df/addons/dialogue_manager/plugin.gd#L193

**Affected version**

- Dialogue Manager version: 2.22.0
- Godot version: 4.1.1

**To Reproduce**

1. Create a project with this plugin.
2. Add several hundreds of resources to the project folder.

**Expected behavior**
Saving should be fast, as it is without the plugin installed.

As a temporary workaround, I've put all of my dialogue files in a single folder and edited the plugin code so it only checks that folder, and that pretty much reduced the slowdown to something unnoticeable.

I suggest the plugin should either handle changes in the file system more efficiently, or at least provide some settings to specify directories to check/ignore.

**Comment by nathanhoad** [comment]
I've made a bunch of changes to how the internal dialogue cache works so if you wanted to give that a whirl its now in `main`.

**Comment by zen14774** [comment]
:+1:  It works much better now. 

Thank you
