### ISSUE TITLE
Why is that?

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#27]
![image](https://user-images.githubusercontent.com/15027345/156937141-33c5c02b-520b-420e-a6d4-32e12e32c5c9.png)

**Comment by wayrboy** [comment]
![image](https://user-images.githubusercontent.com/15027345/156937190-2f6e8975-100d-4e90-b9f5-e43691351479.png)

**Comment by wayrboy** [comment]
![image](https://user-images.githubusercontent.com/15027345/156937205-2e9e45d1-58dd-44be-9a10-bba2e426751e.png)

**Comment by nathanhoad** [comment]
I think the reported error was pointing to the wrong place. The cause appeared to be when conditional lines were looking back up the list they weren't skipping empty lines.
