### ISSUE TITLE
Save "used" responses

### ISSUE THREAD

**Issue by ismslv** [nathanhoad/godot_dialogue_manager#273]
**Is your feature request related to a problem? Please describe.**
In many games, when player uses a responce in a dialog, it is saved. So that next time player starts this dialog or this particular choice, already used response is greyed out.

**Describe the solution you'd like**
Have a consise built-in way to store responses. For example, in a .dialog file or in settings user could add an "import", that would point to an array in a Global script. Dialogue system then would save to that array: name of dialogue (optional), identifier of the response and number of times this response was chosen.

It would also lead to the possibility to implement a special condition for a response, such as `if times_selected == x`. The same could apply even for lines, but with "show" instead of "select": `if times_shown > x`

**Describe alternatives you've considered**
Of course, it can be done with a standard technique (using Global script with variables), but it is cumbersome and it is unclear what is a best way to "identify" a response.

**Comment by nathanhoad** [comment]
I've added IDs to dialogue lines and responses.

Using those IDs you can build a list of used responses in your game. Saving them automatically in the Dialogue Manager isn't something that's likely to get added because it breaks the rule of being stateless.
