### ISSUE TITLE
Can you add search function?

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#28]
Can you add search function?

**Comment by nathanhoad** [comment]
I'll probably look at adding some kind of text search on the weekend.

**Comment by nathanhoad** [comment]
I've added a basic text search. When I get a chance I'll add some text replace functionality too.

**Comment by wayrboy** [comment]
thank you

**Comment by nathanhoad** [comment]
I've added a basic replace toolbar now.
