### ISSUE TITLE
Parser Error: Could not resolve script "res://addons/dialogue_manager/dialogue_manager.gd".

### ISSUE THREAD

**Issue by AngeloGamer10** [nathanhoad/godot_dialogue_manager#283]
**Parser Error**

I encountered a parser error in Godot while trying to resolve the script located at "res://addons/dialogue_manager/dialogue_manager.gd." The specific error message I received is "Expected identifier after '.' for attribute access." This error prevents me from accessing and utilizing the mentioned script properly. Please investigate and provide guidance on resolving this issue. Thank you!

**Affected version**

- Dialogue Manager version: 2.24.2
- Godot version: v4

**Expected behavior**
A simple dialogue.

**Comment by nathanhoad** [comment]
Are you using Godot 4.1?

**Comment by nathanhoad** [comment]
Normally I'd recommend upgrading to whatever the latest stable version of Godot is but I've added a workaround for that specific error anyhow 👍
