### ISSUE TITLE
Add get_previous_dialogue_line function

### ISSUE THREAD

**Issue by renere** [nathanhoad/godot_dialogue_manager#286]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but I would like to implement being able to see previous lines of dialogue in the game I'm working on, similar to Paper Mario (N64) when pressing the Z button.

**Describe the solution you'd like**
A function similar to get_next_dialogue_line would be a great way to achieve what I set out to do.

**Describe alternatives you've considered**
Currently I am storing all previous dialogue lines in an array, and if I want to see a previous line of dialogue instead of getting the next dialogue line I get the last item in the array, and then going back further just displays dialogue lines closer to the front of the array. While this works, having a get_previous_dialogue_line function built in would be excellent.

**Additional context**
I'm not too fussed if you decide this is not necessary or makes things too complicated or anything, it would just be nice to have.

Thank you!

**Comment by ismslv** [comment]
You can have multiple previous lines.
Imagine this theoretical structure:

```
1. Question?
- Answer 1 => 1
- Answer 2 => 2
- Answer 3 => 3
2. Text
3. Text
```

If you are on the line 3, what is the previous line? It can be 2 OR 1.3. Given the stateless nature of the system, you have to store your dialog's history yourself. You don't have to store lines entirely though, just save their ID's into list.

**Comment by nathanhoad** [comment]
Thanks for the suggestion but as @ismslv said above, tracking previous lines would need to introduce state into the Dialogue Manager which isn't something I want to do. Thankfully it should be easy enough to implement in your game though 👍
