### ISSUE TITLE
Invalid get index 'id'

### ISSUE THREAD

**Issue by XuaTheGrate** [nathanhoad/godot_dialogue_manager#289]
**Describe the bug**
Error:  `Invalid get index 'id' (on base: 'Dictionary')`
`res://addons/dialogue_manager/dialogue_line.gd:59 - at function: _init`

**Affected version**

- Dialogue Manager version: v2.42.2
- Godot version: v4.1.1.stable

**To Reproduce**
Steps to reproduce the behavior: I'm not sure, it's just occurring. 
My dialogue file is simply:
```
~ ch_0_begin

Test: i'm testing

=> END
```
And code to start the dialogue is as follows:
```
var dialogue_file_name: String = "res://lang/DemoInvestigation/story/ch_0_p1.dialogue"
var dialogue_start_line: String = "ch_0_begin"

func start_dialogue():
	var resource = load(dialogue_file_name)
	DialogueManager.show_example_dialogue_balloon(resource, dialogue_start_line)
```

**Expected behavior**
For it to show the example dialogue balloon, and the text given.

**Screenshots**
![img](https://i.imgur.com/dVJZIv1.png)

**Comment by nathanhoad** [comment]
I can't seem to replicate this but, just in case, I've added a fallback for getting line IDs from the compiled data. In most cases you won't need them but if you do and they are blank then you might need to restart the editor until it works.
