### ISSUE TITLE
Responses nested inside of conditions continue outside of nesting 

### ISSUE THREAD

**Issue by ShikadiGum** [nathanhoad/godot_dialogue_manager#29]
Nesting regular dialogue lines under conditionals works as expected:
("Condition is TRUE" is the last thing you see before the conversation ends)
```
~ start
if true
	Condition is TRUE
else
 	Condition is FALSE (You shouldn't see this)
```

However, if you add a response, the `else` is also run:
("Condition is FALSE (You shouldn't see this)" is the last thing you see before the conversation ends)
```
~ start
if true
	Condition is TRUE
	- Foo
else
 	Condition is FALSE (You shouldn't see this)
```
![image](https://user-images.githubusercontent.com/99618049/156993243-cb685a37-643f-4b22-944a-489633e79f76.png)

The workaround is to simply add an `=> END` under the response:
```
~ start
if true
	Condition is TRUE
	- Foo => END
else
 	Condition is FALSE (You shouldn't see this)
```

Obviously since the workaround is so simple, this isn't a huge issue, but I figured I should document it anyway in case anyone else comes across this.

**Comment by nathanhoad** [comment]
Ah yep. I think I know what's up with that.
