### ISSUE TITLE
Inconsistent starting title when using "test dialogue" button.

### ISSUE THREAD

**Issue by Obnivelint82** [nathanhoad/godot_dialogue_manager#296]
**Describe the bug**
The dialogue starts at inconsistent titles when editing and testing using the built-in text editor and test dialogue button.

**Affected version**
- Dialogue Manager v2.25.1
- Found bug on Godot 4.1.1, Also confirmed on new clean project in Godot 4.1 stable.

**To Reproduce**

create a new dialog file, and create a few titles. This is what I used. 

~ one
one
=> END
~ two
two
=> END
~ three
three
=> END

Always test the dialogue using the "test dialogue" button. 

First time through you should get "one" of course.

Now make a change. I moved the entire "three" block to the top.
Don't save anything. (I used ctrl-S). Run again. 
I got "two"...

I just keep making small singular changes to the file and re-running it (messing with it) - adding new lines, deleting text, moving titles up and down in order etc. - and the output changes. But again, seemingly randomly. 
Saving (ctrl-s shortcut) also seems to have an effect - sometimes.

I've managed to get all 3 numbers just by messing with the text and changing order.

**Expected behavior**
Consistent behavior. 
When using the test dialogue button, it should always give the same "expected" output. Right now I'm just crossing my fingers that it starts where I expect. 

I'm not sure what the intended behaviour is when running a dialogue file this way. Does it jump to the first title? Do I tell it where to start with a jump at the very top outside of any titles - Just tested this with Nathan default, it crashed. Submitting a seperate bug report.

**Comment by nathanhoad** [comment]
It should be starting from the closest title above the current cursor.

**Comment by Obnivelint82** [comment]
Thanks for the quick reply. Totally works as expected! 
It crashes when there is nothing above the cursor though.

**Comment by Obnivelint82** [comment]
Found this in the documentation:
Your custom test scene must extend BaseDialogueTestScene which will provide you with a resource property which is the DialogueResource currently open and a title property which is the nearest title to the cursor position.

This information should probably be put under (or duplicated in?) the "Running a test scene" heading.
Also should probably read "nearest title above the cursor position."
