### ISSUE TITLE
Remove embedded and cached icon textures

### ISSUE THREAD

**Issue by jmoon1506** [nathanhoad/godot_dialogue_manager#298]
**Is your feature request related to a problem? Please describe.**
This addon's total download size via AssetLib is 6.9 MB. 6 MB is from just two scene files: [settings_view.tscn](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/views/settings_view.tscn) and [code_edit.tscn](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/components/code_edit.tscn). 

**Describe the solution you'd like**
Replace embedded textures with SVG icons. Remove unused cached image data from scene files.

**Describe alternatives you've considered**
At least consider using WebP raster icons instead of raw bitmaps.

**Additional context**
Even though it is an editor tool, keeping download size small makes it easier to use.

<img width="1487" alt="Screenshot 2023-10-01 at 10 17 43 PM" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/21185262/713f8e6f-a36b-4281-98e8-5396416589cd">

**Comment by nathanhoad** [comment]
Good catch. Those images and font resources are set at runtime so there was no need for them to be embedded in the scenes anyhow.
