### ISSUE TITLE
More advanced expressions

### ISSUE THREAD

**Issue by LoipesMas** [nathanhoad/godot_dialogue_manager#3]
I wish I could do something like
```gdscript
- Foo [if foo and (bar or baz)]
    ...
```
or
```gdscript
set foo = bar and (baz or quaz)
```
or
```gdscript
set foo = f1(bar, f2(baz))
```
Keywords (`or, and`) could be operators instead (`||, &&`), doesn't matter.
Doing 2nd or 3rd one would allow 1st one indirectly (by using a temp variable (and maybe custom functions)).

This would allow for more complex checks in responses etc.
Currently it's technically possible with custom functions and more temp variables, but it's kinda ugly and verbose.

Nice work so far, I think it has a lot of potential!

**Comment by nathanhoad** [comment]
Haha yeah this has been on my todo list. I'm almost done so it should be out soon.
