### ISSUE TITLE
Dialogue Editor is slow to type in for large projects

### ISSUE THREAD

**Issue by nstryder** [nathanhoad/godot_dialogue_manager#31]
Hello, I run a large project with thousands of files. This causes saving to be much slower than the average project. 
I was wondering if the editor auto-saves upon entering any text. If so, this might be the cause of the performance issues. The option to turn off auto-save and have a manual save button would be a simple solution I think.

I tested it again with a fresh minimal project, and the slowdown does not happen there.

Attached is a video demonstrating the slowdown. Under Godot's code editor, input is smooth, but in the Dialogue tab, it is slow to enter anything.

https://user-images.githubusercontent.com/45138063/157165190-f8868b0d-d048-45fe-8f74-4bf0372ebb79.mp4

**Comment by nathanhoad** [comment]
I've moved the code that was constantly saving the dialogue resource out into a proper `apply_changes()` method. That should make things better.
