### ISSUE TITLE
Invalid call Nonexistent function 'new'

### ISSUE THREAD

**Issue by Tab1138** [nathanhoad/godot_dialogue_manager#310]
**Describe the bug**
I am using the function call through a singleton to switch scenes different backgrounds and what not. I have everything set up correctly and it works if I push it through F12. But I get this error--> Invalid call. Nonexistent function 'new' in base 'CSharpScript'. The script it is referring to is dialogue_manager.gd line 1025 var dotnet_dialogue_manager = load("res://addons/dialogue_manager/DialogueManager.cs").new()   <----This being the nonexistent function in DialogueManager.cs

**Affected version**

- Dialogue Manager version: v2.25.4
- Godot version: 4.1.1 stable

**To Reproduce**

I have a singleton called globalDialog and in it I have a function
func home_scene():
     get_tree().change_scene_to_file("res://levels/scene/home.tscn")

and in Dialogue I have 
     do home_scene()

and it works if I hit F12 to continue all the way through the dialogue but it throws that error and I am very confused and I do not know how to code.

**Expected behavior**
     Thankyou for this plugin It has worked up till now. But I am probably just using it wrong. But I did have it working I am so confused.

**Screenshots**
If applicable, add screenshots to help explain your problem. Try to include as much detail as possible.
![Dialog](https://github.com/nathanhoad/godot_dialogue_manager/assets/47303611/8594bda9-980d-455f-9026-f2cc2ec55820)
![Error](https://github.com/nathanhoad/godot_dialogue_manager/assets/47303611/f9a7efef-238f-4bfc-89ba-169435719e21)

**Comment by nathanhoad** [comment]
It looks like you're missing the MS Build tab down the bottom. Can you run this tool command and see if that fixes it?

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/78984/5d87065a-341e-48de-9335-0184bdfe43de)

**Comment by Tab1138** [comment]
Failed to create C# project.  Is the window that pops up when I try.

**Comment by nathanhoad** [comment]
Do you get an error in the logs? And are you actually using C# in your project?

**Comment by nathanhoad** [comment]
I'm going to close this until there is more information.
