### ISSUE TITLE
Running game crashes with 'get_files_with_errors' in base 'Nil' in latest Godot beta

### ISSUE THREAD

**Issue by jaybaird** [nathanhoad/godot_dialogue_manager#320]
**Describe the bug**
`res://addons/dialogue_manager/plugin.gd:105 - Invalid call. Nonexistent function 'get_files_with_errors' in base 'Nil'.
editor/editor_node.cpp:6473 - An EditorPlugin build callback failed.`

** Affected Version **
- Dialogue Manager version: 2.25.4 
- Godot version: 4.2 beta 1

**To Reproduce**
Steps to reproduce the behavior: install DialogueManager in Godot 4.2 beta 1

1. Build and run from editor

**Comment by nathanhoad** [comment]
I can't seem to replicate this with Dialogue Manager 2.26.0 and Godot 4.2 beta 1.

**Comment by nathanhoad** [comment]
I'm going to close this for now seeing as how Godot 4.2 is still in beta and I haven't been able to replicate it.
