### ISSUE TITLE
Add exporting of character names as comment column in CSV

### ISSUE THREAD

**Issue by IntangibleMatter** [nathanhoad/godot_dialogue_manager#323]
**Is your feature request related to a problem? Please describe.**
When exporting for translation, it can be very useful for translators to know what character is saying a line. This helps them follow conversations better.

**Describe the solution you'd like**
Godot supports having ignored columns in translation CSVs by prefixing them with an underscore, like so
```csv
key,en,_character
01,Hey,John
02,Hey!,Jade
03,Woah! wild. Same sentence.,Jade
```
It would be beneficial for reading and writing CSVs for translations if the character was exported as a data column. as this would mean that people reading CSV files would have a better idea of who's saying what.
For additional ease of use, you could even add columns for what file/label a thing is said in. All of this would have no consequence on the dialogue files itself, but it would massively improve readability.

**Describe alternatives you've considered**
The only alternative is to add these manually, though you may not remember which character is saying "yeah"

**Comment by nathanhoad** [comment]
Is that documented somewhere? I started implementing this but it seems Godot treats those columns as invalid locales and generates extra translations files anyway.

**Comment by IntangibleMatter** [comment]
Okay, yeah, it generates a translation file without a locale. I think I found this on an old forum or something.

**Comment by IntangibleMatter** [comment]
Created an issue. godotengine/godot#83573

**Comment by IntangibleMatter** [comment]
This should be easily doable in Godot 4.2, as godotengine/godot#83600 was just merged, which means that columns deemed 'invalid' will be ignored, allowing columns which are intended for comments to start with an `_` or `-`, and have no file generated for that column.

**Comment by jsjtxietian** [comment]
I opened a follow up pr for this https://github.com/godotengine/godot/pull/84569, now csv column start's with `_` will not trigger warning anymore.

**Comment by IntangibleMatter** [comment]
Commenting again to check the status of this now that we're in 4.2

**Comment by jkulawik** [comment]
A simple way of bypassing this issue would be to add the character names to the translation IDs.
