### ISSUE TITLE
Provide a way to modify a line’s skip behavior

### ISSUE THREAD

**Issue by gatomesa** [nathanhoad/godot_dialogue_manager#324]
In my project, I would like to do the following: On lines which use a `[wait]` BBCode, skipping will only skip up to the `[wait]` code. In other words, all the text before the `[wait]` code will be shown; then it will wait for the specified duration; then it will resume typing normally, without skipping the part after the `[wait]` code (unless the player presses skip again, of course).

It seems to me that there is no way yet to do this manipulation of skip behavior: when the skip action is pressed, all the text is shown. I thought about how to do it through my game logic, but I didn’t find a way to get a “raw” line (the text with BBCodes) which I would need for any solution. The `text` property on `DialogueLine` returns the “clean” text.

I think a special `[skip_stop]` BBCode, or something along those lines, would be helpful for my use case and others. This code would stop the skipping of a line at a particular point. For example:
`Someone: this line will only skip up to here. [skip_stop] Then this will start typing normally, unless you want to skip it too.`
Of course, there may be a better solution.

**Comment by nathanhoad** [comment]
This feature is a little bit game-specific so if I did implement it it would probably be an option on the DialogueLabel to "skip until next wait" or something. That way you would enable it in your custom balloon.

**Comment by nathanhoad** [comment]
I was thinking about this feature a bit more and I don't think I'll include it in the base `DialogueLabel`. To have your dialogue stop on `wait`s, even when skipping you can make an extension of `DialogueLabel` and override the `skip_typing` method with something like this:

```gdscript
func skip_typing() -> void:
	_type_next(1000, 0)
```
