### ISSUE TITLE
Add extracting game state from dialogue to script.

### ISSUE THREAD

**Issue by Carpynch0** [nathanhoad/godot_dialogue_manager#326]
#### Dialogue.
![dialogue](https://github.com/nathanhoad/godot_dialogue_manager/assets/47200285/1c9153bd-a5c3-46b6-87ce-58fc404dd7db)

#### Filesystem dock.
![filesystem](https://github.com/nathanhoad/godot_dialogue_manager/assets/47200285/ec2402b0-aa63-4cb6-8ac9-c4b27b0641e7)

#### Script with game state.
![game_state](https://github.com/nathanhoad/godot_dialogue_manager/assets/47200285/89facf1c-d880-4e7a-b678-118ae724e02b)

#### Using the script.
![uso](https://github.com/nathanhoad/godot_dialogue_manager/assets/47200285/cbc7aa38-89b0-4d53-89bd-8d70b9b0e47d)

**Comment by nathanhoad** [comment]
This is a little too niche to include in the base Dialogue Manager. You could probably build something like this for your own game by iterating over the lines in a `DialogueResource` and looking at the replacements arrays for variable names.
