### ISSUE TITLE
Changing `ResponseExample` button font size does nothing

### ISSUE THREAD

**Issue by synalice** [nathanhoad/godot_dialogue_manager#328]
I want to change example dialogue balloon. I did manage to change font size for the `DialogueLabel` Node, but overriding the theme's font size for `ResponseExample` button does nothing since these buttons are created at runtime. Is writing
```gdscript
var item: Button = Button.new()
item.add_theme_font_size_override("font_size", 55)
```
in the balloon script – the best way to do this?

**Comment by nathanhoad** [comment]
I've just added [a feature for specifying a response template](https://github.com/nathanhoad/godot_dialogue_manager/pull/332) to the responses menu.
