### ISSUE TITLE
Change default text speed

### ISSUE THREAD

**Issue by joshmitcho** [nathanhoad/godot_dialogue_manager#329]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to change (speed up) the default/global text crawl speed. Setting a different value for each character would be nice, but just a changeable global default is fine. Like how the old pokemon games allowed for changing text speed in Options.

**Describe the solution you'd like**
Either a global editor setting, or a variable accessible via script, even a tag (per-character or global) I could include at the start of each file to set a default text speed.

**Describe alternatives you've considered**
Using the existing text speed tags to change text speed per-line. Not very scalable. I could write a script that intercepts the dialogue_line and modifies the speed tag on the fly, but that kind of entangles things.

**Comment by nathanhoad** [comment]
This is something you'd do in your custom balloon by changing to the "Seconds Per Step" property on the [`DialogueLabel`](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/API.md#dialoguelabel).

**Comment by joshmitcho** [comment]
Gotcha, thanks!
