### ISSUE TITLE
Play test relies on window size

### ISSUE THREAD

**Issue by timothyqiu** [nathanhoad/godot_dialogue_manager#33]
I'm making a pixel art game so the window size is relatively small (256 x 150). When running play test, the scene is too small to actually preview anything.

![ksnip_20220309-111517](https://user-images.githubusercontent.com/372476/157365904-0d4d9123-aff9-4408-9779-284470b000e0.png)

I'm not sure how this should be resolved. Maybe put the test scene in a `Viewport`?

**Comment by nathanhoad** [comment]
I've added a thing to the test scene to force a higher resolution for when you're testing via the dialogue editor.

For the actual balloon in your own game I'd suggest using a smaller font/NinePatch texture or put it under a `Viewport` like you said.
