### ISSUE TITLE
Check if dialog resource has a specific title

### ISSUE THREAD

**Issue by NickHatBoecker** [nathanhoad/godot_dialogue_manager#330]
Hi there,

my game contains of let's say 30 days. Per day every NPC should have a different dialog. If there is no specific dialog for the current day, a default dialog should be used instead.

For this I need to ask if a specific day dialog exists, if not, use default dialog.
For example like this:

```gdscript
var currentDay = 21
var resource = load("res://src/dialogs/some_dialog.dialogue")

if resource.has_dialog("npc_day%s" % currentDay):
    resource.get_next_dialogue_line("npc_day%s" % currentDay):
else:
    resource.get_next_dialogue_line("npc_default"):
```

Maybe this is already possible? I couldn't find anything in the docs.
Just using `get_next_dialogue_line` with a title that doesn't exist, ends in an exception I cannot catch.

Maybe it's as easy as this:

```gdscript
# @see https://github.com/nathanhoad/godot_dialogue_manager/pull/238/files#diff-2bee43b84f968052ea147b011a4360a7a8154d92be8f1d2daf12e22256c40ed9R254

func has_dialog(resource: DialogueResource, key: String = "") -> bool:
    return resource.lines.has(key)
```

or

```gdscript
func has_dialog(resource: DialogueResource, key: String = "") -> bool:
    for i in resource.lines:
        if resource.lines[i].type == "title" and resource.lines[i].text == key:
            return true

    return false
```

Best regards
Nick

**Comment by nathanhoad** [comment]
You can do something like `resource.titles.has("some_title")`
