### ISSUE TITLE
Parser Error: Could not find type "DialogueResource" in the current scope.

### ISSUE THREAD

**Issue by germanbv** [nathanhoad/godot_dialogue_manager#331]
**Describe the bug**
After adding this addon to my project, I have started to experience this issue when hitting the play button... the engine randomly freezes until it displays **Parser Error: Could not find type "DialogueResource" in the current scope.** on dialogue_manager.gd line 76 (get_next_dialogue_line) and the game crashes, if I restart I have a good chance of not triggering the issue.

From what I've read, this seems to be an engine-related bug that has been around since 2019 and has to do with the engine not loading singletons on Autoload, I'm not sure though, since DialogueResource is a global class rather than a singleton... maybe you know a workaround for this?... I was thinking of maybe creating a c# version that's not part of the addon folder to see if the problem persists...

For reference see: https://github.com/godotengine/godot/issues/32759

I have to add that DialogueManager is the only singleton I have on AutoLoad and it is the only addon I'm using on my project, in the other hand I also have other classes inheriting from Resource which don't have any problem.

**Affected version**

- Dialogue Manager version: 2.26.0
- Godot version: 4.1 Mono

**To Reproduce**
Add the addon and execute your game... The problem triggers randomly but it used to be more frequent after modifying a script file. Keep in mind that I'm using the Mono version and I'm working with C#. I haven't tested this on a normal version.

**Comment by nathanhoad** [comment]
Whenever I've run into missing classes I usually delete the `.godot` folder and let Godot rebuild all of the caches.

**Comment by germanbv** [comment]
thanks I'll try that I report back if the problem persists

**Comment by germanbv** [comment]
deleting the .godot folder didn't solve the issue, this seems to trigger after modifying C# scripts

**Comment by nathanhoad** [comment]
I've just merged in some improvements to the C# stuff including [this line](https://github.com/nathanhoad/godot_dialogue_manager/pull/338/files#diff-2bee43b84f968052ea147b011a4360a7a8154d92be8f1d2daf12e22256c40ed9R23) that might help with the error that you're seeing. I do think it's an engine bug but hopefully this is a workaround for now.

**Comment by germanbv** [comment]
thank you! I'll try that out... and yes, the problem is an engine-related bug... I kept investigating and it might be the same issue explained in: https://github.com/godotengine/godot/issues/75388
