### ISSUE TITLE
Access translation_key of Dialogue Line

### ISSUE THREAD

**Issue by mzoeller** [nathanhoad/godot_dialogue_manager#34]
Hi, I'm extending the example balloon to play a line of voice when a line is displayed (if you'd be interested in adding that functionality I could provide a PR when done). 
For this I need to access the translation_key (to lookup the audio file), so I added this to dialogue_line.gd:

`var translation_key : String`
and in _init
`translation_key = data.get("translation_key")`

If this makes sense, would you consider adding this? Thanks

**Comment by nathanhoad** [comment]
I've added `translation_key` to both `DialogueLine` and `DialogueResponse`.
