### ISSUE TITLE
Lag when example balloon is spawned

### ISSUE THREAD

**Issue by Only-a-cat** [nathanhoad/godot_dialogue_manager#346]
**Describe the bug**
My game freezes in 4 or 5 seconds when I spawn the example balloon

**Affected version**

- Dialogue Manager version: 2.27.2
- Godot version: 4.1.2

**To Reproduce**

```gdscript

@export var dialogue_resource: DialogueResource
DialogueManager.show_example_dialogue_balloon(dialogue_resource, "this_is_a_node_title")

```

**Comment by nathanhoad** [comment]
Can you provide an example project that demonstrates the issue?

**Comment by nathanhoad** [comment]
I'm assuming you're the same person from Discord (correct me if that isn't true) so I'll comment here too - it looks like the issue is the fonts you're using and how you're loading them.
