### ISSUE TITLE
mutate function missing yield

### ISSUE THREAD

**Issue by Alec-15** [nathanhoad/godot_dialogue_manager#35]
When creating a dialogue that emits a signal with an argument `do emit("dialogue_event", "arg")`, mutate() doesn't yield and line 82 throws an error:
`First argument of yield() not of type object.`
In order to use `"completed"` on a function in yield, the function itself must yield.

This is easily solved by unindenting lines 280-281 by one, so that we always yield:
```
	# Wait one frame to give the dialogue handler a chance to yield
	yield(get_tree(), "idle_frame")
```

**Comment by nathanhoad** [comment]
Thanks. I've made that change 👍
