### ISSUE TITLE
Parser Error: Could not find type "DialogueLabel" in the current scope error after updating

### ISSUE THREAD

**Issue by NascentSpace** [nathanhoad/godot_dialogue_manager#359]
I updated the dialogue manager addon and am now getting the error from the title whenever I try to do a quick test of the dialogue...
Error originating on line 6 of the example_balloon.gd script.

**Comment by nathanhoad** [comment]
If you remove the `.godot` folder in your project and then restart the editor does it go away?

**Comment by connordechart** [comment]
> If you remove the `.godot` folder in your project and then restart the editor does it go away?

It does not

**Comment by NascentSpace** [comment]
> If you remove the `.godot` folder in your project and then restart the editor does it go away?

I deleted the DialogueManager addon and then reinstalled and updated it and that seemed to fix it.

**Comment by nathanhoad** [comment]
Yeah it sounds like it's more an issue with Godot's class cache than with Dialogue Manager itself.
