### ISSUE TITLE
BBCode is not working properly in choices

### ISSUE THREAD

**Issue by FoxReds** [nathanhoad/godot_dialogue_manager#36]
As you can see in pics BBCode don't work properly in choices. Not sure if it's a bug or I did something wrong but I think it's worth checking...
<img width="423" alt="Screenshot 2022-03-09 at 14 16 18" src="https://user-images.githubusercontent.com/53920262/157459596-9aa16ab6-64fd-4b5c-a368-19ef99a42da5.png">
<img width="610" alt="Screenshot 2022-03-09 at 14 16 52" src="https://user-images.githubusercontent.com/53920262/157459605-59742eda-e356-47ab-bc7b-cb8fd853649c.png">

**Comment by nathanhoad** [comment]
Yeah I somehow had BBCode disabled on the response labels. Fixed now 👍
