### ISSUE TITLE
Allow us to indicate a kind of local State Shortcuts for different dialogue file independently

### ISSUE THREAD

**Issue by JustusPan** [nathanhoad/godot_dialogue_manager#364]
**Is your feature request related to a problem? Please describe.**
I'm making a project which include several different sub-games with different genres,
they should be regard as having different "story worlds", but they are in a same project.
Now, in each "story world", I need similar methods set like `add_item_to_bag()`, `hurt_player()` etc.
and the implementation of they are different.
with the amount of worlds growing, I have to add more and more Autoload file and registered them in Dialogue setting.
and, they method name will conflict with each other, I have to modified the method name with more prefix which decrease the readability of dialogue text.

**Describe the solution you'd like**
Allow us write some syntax like shown below, at the top of a dialogue file
`using "SharedDialogueGlobal"` 
`using "TswDialogueGlobal"`

to register multiple Autoloads `SharedDialogueGlobal` and `TswDialogueGlobal` only in a dialogue file context

**Describe alternatives you've considered**
godot has a method named `get_singleton` which allow us find a autoload with its string name, maybe this could also help?

**Additional context**
another scenario is that I want to decouple the `*.dialogue` with project setting, it's better and flexible to allow it self contain the 
autoload context.

**Comment by nathanhoad** [comment]
I'll be adding the `using` statement to dialogue but you won't need the quotes around the autoload name.
