### ISSUE TITLE
Feature? Show selected response line

### ISSUE THREAD

**Issue by mzoeller** [nathanhoad/godot_dialogue_manager#38]
Not sure if this is possible yet without adding code to the example balloon:
Right now, the response line that is selected, is not displayed before the reply is displayed.
Maybe this could be a toggle?

**Comment by nathanhoad** [comment]
I'm not sure I understand what you mean. Would you be able to provide more information?

**Comment by mzoeller** [comment]
I'm sorry that was not very descriptive :)

Right now, only the lines that are spoken are displayed, the line one selects as the reply are not "read out".
In classic adventure games this is usually the case, though: https://youtu.be/BjQqd0zNI-w?t=4759

So instead of 
```
~ loop
- Yes, sorry for that!
	Laura: No problem.
```
I have to repeat the selected line, i.e.:
```
~ loop
- Yes, sorry for that!
	Lisa: Yes, sorry for that!        
	Laura: No problem.
```
I can hack it into my example balloon but I thought it would be a good candidate for a global setting in the options, so devs can decide the behavior depending on their game.

**Comment by nathanhoad** [comment]
I've just added a syntax shortcut that should achieve the same thing. Now you can do something like:

```
~ loop
- Lisa: Yes, sorry for that!
	Laura: No problem.
```

If a response has a character name in it then it will get added as a line of dialogue automatically when the player selects it. The character name will get stripped out of the example balloon prompt list but it will be shown when the player selects that response.

**Comment by mzoeller** [comment]
Perfect! :)
