### ISSUE TITLE
Please add a way for a line to know what its section title id is!

### ISSUE THREAD

**Issue by Drillur** [nathanhoad/godot_dialogue_manager#382]
For my game, I want to keep track of which sections the player has read through. This way, I can add more reactive dialogue.

I came up with a manual solution: At the end of every section, I write `{{mark_section_read("section_title"}}`. I created a mark_section_read() function in my own script, and it accepts a string. I have to manually pass the title name for every section.

I don't want to copy-paste this code for every section. I want a cooler way to do it! An automated way!

I see that you have lines{} and titles{} in dialogue_resource.gd. I almost found a way to do it with those. I guess my brain is too smooth.

If you are unable to add this feature, I'll probably figure it out and update my post if I'm able to.

**Comment by nathanhoad** [comment]
This is something you'd have to implement in your game. The Dialogue Manager is stateless so it tracks nothing on it's own and also has no definitive concept of "sections" - titles are used more as markers than actual chapter headings.

There is a [`passed_title(title)`](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/API.md#signals) signal that might help you out.

**Comment by Drillur** [comment]
Yup, passed_title is a perfect way to solve my issue! Whenever passed_title is emitted, I store it. Before I store it, I mark the previous passed_title as read!
Thanks! You're doing great work.
