### ISSUE TITLE
Backward incompatible change makes balloons based on old example to advance automatically

### ISSUE THREAD

**Issue by ForestGameDev** [nathanhoad/godot_dialogue_manager#387]
**Describe the bug**
It seems in latest version you changed class DialogueLine to initialize time as default as "". However in previous versions, null value was used to identify if the dialogue line had a time to auto-advance. This means that people updating to this version will start to get their dialogue moving to the next line automatically if they followed your previous example.

This is not exactly a bug I guess, but it is a backward-incompatible change, which in my opinion should be avoided whenever possible, as they make people to fear upgrading to the latest versions.

**Affected version**

- Dialogue Manager version:  v2.29.1
- Godot version: 4.1

**To Reproduce**

In balloon dialogue_line setter,  having the following condition will make the dialogue to keep going next automatically.
```
if dialogue_line.time != null:
    var time = dialogue_line.text.length() * 0.02 if dialogue_line.time == "auto" else dialogue_line.time.to_float()
    await get_tree().create_timer(time).timeout
    next(dialogue_line.next_id)
```

**Expected behavior**
Again, this could be considered not a bug, since you updated your example as well. Maybe at least you could mention in the release notes when you make changes that required you to update your examples, as people build on top of them.

**Screenshots**
N/A

**Comment by nathanhoad** [comment]
I'd usually avoid breaking changes too but this one is more correcting a design flaw that shouldn't have been there in the first place (and this is probably the only one of those that I know of).

I've updated the release notes to mention it.
