### ISSUE TITLE
Invalid call. Nonexistent function 'new' in base 'CSharpScript'

### ISSUE THREAD

**Issue by RandomFckgUser** [nathanhoad/godot_dialogue_manager#388]
**Describe the bug**
Whenever I try to start my game/a dialogue, the game crashes and this is the error, it's not a problem of one of my dialog since I tried loading it without any dialog and with a simple dialog and both crashed with the same issue

**Affected version**

- Dialogue Manager version: 2.29.2
- Godot version: 4.1.3

**To Reproduce**
1. Download Dialogue Manager
2. Enable the plugin
3. Start the game

**Expected behavior**
I expected the game load, and in the dialogue pretty much the same

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/152081473/4668ff17-b8c5-46af-9d38-6d2a871fcff3)

**Comment by meloncolle** [comment]
Can confirm I am having this same issue.

**Comment by CarlJMcGee** [comment]
While @meloncolle solution does work, unless you are actually doing any C# coding, there is no reason to create a C# solution. Just go into the `addons/dialogue_manager/` folder and delete `CSharpScript.cs`. As far as I can tell, it is only necessary for C# projects.

**Comment by RandomFckgUser** [comment]
> While @meloncolle solution does work, unless you are actually doing any C# coding, there is no reason to create a C# solution. Just go into the `addons/dialogue_manager/` folder and delete `CSharpScript.cs`. As far as I can tell, it is only necessary for C# projects.

It worked tysm
