### ISSUE TITLE
Nicer text animation

### ISSUE THREAD

**Issue by tavurth** [nathanhoad/godot_dialogue_manager#4]
Previously I built a dialog manager in a similar style to the Animal Crossing games with a small sound effect as each character is played.

How would be the best way to go about implementing this in the godot-dialogue-manager?

On each character played a small note is also played to give the illusion of some speech.

https://user-images.githubusercontent.com/100964/151955297-a182cfb0-89a5-4eda-8220-0116f37606f8.mov

**Comment by nathanhoad** [comment]
Part of a big update I'm working on will make "talk noises" easier to implement.
