### ISSUE TITLE
Some times editor gives output error when no dialogue is loaded

### ISSUE THREAD

**Issue by Alec-15** [nathanhoad/godot_dialogue_manager#40]
Sometimes when I start Godot up and the no dialogues is loaded.
I get an error in the output: line 80 in main_view.gd can't call raw_text on null (sorry I didn't capture it).

Changing line 79 to:
`if is_instance_valid(editor) and current_resource:`
Fixes it

**Comment by nathanhoad** [comment]
Good catch 👍
