### ISSUE TITLE
If you delete the text in the box, nesting problems occur

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#41]
![image](https://user-images.githubusercontent.com/15027345/159171927-9a761335-3e3a-420c-953e-624d82c3f655.png)

**Comment by wayrboy** [comment]
![image](https://user-images.githubusercontent.com/15027345/159171990-878be7f6-87e8-43ef-9bc2-3ceb94074b24.png)

**Comment by wayrboy** [comment]
Can the function of adding temporary variables be added?

**Comment by nathanhoad** [comment]
I think I've fixed the issue causing the weird nesting.
