### ISSUE TITLE
Support External Editors

### ISSUE THREAD

**Issue by OpenSauce** [nathanhoad/godot_dialogue_manager#410]
Yo! Great work - I've been using your dialogue plugin in my series.

Sorry if this has already been suggested, I tried searching but nothing came up.

**Is your feature request related to a problem? Please describe.**
I use VS code as an external editor, dialogue files are opened in the Godot editor rather than VS code.

**Describe the solution you'd like**
When I click the dialogue files in Godot they should open in the external editor of choice if I have use external editor selected.

**Comment by nathanhoad** [comment]
I can probably make it open in the external editor of choice but you'll lose any syntax highlighting and inline error checking.

**Comment by OpenSauce** [comment]
> I can probably make it open in the external editor of choice but you'll lose any syntax highlighting and inline error checking.

Good point, could it be toggled in a setting maybe? Would be curious to try it!

**Comment by nathanhoad** [comment]
I've added it as an advanced option which only shows up in settings if you've configured an external editor in Editor Settings first.
