### ISSUE TITLE
Example baloon failed to load in 2.31.0

### ISSUE THREAD

**Issue by rena-souza** [nathanhoad/godot_dialogue_manager#421]
**Describe the bug**
The engine says that the type DialogueLabel class could not be found in the current scope. I suspect this may happen to me because I'm on linux, and it may load classes in a diferent order

**Affected version**

- Dialogue Manager version: 2.31.0
- Godot version: 4.2-stable
- OS: pop-os 22.04 LTS

**To Reproduce**

1. Upgraded plugin from version v2.15.5 => v2.31.0
2. Try to run an example dialogue with the default example balloon
3. The baloon will freeze and not run the dialogue

**Expected behavior**
It should run without issues

**Workaround**
I was able to bypass the issue changing the variable declaration from 
`@onready var dialogue_label: DialogueLabel = %DialogueLabel`
to
`@onready var dialogue_label := %DialogueLabel`

With this declaration style, I can run the example baloon without issues.  Although the auto completion features of godot doesn't work

**Screenshots**
If applicable, add screenshots to help explain your problem. Try to include as much detail as possible.

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/8316202/24fbd7cd-1cb5-4b93-bc11-f3109a6d41a4)

**Comment by nathanhoad** [comment]
If you remove the `.godot` cache folder and restart the editor (possibly twice) does it still have an issue with that class?

**Comment by rena-souza** [comment]
It did make it work actually. Didn't knew this could be the cause. Thank you for the support!
