### ISSUE TITLE
Missing GUI

### ISSUE THREAD

**Issue by Zachthebeast** [nathanhoad/godot_dialogue_manager#422]
I have downloaded and installed Dialogue Manager three times and every time when I enabled It in godot Most of the GUI is missing.

**Affected version**

- Dialogue Manager version: 2.31.0
- Godot version: 4.1.3

**To Reproduce**
Steps to reproduce the behavior: Download and install Dialogue Manager from the Godot asset store

**Expected behavior**
All of the GUI to pop up and me being able to make my games dialogue

**Screenshots**
![Screenshot 2023-12-14 6 35 36 AM](https://github.com/nathanhoad/godot_dialogue_manager/assets/146194830/7a080c08-575b-40ff-b9f9-4cc0fc5c37a4)

**Comment by nathanhoad** [comment]
I just downloaded a fresh copy of Godot v4.1.3 and installed Dialogue Manager from the AssetLib but can't seem to replicate this. Can you make a small project that demonstrates the issue happening?

**Comment by nathanhoad** [comment]
I'm closing this until there are further steps to replicate or a demo project.
