### ISSUE TITLE
Make it possible to search for a string in all of a project's .dialogue files

### ISSUE THREAD

**Issue by gatomesa** [nathanhoad/godot_dialogue_manager#424]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to search for a string in all the dialogue files inside a project.

**Describe the solution you'd like**
I think that the "Find in Files" window could be used, with one modification.
When the "Find in Files" shortcut is pressed while on the Dialogue tab, the "Find in Files" window shows up, the same as when one does it in the Script tab. The only difference would be that in "Filters", the only filter there would be "dialogue", checked by default.

**Describe alternatives you've considered**
Right now what I'm doing is using an external program (Visual Studio Code) for the search (and search-and-replace) functionality. However, this slows down my workflow.

**Additional context**
The "Find in Files" window is this one, just to be clear:
<img width="495" alt="image" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/119363621/14e51cc3-e246-4e58-badb-0dad3efa399e">

**Comment by nathanhoad** [comment]
This would definitely be useful. I'm not sure how soon I'll have a chance to build this though (Godot doesn't give direct access to the global search/replace stuff to plugins so it requires recreating a bunch of UI and functionality).

**Comment by zkcl** [comment]
Can maybe use another plugin along with this? Godot finder with some modification seems like it would work for this use case.
