### ISSUE TITLE
BBCode [img] shows up immediately

### ISSUE THREAD

**Issue by salianifo** [nathanhoad/godot_dialogue_manager#429]
**Describe the bug**
When using an image tag in a dialogue, it shows up as soon as the dialogue starts typing out.

**Affected version**

- Dialogue Manager version: 2.31.0
- Godot version: 4.2.1.stable

**To Reproduce**

1. Make a dialogue containing an [img][/img] tag
2. Run the dialogue
3. See the image show up immediately

**Expected behavior**
The image should only show up when the dialogue has reached that point.

**Screenshots**
See short video showing the issue in action.

https://github.com/nathanhoad/godot_dialogue_manager/assets/2348534/0aaa2c8f-1988-4fe0-9834-06a1e256c7d0

**Comment by nathanhoad** [comment]
This is a property on `RichTextLabel`s. I've [reverted it back to the default value](https://github.com/nathanhoad/godot_dialogue_manager/pull/431) (which shows images as they are typed out) in the `DialogueLabel`.

**Comment by chrislemelin** [comment]
Downloaded the dialogue manager recently for godot and had this issue, for some reason my version didn't have that revert on it, but the fix worked for me!
