### ISSUE TITLE
[2.32.1] BBCode [img] shows up immediately when using region

### ISSUE THREAD

**Issue by klaritan** [nathanhoad/godot_dialogue_manager#438]
**Describe the bug**
When using an [img region=x,y,w,h] tag in a dialogue, it shows up as soon as the dialogue starts typing out from its first letter.

**Affected version**

    Dialogue Manager version: 2.32.1
    Godot version: 4.2

**To Reproduce**

1. Make a dialogue containing an [img region=x,y,w,h][/img] tag
2. Run the dialogue
3. See the image show up immediately

**Expected behavior**
The image should only show up when the dialogue has reached that point.

**Comment by salianifo** [comment]
Are you using a custom balloon? If you are try changing `visible_characters_behavior` in the `DialogueLabel` (its under RichTextLabel -> Displayed Text) to `Characters Before Shaping`. This seems to be a bug in Godot itself, and I reported it recently.

**Comment by klaritan** [comment]
> Are you using a custom balloon? If you are try changing `visible_characters_behavior` in the `DialogueLabel` (its under RichTextLabel -> Displayed Text) to `Characters Before Shaping`. This seems to be a bug in Godot itself, and I reported it recently. EDIT: [Issue on Godot tracker](https://github.com/godotengine/godot/issues/86697)

Yes, but if I use `Characters Before Shaping`, it creates even more problem where words as they form would flash on the current line before they move down to the next line if they don't fit.

**Comment by nathanhoad** [comment]
I'm going to close this because it isn't really an issue with Dialogue Manager.
