### ISSUE TITLE
Do not include generated contents on the dialogue resource file

### ISSUE THREAD

**Issue by josejulio** [nathanhoad/godot_dialogue_manager#44]
**Is your feature request related to a problem? Please describe.**
Having the clear and concise dialog language is awesome. Thanks for that!

What I have seen in my short experience with this is that the text is being mixed with implementation details from the resource itself.
This makes it difficult with git conflicts where the text is repeated on the `rawText` and `lines`. This also adds a bit of redundancy.

**Describe the solution you'd like**
I would like to see a simple text file with the `rawText` contents (or the closer to only that). Was wondering if the `lines` (and maybe other fields) could be some kind of cached data that could be build at compile time from the text to keep it more simpler and have a nicer git conflict experience.

**Describe alternatives you've considered**
I haven't considered alternatives - not even sure if what I'm asking is possible.

**Additional context**
 None

**Comment by nathanhoad** [comment]
I'll add an option for choosing whether to pre-bake the compiled dialogue or have it compile at runtime. Personally, I prefer to pre-bake but I can see the use case for turning that off.
