### ISSUE TITLE
Implement docstring-style comments for exporting translations

### ISSUE THREAD

**Issue by IntangibleMatter** [nathanhoad/godot_dialogue_manager#440]
**Is your feature request related to a problem? Please describe.**
When you're making a game with a lot of dialogue, and exporting the translations,
you'll likely want to add some notes for the translators to help them understand what's going on.

**Describe the solution you'd like**
Godot now supports ignored columns in csvs, when they start with `_`. PO files have always supported comments. It would be convenient if you could add comments before a line that would then be used in an `_notes` column in the CSV or as comments in the .PO.

To avoid commented-out dialogue lines being used as notes, two hashtags could be used to denote these notes, similar to automatic documentation in Godot.

As an example:

```yaml
~ start
## This is a reference to the Rickrolling meme, with Never Gonna Give You Up by Rick Astley. If an equivalent phenomenon exists in your language, use it.
Rick: Hey, you know that we're no strangers to love, right?
## The player realizing they've been rickrolled.
You: God damn it.
=> END
```
which would create a csv file that looks something like
| key | en | notes |
|-|-|-|
| aGVsbG8gdGhlcmUK | Hey, you know that we're no strangers to love, right? | This is a reference to the Rickrolling meme, with Never Gonna Give You Up by Rick Astley. If an equivalent phenomenon exists in your language, use it. |
| Z2VuZXJhbCBrZW5vYmkK | God damn it. | The player realizing they've been rickrolled. |

**Describe alternatives you've considered**
You could also add all these comments manually, but that would be less convenient, and mean you would need to find the lines of dialogue in the csv.

**Additional context**
This would work well with #323

**Comment by nathanhoad** [comment]
I'll look into this when I get a chance to look back into #323

**Comment by nathanhoad** [comment]
I've got a PR up that adds settings for this and #323

Adding the comments automatically to POT exports isn't currently supported by Godot but I'll have a look at submitting a PR to Godot itself to add that.

**Comment by nathanhoad** [comment]
I've submitted [a PR](https://github.com/godotengine/godot/pull/87401) to Godot to add support for providing POT comments.
