### ISSUE TITLE
Unskippable first line with custom input

### ISSUE THREAD

**Issue by hanako-eo** [nathanhoad/godot_dialogue_manager#445]
**Describe the bug**
When I try to test to skip the dialogue, it works with the default balloon, but when change
```gdscript
if dialogue_label.is_typing and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT and event.is_pressed():
```
by
```gdscript
if dialogue_label.is_typing and event.is_action_pressed("ui_skip"):
```

the first dialogue_line cannot be skipped but the rest yes.
(ui_skip in my case is "Shift", "X" or gamepad "B")

**Affected version**

- Dialogue Manager version: 2.32.2
- Godot version: 4.2

**To Reproduce**

1. get the balloon exemple
2. change the line given above
3. try to skip the first

**Expected behavior**
the first skipped like the other

**Comment by nathanhoad** [comment]
I've simplified how the skip handling works so now it can be done completely from the balloon.
