### ISSUE TITLE
Randomized lines cannot have replies. It does not add them in the lines dictionary

### ISSUE THREAD

**Issue by Drillur** [nathanhoad/godot_dialogue_manager#446]
What I want is a series of randomized lines with randomized replies, like this:

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/51843489/4314afda-7a80-4325-8055-e8029a8854ef)

The player will have no input on these conversations, as they are just background dialogue.

However, if a randomized line has a reply, even a non-randomized reply, then it will fail this assertion: `assert(resource.lines.has(key), DialogueConstants.translate("errors.key_not_found").format({ key = key }))` Assertion failed: Key "9" not found.

---

I _did_ try this, and it fixed the issue of not adding the replies to the lines dictionary, but then it broke the randomization process of the top-level messages.

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/51843489/c98fc2bd-803b-4ed2-9390-2ff34db865c3)

Perhaps I can brute-force past this myself? But I figure you should know that it doesn't work.

If I'm simply using it incorrectly, boy would that be lame!

**Comment by Drillur** [comment]
I got it to work, and it is really ugly and inconvenient to write compared to the way I tried the first time. Yes, this is the only way to do it. If it has a reply, it must not be randomized. You cannot mix section jumps and regular lines in the same % randomized pool. They are grouped separately. So, lines without replies go in their own section, and then each line with a reply must also be in its own section.

```
~ COAL_RANDOM
%6 => c0
% => c1
% => c2

~ c0
% COAL: Dig, dig!
% COAL: Glad to help!
% COAL: Is this lump yours? [wait=1]Just kidding!
% COAL: I hope my posture is good.
% COAL: I sure am grateful for this shovel.
% COAL: Why is this stuff purple?
=> COAL_RANDOM

~ c1
COAL: If you didn't get enough, go ahead and take some more!
% CONCRETE: Gracias, amigo.
% JOULES: Thank you.
% COPPER_ORE: Well, shoot, there, boss, don't mind if I do!
=> COAL_RANDOM

~ c2
COAL: I always liked playing support.
% => c3
% => c4
% => c5
=> COAL_RANDOM

~ c3
TARBALLS: Support as in... buffer or healer?
COAL: Healer.
=> COAL_RANDOM

~ c4
IRON_ORE: ADC for life.
=> COAL_RANDOM

~ c5
IRON: I like to tank!
=> COAL_RANDOM
```

**Comment by nathanhoad** [comment]
I'm not really sure what you're trying to do but if you want to have separate groups of random lines then you can add an empty line between each group.

**Comment by Drillur** [comment]
The first screenshot is the most relevant to what I'm trying to do: Get randomized dialogue with no input from the player. The player won't be able to reply to anything. I also was trying to get randomized replies to certain lines, like at line 8--if Coal says the line on line 8, then 1 of those 3 characters below him would have a reply.

But there can be no reply like that to a random line.

**Comment by nathanhoad** [comment]
If you unindent all of those lines and then add empty lines between the grouped random lines it should do what you want.
