### ISSUE TITLE
Suggestions for the csv generated files workflow

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#45]
One of the small problems with the generated csv files is that if you want to change the dialogue later on you would have to generate a new csv file or overwrite the old one  meaning you will have to modify the csv file again for both the new generated keys and the old ones. 

I was thinking If it would be possible to instead of overwriting the file, we can just append to it the new keys that were added and replace any dialogue that changed while keeping the original translations

One way I can think of is storing the csv data into a dictionary and modifying it accordignly
Also it would be really nice if the save pop up remembered the last saving directory instead of opening in the same folder the tscn file is in.

**Comment by nathanhoad** [comment]
It currently tries to do a merge if you select an existing CSV file. 

If you use manual translation keys then it _should_ update just the dialogue that has changed. Without using manual keys there's no guaranteed way to know which line is which in order to update it.

I'll change the popup to try and remember the last used directory per file type though.

**Comment by RedXGames** [comment]
I am using the auto generated keys but everytime I overwrite the file I get this error :
--- Debugging process started ---
Godot Engine v3.4.3.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4400
OpenGL ES Batching: ON
 
--- Debugging process stopped ---
 core\compressed_translation.cpp:134 - Condition "bucket_table_size == 0" is true.

**Comment by nathanhoad** [comment]
It looks like that error might just be a Godot thing. I get it too but the generated file *seems* fine.

I've updated the translation export dialog window to remember where you last saved one though.
