### ISSUE TITLE
Passing arguments for characters

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#47]
**Is your feature request related to a problem? Please describe.**
For dialogue heavy VNs the text could get quite full with repetitive functions, for example changing the character emotions

Example : 
```
~ ask_about_dishes
do actor_emotion("mc", "thinking")
mc : Why are you doing dishes by hand? [TR:t0b190be9e7]
mc : Is the dishwasher broken? [TR:t72e4ba6e7b]
do actor_emotion("mom", "cheese")
mom : No honey, it's working just fine, I just like doing them manually sometimes [TR:t9744dbd84d]
mc : Is this the real reason? [TR:tdbf3168707]
do actor_emotion("mom", "thinking_back")
mom : Well...the dev drew me washing dishes and he forgot that there is a dishwasher! [TR:teac14c1038]
do actor_emotion("mom", "neutral")
mc : typical [TR:t0612d3d5fd]
```

the actor_emotion() function is repetitive and breaks the flow of the script and makes it less readable 

**Describe the solution you'd like**
Passing arguments for characters in the dialogue as follow : 
```
~ ask_about_dishes
mc "thinking": Why are you doing dishes by hand? [TR:t0b190be9e7]
mc "thinking": Is the dishwasher broken? [TR:t72e4ba6e7b]
mom "cheese": No honey, it's working just fine, I just like doing them manually sometimes [TR:t9744dbd84d]
mc "thinking": Is this the real reason? [TR:tdbf3168707]
mom "thinking_back": Well...the dev drew me washing dishes and he forgot that there is a dishwasher! [TR:teac14c1038]
mc "neutral": typical [TR:t0612d3d5fd]
```

and then we can use the balloon script to separate the arguments from the character name and handle the logic from there.
this could be very useful for heavy dialogues VNs and could be used for other stuff other than character expressions, maybe changing characters positions on the screen just like in renpy

**Comment by nathanhoad** [comment]
While this is a good idea it is a bit too game specific for me to add into the Dialogue Manager core. I think it will work better as something implemented into your game's dialogue balloon.
