### ISSUE TITLE
Inconsistent Parser Error When Running from Editor

### ISSUE THREAD

**Issue by NoShenGG** [nathanhoad/godot_dialogue_manager#471]
**Describe the bug**
Every now and again, when attempting to run my scene, a Parser Error appears that says it could not resolve member "responses" on line 394 of dialogue_manager.gd. I've attempted to make sense of the error by adding breakpoints, but I can't seem to get breakpoints to work. This happens more frequently after I make changes to some C# script in Rider and run the scene after making those changes.

**Affected version**

- Dialogue Manager version: v2.33.1
- Godot version: 4.2.1.stable.mono

**To Reproduce**

1. Attempt to run a scene that doesn't contain anything (as far as I know) related to Dialogue Manager except the global autoload.
2. Randomly encounter Parser error after making changes to other C# scripts.

**Expected behavior**
DialogueManager is autoloaded and the scene runs normally without error.

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/53906364/118309ce-3585-4bf7-9ac9-60ec8822897b)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/53906364/91928d6b-81ff-4b01-8400-a275b6b44924)

**Comment by NoShenGG** [comment]
I know something that's random and without cause is hard to diagnose, but I've been scratching my head for a while trying to figure out what was causing this. I assume it's related to editing my C# scripts since it's only happened every now and again after editing them, but I'm not sure what exactly is causing the problem within them. It only happens on my desktop too. Running the project on my laptop doesn't seem to trigger the error at all. Just some guidance to start looking would be helpful!

**Comment by nathanhoad** [comment]
Do you get a stack trace of what was being called to get there?

**Comment by NoShenGG** [comment]
I don't have access to my desktop often enough to test it, but, from my memory, it didn't appear to have a stack trace for some reason when the error pops up. I believe that it is probably related to #473 in some capacity as well, since it might be trying to run get_next_dialogue_line for some reason and I might be forcing it to run in editor somehow by introducing build time with C# editing?

**Comment by NoShenGG** [comment]
Managed to capture a full screenshot of the Debugger window
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/53906364/e00ec0b0-2cdb-4e7d-a575-83d5a19143ea)

**Comment by NoShenGG** [comment]
[MSBuild_Log.txt](https://github.com/nathanhoad/godot_dialogue_manager/files/14190351/MSBuild_Log.txt)
[MSBuild_Log2.txt](https://github.com/nathanhoad/godot_dialogue_manager/files/14190350/MSBuild_Log2.txt)

I'm including the MSBuild output as well that's generated when I run the scene. The first one labeled MSBuild_Log.txt is the one that accompanied the Parser Error and the second one labeled MSBuild_Log2.txt is what was generated after I reran the scene.

**Comment by NoShenGG** [comment]
Just to add even more context, my laptop has .NET SDK 6 while my desktop has .NET SDK 7. It might make a difference so I will experiment around with it.

**Comment by nathanhoad** [comment]
Do you see it on both your laptop and your desktop?

**Comment by NoShenGG** [comment]
I only get it on my desktop for some reason. Not quite sure what the difference is still between the two of them besides just physical hardware.

**Comment by nathanhoad** [comment]
I'm on .NET SDK 8 on both my Desktop and my Surface and haven't come across anything like that (though I admittedly don't use Godot with C# that much).

**Comment by NoShenGG** [comment]
Thank you for all of your help so far! I've really been kicking myself with this for a while now, but it seems as though the root cause goes beyond Dialogue Manager itself and into some potential race conditions with autoloads in general for my project? That would explain why differing hardware would present the issue. However, I don't see why or how these race conditions are created. As the issue seems to stem outside of just Dialogue Manager though, I don't see the point in pushing this topic here specifically any further. Thank you for your help though!

**Comment by GovermanGambo** [comment]
I'm getting the exact same error in my own project, and a friend is getting the error every time she tries to launch the game while I'm only getting it about 20% of the time. I'm also using Rider, and the error occurs more frequently after updating C# scripts without recompiling manually. Breakpoints does not work. I've been able to bypass the error by guarding the `responses` property call with checks or `get()`/`set()`, but then I get errors about `DialogueResource` not being defined in the scope. There seems to be some general GDScript parsing error here when using .NET.

**Comment by mprystupa** [comment]
I think I might be experiencing similar issue, and it also seems to be happening only occassionally, although the error is different in this case:

![Image](https://github.com/user-attachments/assets/f05e46ab-1162-4974-a3f4-ce025f132fe5)

I do hope it's not related to my setup per se, but if it is, I have no idea what might be causing it...
