### ISSUE TITLE
Allow nested properties in conditions and mutations

### ISSUE THREAD

**Issue by stephanbogner** [nathanhoad/godot_dialogue_manager#478]
## Is your feature request related to a problem? Please describe.
To keep my structure clean I want to use a dictionary that stores dialog relevant information when using [conditions](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md#conditions) and mutations.

For example:
```
var conditions = {
    "level_1": {
        "talked_to_john": false,
        "met_robin": true,
    },
    "level_2": {
        ...
    }
}
```

## Current behaviour
Will trigger the error `Invalid call. Nonexistent function 'get' in base 'Nil'.` in `dialog_manager.gd` at line 858

## Describe the solution you'd like
`if DialogVariables.conditions.talked_to_john == false` should ideally work

## Describe alternatives you've considered
I could of course use long variables name like `level_1_talked_to_john`.

## Additional context
I am not sure yet how our save system is gonna work, but if a single dictionary contains all variables it would be really easy to save and load. Much easier than individual variables.

**Comment by nathanhoad** [comment]
This is already supported. Your example is `DialogVariables.conditions.talked_to_john` but should probably be `DialogVariables.conditions.level_1.talked_to_john`.

**Comment by stephanbogner** [comment]
🤦‍♂️ As you spotted correctly ... even in my simplified/fake example I typed the dictionary path wrong.
This is also what happened in my actual code. Thanks for helping me.

PS: I already mentioned in the last issue but this plugin is great. Thanks a lot!
