### ISSUE TITLE
Using the return value of the same function in a dialog will only show the return value of one function.

### ISSUE THREAD

**Issue by Abab-bk** [nathanhoad/godot_dialogue_manager#484]
**Describe the bug**
Prepare the following dialog:
Get skills: {{Master.get_new_random_ability()}}, {{Master.get_new_random_ability()}}
(get_new_random_ability() returns a String)
But in the game both function return values are displayed as the first function's return value.

**Affected version**

- Dialogue Manager version: v2.32.0
- Godot version: 4.2.1 Stabel

**To Reproduce**

1. Preparation of dialogues.
2. See error.

**Expected behavior**
The correct return value will be show.

**Screenshots**
If applicable, add screenshots to help explain your problem. Try to include as much detail as possible.

**Comment by nathanhoad** [comment]
That isn't a bug with Dialogue Manager - just the nature of Godot's randomisation. The default randomiser uses the system clock to generate a value so if you're calling it twice in the same tick you might want to also pass in a value to reseed it with each call.

**Comment by Abab-bk** [comment]
No .... This is indeed a bug, see the picture.
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/55276676/b2f74e48-2365-4bc5-bfac-1cf7398a2a7f)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/55276676/9643d3b2-9e94-4111-9e3a-f04d34a6cc58)

**Comment by Abab-bk** [comment]
@nathanhoad

**Comment by nathanhoad** [comment]
Ah yep, I think I know what it might be then.
