### ISSUE TITLE
async method not exist that return Task in C#

### ISSUE THREAD

**Issue by gnenux** [nathanhoad/godot_dialogue_manager#487]
**Describe the bug**
Hi, sorry for my english. I added Mutations to the dialogue system based on [this document](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/CSharp.md#mutations), and found async function not exist that return "Task" in C#

**Affected version**

- Dialogue Manager version: 2.34.0
- Godot version: 4.2.1

**To Reproduce**
```md
# dialogue file
	npc: line1
	do ShowStorePage(npc)
	npc: line3
```

```csharp
        // V1
        public async Task ShowStorePage(GameplayCharacter merchant)
        {
            var storePage = StorePageWidget.Instantiate();
            storePage.Merchant = merchant;
            HUD.Singleton.ShowWidget(storePage);

            await ToSignal(storePage, Control.SignalName.TreeExiting);
            storePage.QueueFree();
        }

        // V2
        public async void ShowStorePage(GameplayCharacter merchant)
        {
            var storePage = StorePageWidget.Instantiate();
            storePage.Merchant = merchant;
            HUD.Singleton.ShowWidget(storePage);

            await ToSignal(storePage, Control.SignalName.TreeExiting);
            storePage.QueueFree();
        }
```
1. The V1 "ShowStorePage" will report "ShowStorePage not exits".
2. The V2 "ShowStorePage" not report error, but it does not wait for the async function to finish executing. And will goto the "npc: line3" immediately.

**Expected behavior**
The V1 "ShowStorePage" executes normally.

**Screenshots**

![屏幕截图 2024-02-21 173719](https://github.com/nathanhoad/godot_dialogue_manager/assets/14236891/5410dbf4-69b4-43e5-a4a0-2afa5e5b662f)

**Comment by nathanhoad** [comment]
What version of the .NET SDK do you have? And can you attach a small project that demonstrates the issue?

**Comment by gnenux** [comment]
> What version of the .NET SDK do you have? And can you attach a small project that demonstrates the issue?

```
.NET SDK (反映任何 global.json):
 Version:   6.0.321
 Commit:    61baf6999b

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.321\

global.json file:
  Not found

Host:
  Version:      6.0.26
  Architecture: x64
  Commit:       dc45e96840

.NET SDKs installed:
  6.0.321 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
dotnet version: 6.0.321.

I have found that because the function is defined in the parent class, there is no problem if it is defined in the direct subclass.
Please refer to the attached item.
[DialogueTest.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/14358558/DialogueTest.zip)
