### ISSUE TITLE
Add parameters to the title

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#49]
![image](https://user-images.githubusercontent.com/15027345/162601718-0eb78643-367a-4bf4-b1ff-5470394c5139.png)

like this

**Comment by nathanhoad** [comment]
This would be adding too much complexity for what might be a niche feature.

You can already do something like this with:

```
- asdf
	set a = 1
	=> asdf

~ asdf
	do get_hope_money(a)
```
