### ISSUE TITLE
Issue when starting a dialogue too fast after waiting for previous dialogue's "dialogue_ended" signal.

### ISSUE THREAD

**Issue by scyfris** [nathanhoad/godot_dialogue_manager#499]
**Describe the bug**

I _think_ this is a bug, please let me know if not!

This happens when starting a dialogue immediately when the dialogue's "dialogue_ended" signal is received.  Another signal "bridge_get_next_dialogue_line_completed" has yet to be fired when "dialogue_ended" is fired, so a new dialogue would catch the old "bridge_get_next_dialogue_line_completed" if it hasn't been emitted yet and null out.  I believe this happens in C# only (haven't tested GDscript variant).

 What I'm doing is something like this:

 1) Fire some dialogue using DialogueManager.ShowDialogueBalloonScene().  This calls into C# function GetNextDialogueLine().
 2) I set my code to Connect() a callback on signal "dialogue_ended"
 3) During my Connect()'ed "dialogue_ended" callback, I immediately start a new dialogue via ShowDialogueBalloonScene().
 4) The new dialogue never starts up!

I believe the reason for (4) never starting is because "dialogue_ended" gets fired during dialogue_manager.gd's "get_next_dialogue_line()" function.  BUT, once that signal is fired, the dialogue manager hasn't really finished, because the enclosing function "_bridge_get_next_dialogue_line()" still needs to fire off its internal "bridge_get_next_dialogue_line_completed".  If a new dialogue starts too quickly and enters GetNextDialogueLine(), it waits for the internal signal "bridge_get_next_dialogue_line_completed" and intercepts the PREVIOUS dialogues emission if it hasn't happened yet.  It then gets NULL because it is receiving the end of the previous dialogue.

As a workaround, in my code, instead of cehcking for "dialogue_ended" signal before starting a new one, I need to check for "bridge_get_next_dialogue_line_completed".  But this doesn't feel right, since that is marked as "internal" in the comments inside dialogue_manager.gd.

**Affected version**

- Dialogue Manager version: v2.34.0
- Godot version:  v4.2.1.stable.mono.official [b09f793f5]

**To Reproduce**
I didn't have time to create a reproducer, but it should be trivial - just try calling into DialogueManager.ShowDialogueBalloonScene(), then Connect() a callback to the "dialogue_ended" signal, then in the allback do another call to DialogueManager.ShowDialogueBalloonScene().  This may also be affected by the system since I'm assuming some multithreading is occurring here.

**Expected behavior**
A new dialogue to pop up.

**Comment by nathanhoad** [comment]
I've opened [a PR](https://github.com/nathanhoad/godot_dialogue_manager/pull/502) that should resolve this if you wanted to try it before I merge it.
