### ISSUE TITLE
Escape ":" if it's part of a dialogue line

### ISSUE THREAD

**Issue by stdll** [nathanhoad/godot_dialogue_manager#5]
I chose your dialogue plugin for my first game built with Godot and it looks very promising!

Is it possible to handle ":" differently if it's just part of a dialogue line, maybe with an escape sequence?
If no character is speaking, the whole part before ":" becomes the character.
If a character is speaking, the part after ":" is not shown.

**Comment by nathanhoad** [comment]
I'll update it so that you can use `\:` to escape a colon (on lines which no character) and fix it so having multiple colons doesn't chop off the end of a dialogue line.
