### ISSUE TITLE
Change action for skip_action in the DialogueLabel node.

### ISSUE THREAD

**Issue by AsixJin** [nathanhoad/godot_dialogue_manager#50]
Currently, the skip_action used in the DialogueLabel node is set to "ui_cancel" and I was wondering if it would be possible to be able to change that. I'm currently changing it to what I need before the label starts doing its thing so it's not a big deal, but I'd thought I ask.

**Comment by nathanhoad** [comment]
The **skip_action** in the `DialogueLabel` is an export variable so you can change it in the property inspector in your dialogue balloon.

**Comment by AsixJin** [comment]
Apologies! I didn't even realize it was exported. Thank you!
