### ISSUE TITLE
DialogueManager "Parse error"

### ISSUE THREAD

**Issue by mickeyordog** [nathanhoad/godot_dialogue_manager#503]
**Describe the bug**
I've never had this error when running on Mac, but sometimes when I run my game on Windows, I get a "parse error" right at the start. DialogueManager subsequently won't work properly until I close the game and run again.
```
E 0:00:34:0861   load: Failed to load script "res://addons/dialogue_manager/dialogue_manager.gd" with error "Parse error".
  <C++ Source>   modules/gdscript/gdscript.cpp:2788 @ load()
```

**Affected version**

- Dialogue Manager version: 2.35.0
- Godot version: v4.2.1.stable.mono.official [b09f793f5]

**To Reproduce**

1. Run game

**Expected behavior**
Game should proceed without error

**Comment by mickeyordog** [comment]
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/0f9ea085-6c4a-409a-875d-7aa51dbf0548)
More info: here's what I see in the editor when this happens

**Comment by nathanhoad** [comment]
I've seen one or two people run into something similar but we've yet to nail down what the cause is.

What version of the dotnet SDK do you have on your Mac and which one on Windows?

And if you change [line 411](https://github.com/nathanhoad/godot_dialogue_manager/blob/v2.35.0/addons/dialogue_manager/dialogue_manager.gd#L411) to... 

```gdscript
line.set("responses", await get_responses(data.get("responses", []), resource, id_trail, extra_game_states))
``` 

...does it make a difference?

**Comment by GovermanGambo** [comment]
I was also having this issue, but was able to fix it using `get` and `set` methods as you suggest above. Seems to be some strange race condition with the parsing of the scripts

**Comment by mickeyordog** [comment]
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/e7dc26a8-9fa4-49c7-a292-376b9c991972)
Here is the version for my Windows dotnet.
Thanks for the help, I made that change and ran the game about 20 times and didn't see the error again. I'll keep checking for the next few days and if I don't see the error again I'll come back to let you know and close the issue.

**Comment by mickeyordog** [comment]
Update: Nope, I'm still getting the error. My version on mac is `7.0.403`

**Comment by nathanhoad** [comment]
Is it the same line number and same error?

**Comment by mickeyordog** [comment]
I believe so, but when I get the error again I can report back

**Comment by mickeyordog** [comment]
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/b2a3f296-0648-418e-9fac-a696ed1c3738)
Yep got it again. I believe this is the same line?

**Comment by nathanhoad** [comment]
That's a line further down and doesn't have the same `get`/`set` stuff applied. I've implemented the fix for both occurrences as part [this PR](https://github.com/nathanhoad/godot_dialogue_manager/pull/507/files#diff-2bee43b84f968052ea147b011a4360a7a8154d92be8f1d2daf12e22256c40ed9R432) if you wanted to give it a try.

**Comment by mickeyordog** [comment]
Oh my mistake, you're right. Thanks for the fix!

**Comment by mickeyordog** [comment]
Hey @nathanhoad , I pulled your fixed but just got an error on a different line unfortunately
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/5ca7076c-043a-449d-9713-b987cbf905b9)

**Comment by nathanhoad** [comment]
Looks like it could use another `get("responses", [])`.
