### ISSUE TITLE
Short method names not working

### ISSUE THREAD

**Issue by mickeyordog** [nathanhoad/godot_dialogue_manager#504]
**Describe the bug**
I have a class KeeperDialogManager.cs with a public method Emote(string character, string emote) that I want to call from a script. KeeperDialogManager is an autoload and the global checkbox is checked. However, inside a dialogue script, the function does not get called properly if I just write eg `Emote("player", "happy")`, it only works if I write the full `KeeperDialogManager.Emote("player", "happy")`. Do you know why this might be?

**Affected version**

- Dialogue Manager version: 2.35.0
- Godot version: v4.2.1.stable.mono.official [b09f793f5]

**To Reproduce**

1. Call function without class name

**Expected behavior**
Function should call properly

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/7a32da83-e38b-4735-8e13-cff717fe954f)

**Comment by mickeyordog** [comment]
Wait hold on, I was just checking the global checkbox in the autoload settings. Though this from the documentation appears to be a different checkbox? Do you know where i could find this? It isn't in the Project settings > Dialogue Manager panel
<img width="1331" alt="image" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/de970784-b7f3-42d7-b8bd-49cec31e2df5">

**Comment by nathanhoad** [comment]
It's in the Dialogue Settings window that you can open from this button: 
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/78984/1f6c3f1c-f764-4353-90b5-cbf41a5c8a67)

You can also add `using KeeperDialogManager` to the top of a dialogue file and then shortcuts work the same way.

**Comment by mickeyordog** [comment]
Thanks for the help, didn't realize that settings panel existed.
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/06a170e0-8ee4-485b-ba11-2efcea35e8f2)
So I checked the box here, the shortcut works if I put `using KeeperDialogManager` at the top like you said, but without it I get an error saying the function was unable to be found. I double checked that KeeperDialogManager is being autoloaded and is global. Any ideas?

**Comment by mickeyordog** [comment]
Hold on, it just started working as expected now. Maybe I just needed to restart the editor or something. Thanks for the help in any case.
