### ISSUE TITLE
Bug if section begins with a "response"

### ISSUE THREAD

**Issue by mickeyordog** [nathanhoad/godot_dialogue_manager#505]
**Describe the bug**
I have the following dialogue:
```
~ start
Doctor: What do you say?

~ response
- Yes
- No
	Doctor: Pretty please? 
	=> response
Doctor: Excellent!
```
When the dialogue runs and goes from the "what do you say" to the response options, the title_passed signal does not fire. (Another probably related problem: only this situation also results in the dialogue bubble being empty while the responses are shown in game)

I did some testing and found that if a => is used to jump to the `response` title, then the signal fires normally. Additionally, if I add some text such as `Doctor: Will you do it?` right under the `response` title, then the signal also fires as expected. So it seems to be a bug with a title being immediately followed by a response.

Why does this matter? I'm using the `title_passed` signal to make note of which titles the player has seen already, which I need so I can e.g. not show certain dialogues twice.

**Affected version**

- Dialogue Manager version: 2.35.1
- Godot version: v4.2.1.stable.mono.official [b09f793f5]

**To Reproduce**

See above

**Expected behavior**
n/a

**Screenshots**
n/a

**Comment by nathanhoad** [comment]
I've opened [a PR](https://github.com/nathanhoad/godot_dialogue_manager/pull/507) that should address the issue if you wanted to give it a go before I merge it.
