### ISSUE TITLE
Allow writing comments in dialogue

### ISSUE THREAD

**Issue by mickeyordog** [nathanhoad/godot_dialogue_manager#506]
**Is your feature request related to a problem? Please describe.**
It would be nice to have this for the same reasons we use comments in code. In particular I'd really like to be able to write myself todos on places I'd like to expand the dialogue more, or if I want to add a mutation and haven't implemented it yet. Right now, I don't see any way to do this that won't impact the player.

**Describe the solution you'd like**
Some way to specify that a line is a comment

**Comment by nathanhoad** [comment]
Comments are already available but you did just make me realise they weren't mentioned in the docs [until now](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md#comments).

You can write comments with lines that begin with `#` like:

```
# This is a comment
Nathan: You can't see it in the game but there's a comment here.
```

**Comment by mickeyordog** [comment]
Awesome, thanks! Might also be good to let a line be commented in the editor using ctrl + /, like it does in the normal editor
