### ISSUE TITLE
Requesting the ability to fold/unfold title blocks

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#51]
**Describe the solution you'd like**
Well it's failry simple, It's kinda the same thing that we have with the godot script editor where you can fold/unexpand blocks of code such as functions and classes only this time inside the dialogue text editor to fold titles. I dont know if it's an easy task to do but this would really help games with lots of dialogs

**Comment by nathanhoad** [comment]
Unfortunately, the folding in Godot 4 is limited to indented blocks so I'm not going to be able to fold titles. With the way titles now work in version 2 (as general markers) it probably doesn't make as much sense to fold them any more anyway.
