### ISSUE TITLE
Allow LUA syntax for dictionaries

### ISSUE THREAD

**Issue by yongan-game** [nathanhoad/godot_dialogue_manager#511]
**Is your feature request related to a problem? Please describe.**
Akin to how GDScript supports both normal (e.g. { "foo": bar }) and LUA (e.g. { foo = bar }) syntax for dictionaries, it would be nice if Dialogue Manager also allowed for it too.

**Describe the solution you'd like**
As mentioned, LUA syntax for dictionaries.

**Describe alternatives you've considered**
A simple alternative is obviously just using the normal syntax. This is a pretty low priority request honestly, but still nice to have

**Additional context**
https://docs.godotengine.org/en/stable/classes/class_dictionary.html

**Comment by nathanhoad** [comment]
I've opened [a PR](https://github.com/nathanhoad/godot_dialogue_manager/pull/514) that adds Lua syntax support if you wanted to give it a try.

**Comment by yongan-game** [comment]
I tried out the PR quickly just now with my game's test conversation and it all seems to be working fine so far, but I did notice an error when it comes to syntax highlighting that I think might already exist elsewhere but I notice more obviously with the LUA syntax.

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/88519061/2f7c8b00-5876-48f2-b5a2-630e6639c745)
If you look above at the red underline, the whole dictionary is coloured as a string, even though both strings on this line are closed; you can actually see some weird syntax colouring with the string at the blue underline too.

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/88519061/1d742987-c30e-47c5-9cd1-5b5b996f0f72)
If you look at the second image, you can see the text `, { ` coloured as a string before the dictionary key, so I think this problem existed beforehand.

In any case, as far as the functionality requested is concerned, this PR works great! Thank you for the quick work as always 🫡
