### ISSUE TITLE
Error upon not having a character name for a line of dialogue

### ISSUE THREAD

**Issue by mickeyordog** [nathanhoad/godot_dialogue_manager#512]
**Describe the bug**
I have the following .dialogue file:
```
~ dagger_get
This doesn't work without a character
```
When I run this, I get the following error:
`Invalid get index 'text' (on base: 'Nil').`
Screenshot of error and relevant lines:
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/36612632/5c2d04f3-3ffb-424c-84e7-8557cf12322f)
However, if I include a character name like so:
```
~ dagger_get
John: This doesn't work without a character
```
It now works without error. According to the documentation, having a line without a character name is valid.
**Affected version**

- Dialogue Manager version: v2.35.1
- Godot version: v4.2.1.stable.mono.official [b09f793f5]

**Comment by nathanhoad** [comment]
I'm not entirely sure why that line is where it's showing an error but I managed to replicate a possibly related issue which should be fixed in [this PR](https://github.com/nathanhoad/godot_dialogue_manager/pull/513). Let me know if this fixes your issue.

**Comment by nathanhoad** [comment]
That PR has been merged. I'm going to close this unless it comes up again.
