### ISSUE TITLE
I would like some mechanism to link lines to the speaker in translation CSV's

### ISSUE THREAD

**Issue by NatCracken** [nathanhoad/godot_dialogue_manager#518]
**Is your feature request related to a problem? Please describe.**
The game I am working on is using voice acting. In order to sync audio lines to text lines I am trying to re-use TL keys since they serve a similar purpose and have existing infrastructure. Due to having those keys and using the import/export settings, the generated CSV's seem a very useful authoritative version of the script for generating and then keeping lines in sync across the team. So I would like to to generate a more readable script from them. Stuff like removing BBCode I can post process myself, but linking lines in the CSV file back to their speaker is more difficult. And it necessary to have speaker names in these docs for them to be usable to the rest of the team

**Describe the solution you'd like**
Perfect solution; another field in the generated CSV which contains the name of the speaker for each line, but this would probably break the generated packed_translation file unless theres some way to exclude a field that I don't know about.
Imperfect solution; generate another file which links each speaker to each TLkey they speak so I can do it myself externally

**Describe alternatives you've considered**
This could be accomplished by a toolscript that reads through the file as if it were playing the game and generates a readable script using those exposed values, but this could get quite complex as it goes back to re-do other branches and I don't even know how I would detect and handle a recursive script.
I could also attempt to read the dialogue_resource file directly. Theres no downsides to this;, I'd just rather not put in the work if I can avoid it. This will probably be of use to others in the future so I may as well try proposing it as a feature before doing it myself.

**Comment by nathanhoad** [comment]
There's an option in advanced dialogue settings to include the character names in CSV exports (There was an issue when initially generating the file but that's been fixed in [this PR](https://github.com/nathanhoad/godot_dialogue_manager/pull/519)). It will throw a few errors in the Godot console because it tries to import the `_character` column as a language but you should be able to safely ignore them.
