### ISSUE TITLE
Request: Better Internationalization Features

### ISSUE THREAD

**Issue by nikecantab** [nathanhoad/godot_dialogue_manager#52]
I am bilingual and I translate my own script and also like to switch back and forth between versions a lot as I write. Oftentimes when translating into one language I end up revising the other language script a lot too. Right now this means switching between the csv file and the resource a lot and since that's a pain usually I just adjust my scripts in the spreadsheet, then copy-paste each modified line back into godot... which is also a bit of a pain.

One thing that might help is a way to import lines from the csv file if they have the same static keys. It would at least do away with the copy-pasting.

If there was a way to edit translations from within godot itself that would be a massive help but I'm not sure how that would work.

**Comment by nathanhoad** [comment]
Importing lines from a CSV with matching keys is a good idea. I'll have a look at doing that next chance I get.

**Comment by nathanhoad** [comment]
The re-importing CSV thing is in [v1.10.0](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v1.10.0)
