### ISSUE TITLE
Discernible line id generation.

### ISSUE THREAD

**Issue by Kakiroi** [nathanhoad/godot_dialogue_manager#522]
**Is your feature request related to a problem? Please describe.**
On translation software, or in excel, indentations of dialogues do not exist.
During translation, it's impossible to know whether branched dialogue is finished. 

**Describe the solution you'd like**
My first guess to this is just adding "_indentation_level" and "_branch_level" to id.
For example:
A: Blah. [ID:t3u3h_0_0]
A: Blah blah. [ID:trjid93_0_0]
- Choice one. [ID:tjf930_0_1]
   B: B choosed one. [ID:t5ji3h1_1]
- Choice two. [ID:tculfu35_0_2]
   B: B choosed two. [ID:t535j_1_2]
   A: A keeps dialogue on indentation 1, branch 2. [ID:t3ji23_1_2]

Or maybe those numbers could be human readable. I suppose it's just a key so it doesn't matter how it looks.
Important part is that they are discernible. [ID:tjw294_indentation(0)_branch(3)]
Also, this means now when generating translation keys, it shouldn't skip when it finds existing one. Needs to compare with it, and update indentation and branch number too, which will be a hassle but I don't think it will happen that often.

**Comment by Kakiroi** [comment]
Or maybe we can have more clearer line id for translators. 
I tried tweaking id generation so the id has both title and speaker. Also with indentation and choice levels.

I think it makes it much much easier for translator to work with. Although it makes code space a little bit crowded, I think it's worth it. Especially since I don't think it's possible to export any comments with POT generation(unless the plugin generate POT itself in the future?). 
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/120232084/c8921dc2-1044-46fa-93dd-79924db70bd6)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/120232084/d3f6e0f8-8840-4a7d-a2bb-b19dbfcafbe9)

**Comment by nathanhoad** [comment]
Thanks for the suggestion but I'm unlikely to add indentation guides to the translation keys. There are a few reasons for not adding it but the main one is that it can easily become outdated as dialogue is moved around and rewritten. 

I am contemplating exposing a few of the internal dialogue editor methods to allow for per-game modifications so the translation key method might be a good candidate for that - then you'll be able to implement it however makes sense to you.
