### ISSUE TITLE
Responses that return to the list of responses once finished.

### ISSUE THREAD

**Issue by FringeSci-com** [nathanhoad/godot_dialogue_manager#523]
**Is your feature request related to a problem? Please describe.**
I'm making an RPG where I commonly find myself having lists of responses that will jump you back to the list once it's been answered.
Right now you can achieve this with jumps like this:
```
- I have some lore questions.
	Wizard: What do you want to know?
 	=>< lore_questions

...

~ lore_questions
- Lore question 1
	Wizard: ...
	Wizard: Anything else?
	=> lore_questions
- Lore question 2
	Wizard: ...
	Wizard: Anything else?
	=> lore_questions
- That's all for now

```
But when I have lots of little 2-3 question lists it gets quite cumbersome, especially when nested in other lists. It breaks the flow of my dialogue files having to jump back and forth in the file to track a simple conversation.

**Describe the solution you'd like**
I propose a syntax for responses like we have for jumps, where it'll jump you back to the list of responses once it's done. This allows for little blocks of responses inline with the rest of your dialogue.
```
- I have some lore questions.
	Wizard: What do you want to know?
	-< Lore question 1
		Wizard: ...
		Wizard: Anything else?
	-< Lore question 2
		Wizard: ...
		Wizard: Anything else?
	- That's all for now
```

**Describe alternatives you've considered**
You can achieve the same effect with jumps, This is just some syntactic sugar to make dialogue files more concise and easy to follow.

**Comment by nathanhoad** [comment]
Thanks for the suggestion but I'm hesitant to add another level of complexity to the parser where the alternative is still pretty manageable (and arguably easier to read at a glance).
