### ISSUE TITLE
Preview Ideal Dialogue Length in the Editor

### ISSUE THREAD

**Issue by Paul-Griffin-1517-1** [nathanhoad/godot_dialogue_manager#526]
**Is your feature request related to a problem? Please describe.**
There's a limit to the amount of text a dialogue balloon can display without resizing the text or the balloon itself. For many games, limiting the length of the dialogue text in the dialogue editor would be a convenient way to avoid these sorts of compromises.

**Describe the solution you'd like**
Some sort of option to visualize whether a given line of dialogue has gone over a character limit (or some other equivalent metric of the length of a line).

This could be achieved by turning the excess characters red, but there are several reasons not to do it this way. For one, even within a single game various dialogue balloons may be able to handle various quantities of text. Some individual lines of dialogue may even be displayed differently (for example, one dramatic line of dialogue might be centered and in a larger font for emphasis.)

I think the least obtrusive option would be or simply putting a small guide line in the background for the writer to keep to the left of.
![dialogue1](https://github.com/nathanhoad/godot_dialogue_manager/assets/116929197/c83724a5-54f5-4b7b-b870-3c74da7d0cf1)

If multiple target lengths are needed for the project, it's as simple as adding an entry to an array of lengths and adding an additional guideline to the background. Each line could be toggled on and off as desired. Perhaps even named to help keep track of which is which.
![dialogue2](https://github.com/nathanhoad/godot_dialogue_manager/assets/116929197/c657c0f0-aece-4502-bc5c-407f0a549a16)

**Describe alternatives you've considered**
Any other solutions I've thought of risk limiting the utility or predictability of the plugin (such as turning the excess text red, or making the dialogue manager treat excess text as a new line of dialogue automatically).

**Additional context**
There are still difficulties to consider here.
- How would this work when wrapping text in the editor?
- Is a character limit even the best way to determine the amount of space text will take up? ("llllll" and "MMMMMM" are the same number of characters, for example.)
- What about screen sizes/editor zoom levels/etc.?
- Most importantly, how would this work with character names of various lengths, which are visible on a separate label and don't contribute to the overall length of the line in-game? Adjusting the position of the guideline for every line of dialogue to account for this could quickly become visual noise.

Regardless, I believe keeping track of the length of dialogue lines is a worthwhile feature to consider, even if this proposal doesn't quite solve it.

**Comment by nathanhoad** [comment]
Thanks for the suggestion but I'm not likely to add an ideal length indicator - mainly because there's no way to guarantee any meaningful accuracy.

**Comment by Paul-Griffin-1517-1** [comment]
Makes sense. Thanks for considering!
