### ISSUE TITLE
Error connecting to signal: completed during yield()

### ISSUE THREAD

**Issue by JeremyStarTM** [nathanhoad/godot_dialogue_manager#53]
**Describe the bug**
Unable to use any dialogue (custom balloon or example balloon) because of an error that Godot returns.
Error: _Error connecting to signal: completed during yield_

**To Reproduce**
1. Download the latest Godot Dialogue Manager
2. Create some dialogue
3. Try to show dialogue

**Expected behavior**
The written dialogue shows up successfully.

**Comment by nathanhoad** [comment]
I can't replicate the issue in any tests yet. Have you got a sample project you can attach that shows the error?

**Comment by JeremyStarTM** [comment]
I copied my project and made it super simple (with the scene I want it in). Make sure to read the README.txt included in the zip file.

Link: https://drive.google.com/file/d/1VlCBxEEfCl-SEcYboUVZSgAZgee5r4hw/view (couldn't upload it via GitHub)

**Comment by nathanhoad** [comment]
It looks like you've commented out a line that makes sure the `get_next_dialogue_line` can yield:

![yield](https://user-images.githubusercontent.com/78984/174430464-5a5d7a5e-389a-49c5-97db-2aa5c107ed99.jpg)

When I uncomment that it all works as expected.

**Comment by JeremyStarTM** [comment]
I uncommented that line because it threw that error:
![grafik](https://user-images.githubusercontent.com/53786253/174433486-732465fe-ec4f-44e2-b308-861a2f41f583.png)

**Comment by JeremyStarTM** [comment]
I compared the sample and my own project and it seems that the error only occurs in my project. [You can view the sourcecode here](https://staropensource.ddns.net/gitea/staropensource/jessist) (same locations, but the mentioned functions in res://Scripts/GameController.gd can be found at the bottom of the script)

**Comment by JeremyStarTM** [comment]
@nathanhoad

**Comment by nathanhoad** [comment]
It looks like you somehow have the DialogueManager running outside of the tree. In that case you can replace the `get_tree()` there with `Engine.get_main_loop()`.

I'd also look into why your frame rate is being eaten up by player physics and some of your logging:

![profiler](https://user-images.githubusercontent.com/78984/174687465-b1dcac68-b4bd-4b21-a828-d4e8c42b3c63.jpg)

**Comment by JeremyStarTM** [comment]
Thank you. The game is completely unfinished and I may rewrite parts of it. Still thank you!
