### ISSUE TITLE
Minor bug: editor prompts to save when quitting with no changes

### ISSUE THREAD

**Issue by jaronkk** [nathanhoad/godot_dialogue_manager#536]
**Describe the bug**
This is only a nuisance, but in a project with the Dialogue Manager plugin enabled the editor will always show the `(*)` change indicator in the top bar, and will prompt to save when quitting when no changes have been made.

**Affected version**

- Dialogue Manager version: Latest (847353400528251c68029113a1734e90d263ff4c)
- Godot version: Windows `v4.2.1.stable.official [b09f793f5]`

**To Reproduce**

1. Create a new project
2. Drag the addons folder from the Dialogue Manager download into the project
3. Enable the addon
4. Save and quit
5. Reopen the project
6. Attempt to quit without doing anything and it will prompt to save before quitting. I've confirmed saving doesn't actually update any files.

**Expected behavior**
The editor shouldn't think anything has changed when freshly opening the project.

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/127832/290b69ff-595d-4c9f-a1d2-2b9f25c7907e)

Thanks! This is definitely a super duper minor issue.

**Comment by nathanhoad** [comment]
I think it might be an issue with Godot itself but I've added a kind of hacky workaround for now that will just save the project a few frames after opening the project.
