### ISSUE TITLE
Godot doesn't like unknown file extensions

### ISSUE THREAD

**Issue by cube-logic** [nathanhoad/godot_dialogue_manager#540]
**Describe the bug**
For some reason godot doesn't like extensions it doesn't recognize, which includes .dialog and .txt

**Affected version**
2.37.1

- Dialogue Manager version:
- Godot version: 4.2.1

**To Reproduce**
Use your example and add a dialog.dialog file to then load it

1. List steps to see error
2. See error, etc

**Expected behavior**
To be able to select the dialog file

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/85768334/e3bf34ce-a2a2-482b-91c9-102332b3d3e6)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/85768334/825b5b10-429b-4f86-9db5-09db3bc44498)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/85768334/38809ec6-d6d7-47f7-b0c7-d41692a8f5b7)

**Comment by nathanhoad** [comment]
Dialogue Manager uses `.dialogue` files, not `.dialog` or `.txt`
