### ISSUE TITLE
Out of bounds get index crash in resolve_thing_method()

### ISSUE THREAD

**Issue by SpookyLamb** [nathanhoad/godot_dialogue_manager#541]
**Describe the bug**
When having the Dialogue Manager perform a method with a default value that is not filled in (eg. do singleton.method(property) when the method footprint is method(property, property := value)), the Dialogue Manager crashes at line 1211. Problem seems to be with this block of code:

```
		for i in range(0, method_args.size()):
			var m: Dictionary = method_args[i]
			var to_type:int = typeof(args[i])
```

The third line causes the crash. Presumably, the issue is that method_args.size() and args.size() are not always the same.

**Affected version**

- Dialogue Manager version: v2.37.1
- Godot version: v4.2.1 stable

**To Reproduce**

1. Have a singleton with a method that takes two arguments, one of which has a default value.
2. In a dialogue resource, include a do statement using that singleton and method, with only a single argument, leaving the default value as-is.
3. Trigger dialogue in-game.
4. Observe the crash.

**Expected behavior**
The Dialogue Manager to execute the method without crashing, using the given default value.

**Comment by nathanhoad** [comment]
This might already be fixed in [https://github.com/nathanhoad/godot_dialogue_manager/commit/847353400528251c68029113a1734e90d263ff4c](https://github.com/nathanhoad/godot_dialogue_manager/commit/847353400528251c68029113a1734e90d263ff4c)

**Comment by SpookyLamb** [comment]
Impressive response time! Yes, it looks like that commit fixes it, after testing it out just now. Thank you for replying so quickly!

**Comment by SpookyLamb** [comment]
Impressive response time! Yes, it looks like that commit fixes it, after testing it out just now. Thank you for replying so quickly!
