### ISSUE TITLE
Get Dialogue Editor Shortcuts from Godot Editor Shortcuts

### ISSUE THREAD

**Issue by nan0m** [nathanhoad/godot_dialogue_manager#549]
**Is your feature request related to a problem? Please describe.**
I use CTRL + 1 to comment out my code. It allows me to use my left hand to comment using my right hand to select things.
The code editor of the Plugin only uses CTRL + K it's hardcoded as a String. The same goes for some other shortcuts.

**Describe the solution you'd like**
These behaviors have a clear equivalent in the Godot Code Editor, if I set my shortcuts up in a certain way, it is highly unlikely I would want them to be different in the Dialogue Manager plugin.

**Describe alternatives you've considered**
Replacing the Strings in my code with the preferred ones, but that would mean having to make a branch of the plugin for this minor thing. For a plugin which is otherwise excellent.

**Additional context**
Love this plugin, btw.

**Comment by nathanhoad** [comment]
Godot doesn't expose those shortcuts natively but I've found a possible workaround to use until it does. Feel free to give the latest `main` a go and let me know how it goes for you.
