### ISSUE TITLE
Better conditional information for responses

### ISSUE THREAD

**Issue by jcandres** [nathanhoad/godot_dialogue_manager#55]
First: thanks for the hard work! Second: I just started using the addon so perhaps I'm missing something obvious or using it the wrong way.

**Is your feature request related to a problem? Please describe.**
The manager doesn't feel very transparent regarding responses at the moment. It seems like disallowed responses are hidden from the user.
If I understand this correctly, `DialogueLine` has an array of `DialogueResponse`, and each response has an `is_allowed` field. I'm unsure if that field works, because the manager simply discards the responses with failed conditions.

I feel like the most transparent way to handle this would be to pass all the responses to the user, allowed or not, so the user can decide what to do with them for their particular project (hide them, gray them out, etc).

**Describe the solution you'd like**
Ideally, the dialogue would output all the responses, both allowed and not.
It would also be great if `DialogueResponse `included its condition(s) as an aditional field, both failed and passed. This would allow you to parse the response and inform the player why a certain response is enabled or disabled. This is very common in interactive fiction and CRPGs, where the actions of each choice are made explicit, for example it's common to see choices like: "- Tell me about your past. (Requires relationship 5+)" or "- Pick the lock (Requires picklock)".

Hopefully this sounds reasonable. Thanks again!

**Comment by nathanhoad** [comment]
You might be looking for [this setting](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Settings.md#runtime):

![image](https://user-images.githubusercontent.com/78984/176585161-0411f651-610d-444a-a9c5-8c4ed0464abe.png)
