### ISSUE TITLE
Cant run the game after export.

### ISSUE THREAD

**Issue by Pynthare** [nathanhoad/godot_dialogue_manager#552]
**Describe the bug**
I have no problem running my game with Dialogue Manager enabled inside the editor, however, when ever I try to export the game with the plugin enabled, the game crashes, Ive tried checking logs and starting with console, reading everything I can find in the docs, earlier issues and discussions here on github for the past 3 days, but I have not found anything that even remotely could point me in the right direction. 

Nothing seems to output any errors at all, no logs or anything. The game simply crashes at the godot splash right at the beginning. 

I do not have this issue if I disable the plugin, or have other plugins running. 
This is the only one, and I just cant figure out why. 
This happens both on Android and Windows 11

The only thing Ive been able to find is that Godot MIGHT ignore files that should be included in the export, and that in turn might cause a crash I guess? But Ive gone bats**t crazy with the includes and by now it should probably even include baby dipers if they were in the same folder.
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/149574826/34026712-2a2a-4474-8081-1348ce4f0bb6)

The plugin is enabled, the autoload is there and enabled, everything works perfectly in engine. Please help? I am totaly lost at what to even try next. 

Edit*:
Ive also tried using --debug and --verbose on the exported exe to see if some kind of error appears, but nothing of the sort.

**Affected version**
- Dialogue Manager version: 2.38.0
- Godot version: 4.2.1

**To Reproduce**
I would not know, since I dont have any leads at all. I do not belive this is a general issue, probably something stupidly easy I am missing.

**Comment by BlairStewart** [comment]
Are you exporting on Linux by any chance? 

If not, what shows up if you run the `game.exe` file from the command line. Are you getting a, resource loader missing error?

**Comment by Pynthare** [comment]
I export and run the exe on a Windows 11 machine.
I do no not get any errors at all, no missing resources messages, nothing.

**Comment by Pynthare** [comment]
I do not know how or why, since I still dont have any error messages, logs or information at all. But I tried updating Godot engine from 4.2.1 to the latest 4.2.2 and for some reason the game now runs when exported. 

So with that I am closing this issue.

**Comment by ksmithdev** [comment]
I'm actually experiencing this exact issue now. I'm using the latest Godot (Godot Engine v4.2.2.stable.mono.official.15073afe3) and Windows 11, but whenever I export a project that has this plugin enabled, the program fails to run. It simply closes after loading up. 

I even tried creating a brand new project and only added this addon and enabled it and it still fails. 

Event viewer has this information:
```
Faulting application name: DialogManagerCrashTest.exe, version: 4.2.2.0, time stamp: 0x00000000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x0x2900
Faulting application start time: 0x0x1DAA548888DED22
Faulting application path: [redacted]\DialogManagerCrashTest\.exports\Windows\DialogManagerCrashTest.exe
Faulting module path: unknown
Report Id: a7e885f0-f41c-405e-87e1-ba5ad4ff5858
Faulting package full name: 
Faulting package-relative application ID: 
```

Here's the project I created:
[DialogManagerCrashTest.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/15297634/DialogManagerCrashTest.zip)
