### ISSUE TITLE
A way to capture input when the Balloon parent node is a SubViewportContainer

### ISSUE THREAD

**Issue by sysl-dev** [nathanhoad/godot_dialogue_manager#560]
**Is your feature request related to a problem? Please describe.**
Yes, when you create a balloon that has a parent of a SubViewportContainer, then you use a SubViewport to ensure all the UI is scaled pixel perfect, menu input no longer works. Since you've wrapped it in a viewport, ```self.get_viewport().set_input_as_handled()``` fails and it only will accept mouse input.

**Describe the solution you'd like**
A guide on how to work around this, or an example that works around the issue.

**Describe alternatives you've considered**
I've made my buttons look flat to ensure they *look* pixel perfect and I'm considering modifying the response creation script to use a patchnine behind the items.

I could also give up on having dynamic layers and just use int scale. But this gives mess less control. I want to be able to have a pixel world and a higher res layer (just not the textbox/choices)

**Additional context**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/13181256/cc039b94-5b98-4783-a4bd-db3557abf7c6)

**Comment by nathanhoad** [comment]
Can you provide a small project with this kind of setup and I'll have a look.

**Comment by sysl-dev** [comment]
Sure, please give me until this Sunday.

**Comment by sysl-dev** [comment]
Did some more work because I did not want to bother you with looking into this if I could work around it.

I can work around it, so this can be closed.

Thank you for responding.
