### ISSUE TITLE
Parsing Error when loading game with DialogueManager open

### ISSUE THREAD

**Issue by archschool** [nathanhoad/godot_dialogue_manager#562]
I'm making a game and I enabled dialogue manager, Loaded my game and the dialogue manager script is giving me an error/stack frame

Here are the errors
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/169214131/76ebca32-bb76-4a5c-9be5-e60d1299fb96)
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/169214131/172616ad-26a1-469d-a64f-a2f0e3daa4a5)
 HELP!!!

**Comment by nathanhoad** [comment]
It looks like your `addons` folder has a capital "A" when it should be all lowercase.
