### ISSUE TITLE
Text inside DialogueLabel doesn't updates with TranslationServer.set_locale("") if I change "Default CSV Locale"

### ISSUE THREAD

**Issue by cortrano** [nathanhoad/godot_dialogue_manager#565]
**Describe the bug**
If I change "Default CSV Locale" in Dialogue Manager settings from "en" to another locale (for example "ru"), then changing locale via TranslationServer.set_locale("") at runtime doesn' update text inside DialogueLabel node.

**Affected version**
- Dialogue Manager version: 2.39.0
- Godot version: 4.2.2

**To Reproduce**

1. Create new .dialogue file
2. Set "Default CSV Locale" to another locale
3. Select Translations -> Save lines to CSV
4. Add "en" translation to your CSV file
5. In custom dialogue baloon add _input func to switch between two locales using TranslationServer.set_locale("")

**Expected behavior**
If locale changed, I expect text inside DialogueLabel to be updated

**Comment by nathanhoad** [comment]
Have you added all of the auto-generated `.translation` files to the project (under the Localization tab in Project Settings)?

**Comment by nathanhoad** [comment]
I'll look at adding something like that to the example balloon but for now you can add this to yours and it should be fine:

```
func _notification(what: int) -> void:
	if what == NOTIFICATION_TRANSLATION_CHANGED:
		dialogue_label.dialogue_line = await resource.get_next_dialogue_line(dialogue_line.id)
```

The line needs to be fetched again to account for any variables that might need to be resolved.
