### ISSUE TITLE
Custom Balloon Paths Not Recognized

### ISSUE THREAD

**Issue by LouisC00** [nathanhoad/godot_dialogue_manager#574]
**Describe the bug**
I’m experiencing an issue with the Dialogue Manager 2.39.1 in Godot 4.2.2-stable where the runtime does not recognize custom balloon paths. Regardless of the custom path I set, whether it’s a scene path unrelated to dialogue or not, the runtime consistently defaults to the default balloon.

**Affected version**

- Dialogue Manager version: 2.39.1
- Godot version: 4.2.2-stable

**To Reproduce**

1. Create a copy of dialogue example balloon and customize it
2. Set the run time path to that balloon in dialogue manager
3. Observe that it always runs the balloon at res://addons/dialogue_manager/example_balloon/example_balloon.tscn regardless of the runtime path set.

**Expected behavior**
The Dialogue Manager should run my custom balloon as specified in the runtime path. I attempted to replace my custom dialogue at the path res://addons/dialogue_manager/example_balloon/example_balloon.tscn, which interestingly results in the runtime pointing to a different path and displaying my custom dialogue. This suggests that the paths I set are not being read properly.

**Comment by LouisC00** [comment]
1. You can see the custom balloon has a portrait, and the path is correct, but in the game, there’s no portrait:
<img width="1710" alt="Screenshot 2024-05-23 at 1 38 07 PM" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/159967757/06f2edf8-b052-4b9f-93c2-60e7ee546ac8">

2. When I use the default test scene, it should point to the default scene in the dialogue manager because I don’t have my custom test scene, but it actually tests the runtime path.
<img width="1710" alt="Screenshot 2024-05-23 at 1 33 27 PM" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/159967757/ededb5ba-6b93-460f-bbd3-117c5927854d">

I have checked the dialogue balloon in the dialogue manager; it should have no portrait:
<img width="1822" alt="Screenshot 2024-05-23 at 1 32 37 PM" src="https://github.com/nathanhoad/godot_dialogue_manager/assets/159967757/49910bef-872a-4790-aca8-b38bebfc7dc8">

**Comment by nathanhoad** [comment]
Can you show me the code you're using to start the dialogue in your game? It should be calling `DialogueManager.show_dialogue_balloon()`.

**Comment by LouisC00** [comment]
Oh. I did forget to use show_dialogue_balloon(). I use show_dialogue_example_balloon() instead.
So now the runtime is correctly showing my custom balloon.
but the test still showing the runtime path balloon.

**Comment by nathanhoad** [comment]
The "test dialogue" button will use whichever balloon is configured to be your runtime balloon (it uses `show_dialogue_balloon()` internally).

So is your game working as expected now? If so, I'll close the issue.

**Comment by LouisC00** [comment]
Yes. it's working as expected now. Thank you. Please close the issue
