### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JekSun97** [nathanhoad/godot_dialogue_manager#576]
**Describe the bug**
I cloned the repository via git and none of the scenes work fine, I don't have C#, maybe this is the problem?
There are no errors in the console

- Dialogue Manager version: 2.39.1
- Godot version: 4.2.2

**Screenshots**
![32](https://github.com/nathanhoad/godot_dialogue_manager/assets/130399274/b08a8f1e-cceb-4139-aaf9-3c68d970143f)

**Comment by nathanhoad** [comment]
It looks like you're trying to run the balloon scene instead of the test scene in `/examples/test_scenes/point_n_click_scene.tscn`.
