### ISSUE TITLE
Dialogues not getting saved

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#58]
**Describe the bug**
Basically dialogue lines are not being saved when I switch between tscn files in the dialogue editor

**To Reproduce**
I don't know if this is intended but I just noticed it, since I usually save the dialogues manually but switching without saving will cause the edited dialogues to not get saved.
my steup is as follows : I have multiple dialogue files (tscn files) lets call them home_dialogues.tscn, mia_dialogue.tscn ...ect 

1 Lets say I edit a big dialogue file , home_dialogues.tscn, weather it is modifying a line ,adding a new one  or even removing a whole title from it.
2 Generate translation keys and save csv - (Tested without doing it but same thing, so this is irrelevant)
3 Switch to another dialogue from the recently opened files (mia_dialogue.tscn)
4 Go back to the first file (home_dialogues.tscn)
5 The dialogue is reset to what it was before modifying it.

I think this bug happened to me once a while ago and I got confused and convinced myself that I didn't actually modify the dialogue and maybe I just imagined it, But now that the dialogue file is kinda big, I can replicate it easily. 

Notes : 
- This bug wont happen if before switching to another file, you save the project with ctrl+s.

**Expected behavior**
The changes to be saved

**Comment by nathanhoad** [comment]
The size of the file shouldn't affect the ability to save, just the time it takes to save.

Turns out I simply wasn't saving the previous file when changing resources. I think I never really ran into it before because I was always running the scene when making changes so it would save at that point.

**Comment by RedXGames** [comment]
Yeah, I usually save manually everytime I edit dialogues just as a habit but I found myself having to switch between dialogue files 
 as the project grows and just noticed it
Thanks for fixing it
