### ISSUE TITLE
Visual node graph editor for writing dialogues

### ISSUE THREAD

**Issue by nan0m** [nathanhoad/godot_dialogue_manager#580]
**Is your feature request related to a problem? Please describe.**
It's difficult to follow the flow of conversation in a linear text based file at times.

**Describe the solution you'd like**
Visual Node editor e.g. like yarn spinner or other tools

**Describe alternatives you've considered**
nothing

**Additional context**
It's probably a big discussion, not sure if it is even possible or desired. There would have to be a way to convert the dialogue text files to a graph node representation and vice versa.
example from yarnspinner web editor: 
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/74869542/dba1e8b1-110d-4c34-8f02-4e1d7a97025e)

link to yarnspinner web editor: https://blurymind.github.io/YarnClassic/

**Comment by nathanhoad** [comment]
The reason I made Dialogue Manager in the first place was that I didn't want to use a graph editor to write dialogue. Also, the nature of `title` lines means there's no such thing as a "block" like what you have in YarnSpinner, Ink, and the like.
