### ISSUE TITLE
Unable to use editor in 4.3-beta1

### ISSUE THREAD

**Issue by SylvestreMassalaz** [nathanhoad/godot_dialogue_manager#584]
**Describe the bug**

Importing the plugin in godot 4.3 doesn't seems to work. The eidtor tab does not seems to be working

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/5619464/c7535fd8-3b8a-4ae4-806b-fb927c5eb847)

Multiple errors are shown in output 

```
  res://addons/dialogue_manager/components/code_edit.gd:279 - Parse Error: The function signature doesn't match the parent. Parent signature is "insert_text(String, int, int, bool = <default>, bool = <default>) -> void".
  modules/gdscript/gdscript.cpp:2943 - Failed to load script "res://addons/dialogue_manager/components/code_edit.gd" with error "Parse error". (User)
Add Autoload
  res://addons/dialogue_manager/views/main_view.gd:357 - Invalid assignment of property or key 'theme_overrides' with value of type 'Dictionary' on a base object of type 'CodeEdit (code_edit.gd)'.
  res://addons/dialogue_manager/views/main_view.gd:151 - Invalid assignment of property or key 'main_view' with value of type 'Control (main_view.gd)' on a base object of type 'CodeEdit (code_edit.gd)'.
  res://addons/dialogue_manager/views/main_view.gd:961 - Invalid call. Nonexistent function 'get_cursor' in base 'CodeEdit (code_edit.gd)'.
[LSP] Connection Taken
  Failed parse script res://addons/dialogue_manager/components/code_edit.gd
  The function signature doesn't match the parent. Parent signature is "insert_text(String, int, int, bool = <default>, bool = <default>) -> void".
```

**Affected version**

- Dialogue Manager version: 2.39.1
- Godot version: 4.3-beta1 (gdscript only)

**To Reproduce**

- Create a new project in godot 4.3.
- Add the addon from the asset store.

**Expected behavior**

The editor should be working, no erroers should be shown in the output part of the interface.

**Screenshots**
If applicable, add screenshots to help explain your problem. Try to include as much detail as possible.

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/5619464/c7535fd8-3b8a-4ae4-806b-fb927c5eb847)

![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/5619464/55966d79-f10f-42e5-aebc-1bef770239b4)

**Comment by D0vid** [comment]
FYI: renaming `insert_text(text: String)` in code_edit.gd (and its usages in main_view.gd) to `insert_some_text(text: String)` (or to anything else basically) seems to fix the problem as a workaround

It seems like they added an `insert_text()` method to TextEdit Node in Godot 4.3

Tested on 4.3beta1.mono version

**Comment by nathanhoad** [comment]
This was already fixed in https://github.com/nathanhoad/godot_dialogue_manager/pull/583 but hasn't been released yet.
