### ISSUE TITLE
NOTIFICATION_TRANSLATION_CHANGED triggered before start() and _ready()

### ISSUE THREAD

**Issue by ProFiLeR4100** [nathanhoad/godot_dialogue_manager#589]
**Describe the bug**
Not sure if it is related to beta godot version or something else, but when I try to call `DialogueManager.ShowExampleDialogueBalloon` then NOTIFICATION_TRANSLATION_CHANGED is being triggered start() and _ready(), which causes two errors: 
- DialogueLabel is not set to the variable because _notification() being called before _ready()
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/9364958/518e4573-8d5d-4470-9aa9-4dae4251ffb3)
- resource is missing because is is called before start()
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/9364958/9b5e59e7-8d9b-4c60-9a5f-27ec07f7a60c)

So basically this is new order of execution: _notification -> _ready -> start.

**Affected version**

- Dialogue Manager version: v2.39.1 (latest)
- Godot version: v4.3.beta1.mono.official [a4f2ea91a]

**To Reproduce**
- Install 4.3-beta1 release from [preview builds download page](https://godotengine.org/download/preview/)
- Create project
- Install and enable latest Godot Dialogue Manager addon
- Apply patch from https://github.com/nathanhoad/godot_dialogue_manager/issues/588
- Create script to show example baloon.
```cs
using DialogueManagerRuntime;
using Godot;

public partial class Test : Node2D {
    [Export]
    public Resource DialogueResource;
    
    public override void _Ready() {
        DialogueManager.ShowExampleDialogueBalloon(
            DialogueResource,
            "this_is_a_node_title"
        );
    }
}
```
- Run scene

Or you can just download attached project with everything patched and then just run it:
[order-of-execution-issue.zip](https://github.com/user-attachments/files/15752507/order-of-execution-issue.zip)

**Expected behavior**
I even don't know what is the expected order of execution, probably this is defect of Godot 4.3-beta1 and not this repo at all.

**Workaround (patch)**

```
Index: addons/dialogue_manager/example_balloon/example_balloon.gd
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/addons/dialogue_manager/example_balloon/example_balloon.gd b/addons/dialogue_manager/example_balloon/example_balloon.gd
--- a/addons/dialogue_manager/example_balloon/example_balloon.gd	(revision 87fcb7a1109bcfedf7fc4e4afc9ffaf34ac2b0f3)
+++ b/addons/dialogue_manager/example_balloon/example_balloon.gd	(date 1717934143315)
@@ -92,6 +92,14 @@
 func _notification(what: int) -> void:
 	# Detect a change of locale and update the current dialogue line to show the new language
 	if what == NOTIFICATION_TRANSLATION_CHANGED:
+		# If the node isn't ready yet then none of the labels will be ready yet either
+		if not is_node_ready():
+			await ready
+		
+		# If there is no resource file set then there is no way to get dialogue line from it
+		if not resource:
+			return
+		
 		var visible_ratio = dialogue_label.visible_ratio
 		self.dialogue_line = await resource.get_next_dialogue_line(dialogue_line.id)
 		if visible_ratio < 1:
```

**Comment by ProFiLeR4100** [comment]
Looks like this is related to [this Godot issue](https://github.com/godotengine/godot/issues/89804)

**Comment by nathanhoad** [comment]
A workaround is already in the [updated example balloon](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/addons/dialogue_manager/example_balloon/example_balloon.gd#L94).
