### ISSUE TITLE
Cannont call 'has_method' on null value.

### ISSUE THREAD

**Issue by lukehayes** [nathanhoad/godot_dialogue_manager#590]
This is my first try with the plugin so may well be me and not a bug!

**Describe the bug**
I copied the example balloon into my project and renamed it. I have a test scene to see how I can trigger the dialogue manager from code and I get this error.

**Affected version**

- Dialogue Manager version: 2.39.1
- Godot version: Godot Engine v4.2.2.stable.arch_linux 

**To Reproduce**

I'm not entirely sure, but all I am doing is trying to call the dialogue manager from GDScript.

Here is all the code:

```
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	var res = preload("res://dialogs/test-dialog.dialogue")
	DialogueManager.show_dialogue_balloon(res, "this_is_a_node_title")
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

```

**Expected behavior**
The scene to run and the dialogue to show.

**Screenshots**
![Screenshot_2024-06-10_18-26-59](https://github.com/nathanhoad/godot_dialogue_manager/assets/3280616/5a762f68-96c4-4aac-8000-e188c402ec63)

**Comment by nathanhoad** [comment]
Did you manually copy the balloon or use the **Project > Tools > Create copy of dialogue example balloon** option?

**Comment by lukehayes** [comment]
> Did you manually copy the balloon or use the **Project > Tools > Create copy of dialogue example balloon** option?

No, I used the 'copy' from the drop down when you right click the scene. I will try this  method and see what happens :+1:

**Comment by lukehayes** [comment]
Yes, that was what the problem was :man_facepalming: . Thank you for the help, and this great plugin!

I will close this issue now :+1:
