### ISSUE TITLE
Undo action in dialogue editor is not working

### ISSUE THREAD

**Issue by pavelperc** [nathanhoad/godot_dialogue_manager#592]
**Describe the bug**
Undo action in dialogue editor is not working.

**Affected version**

- Dialogue Manager version: 2.39.1
- Godot version: 4.2.2
- MacOS

**To Reproduce**
1. Open dialogue editor.
2. Edit dialogue.
3. Press Cmd+Z

**Expected behaviour**
Last text will be deleted.

**Actual behaviour**
Undoing steps from latest opened scene.

**Comment by pavelperc** [comment]
Sorry. Seems like it was fixed when I saved the dialogue, but this is strange anyway.

**Comment by nathanhoad** [comment]
The undo functionality is something provided by Godot and not something in Dialogue Manager itself.
