### ISSUE TITLE
Cant call dialogue by code

### ISSUE THREAD

**Issue by MICHIFUBRUNO** [nathanhoad/godot_dialogue_manager#595]
**Describe the bug**
It say: the key "start" was not found

**Affected version**

- Dialogue Manager version: 2.39.1
- Godot version: 4.2.1

**To Reproduce**

1. call the dialogue in any way through the "Start" key

**Expected behavior**
that can execute the dialogue

**Screenshots**
![Captura de pantalla 2024-06-15 204847](https://github.com/nathanhoad/godot_dialogue_manager/assets/172941081/8a6899bb-c9b9-4985-aff4-785266318ac0)

**Comment by nathanhoad** [comment]
Is there a chance you're trying to call "start" but your title is actually "Start" with a capital?

**Comment by MICHIFUBRUNO** [comment]
I call using "start"

**Comment by nathanhoad** [comment]
What does your dialogue file look like?

**Comment by MICHIFUBRUNO** [comment]
![Captura de pantalla 2024-06-17 122537](https://github.com/nathanhoad/godot_dialogue_manager/assets/172941081/d647e8ed-b2ec-48d6-a67f-de686415c04a)


it looks like this

**Comment by MICHIFUBRUNO** [comment]
I've solved the problem, I had to put the title of the dialog where it says "start". thanks for the help! (and I hope bravest coconut does well)
