### ISSUE TITLE
Godot 4.3-beta1

### ISSUE THREAD

**Issue by AmyGilhespy** [nathanhoad/godot_dialogue_manager#596]
**Describe the bug**
This asset doesn't seem to work in Godot 4.3-beta1.  It spews several errors when you try to open the dialog editor.

**Affected version**

- Dialogue Manager version: v2.39.1
- Godot version: 4.3-beta1-mono

**To Reproduce**

1. Import and enable the asset
2. See error

**Screenshots**
![image](https://github.com/nathanhoad/godot_dialogue_manager/assets/120238507/19b1aa41-150f-4443-95af-9dafe12ec332)

**Comment by AmyGilhespy** [comment]
As a very temporary workaround, commenting out two parts of the code in code_edit.gd allows use of the asset.

[code_edit.gd.txt](https://github.com/user-attachments/files/15860093/code_edit.gd.txt)

**Comment by nathanhoad** [comment]
This was fixed back in https://github.com/nathanhoad/godot_dialogue_manager/pull/583 - there just hasn't been a release yet.

**Comment by AmyGilhespy** [comment]
Oh, sorry for not seeing that.  Thanks, and great work as always :)
