### ISSUE TITLE
Any plans on porting the addon to Godot 4?

### ISSUE THREAD

**Issue by GersonFeDutra** [nathanhoad/godot_dialogue_manager#6]
I love the idea of your 'Say What' plug-in. To parse a simple dialog script that treats the data and events almost automagically is mindblowing. This mixed with something like dialogic (a dialog-box theme editor) could make frameworks like Ren'Py outdated and deprecated. :P

Anw, praises aside. As soon as I got my hands on the plugin, decided to translate it to Godot 4 alpha. Availlable [here](https://github.com/GersonFeDutra/godot_dialogue_manager/tree/godot4).  It's somewhat functional ─ I may test it later to catch unreached bugs.

If you wish to post it already into Godot 4 AssetsLib, go ahead! I would love to contribute. :3

**Comment by nathanhoad** [comment]
That's awesome 👍 

I have my own port for Godot 4 in the works (with a few new features that are only now possible with G4). I'm making a video about the kinds of things that are different in 4 when porting over so I'll push up the changes as an alpha branch when the video goes out.

**Comment by lentsius-bark** [comment]
This is exciting stuff, looking forward to it!

**Comment by wayrboy** [comment]
i like this

**Comment by Cannon-S** [comment]
So glad someone has already raised this question! Stoked for the Godot 4 release :D

**Comment by nathanhoad** [comment]
I mentioned this in the Discord a little while ago but I'll put it here too: the current plan is now to make Dialogue Manager 2.0 a Godot 4 thing, which I'll start releasing once we get a G4 beta and I've had more of a chance to work through some of the GDM breaking changes I want to make.

**Comment by nathanhoad** [comment]
From version 2 onwards, Dialogue Manager is now for Godot 4.
