### ISSUE TITLE
Selecting which negative options to show

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#60]
**Is your feature request related to a problem? Please describe.**
The ability to show the negative options as disabled/grayed out buttons is really nice but I don't think all conditional options should either be visible or not, Perhaps we can choose which options to be shown instead 

**Describe the solution you'd like**
My solution is as simple as adding an extra tag, for example [show]/[hide] after the [if] tag
So maybe we can add an option in the settings to choose weather the options that haven't met their conditions should be visible or hidden  by default.
and then we use the [show] tag to make them visible if the options are hidden by default or the [hide] tag to hide an option  if the options are visible by default 

**Additional context**
This feature is really great but I found myself unable to use it because of having a lot of conditional options that wont make sense for the player to see at a certain point of the game, but for the options that are related to a player stat having to be a certain amount it would be a good way to let the player know why he can't choose that option

**Comment by nathanhoad** [comment]
This is already possible if you implement that check in your balloon. For example if you had something like:

```
Nathan: Here are some options!
- First [show] [if something]
- Second [if something_else]
```

Then you could have some code in your balloon that looks in response prompts for `[show]`, removes it, and then does something based on that information.

I feel like it's a bit too niche to add as a general option to the Dialogue Manager though.
