### ISSUE TITLE
Hello! I wanted to request (Input.mouse_mode) To be a toggle for settings.

### ISSUE THREAD

**Issue by TheRealFame** [nathanhoad/godot_dialogue_manager#612]
**Is your feature request related to a problem? Please describe.**
So! In my 3d game, I have to capture the mouse of the player, If not. It allows the player to accidentally have the cursor go out the play area, And cause the game to get sent to the background. Butttt!

**Describe the solution you'd like**
If i add the toggle, For mainly any/every node that needs it. (My setting's and main menu is set this way.) To start/stop capturing the mouse, I can make the player be able to select options or return to a playable state of the game without putting it in the background!

**Describe alternatives you've considered**
Making a push request with this feature forced, (This would be hard. I don't know all of the code put into making dialogue instances run, And i don't wanna break stuff and have to use version control to fix it once more.)

**Additional context**
(This would of been where i put an image of my player in game, With the mouse focused. And then a screenshot with it unfocused when dialogue occurs, But. Sadly since i haven't figured anything out, This is just the theme you set your github to~)

**Comment by TheRealFame** [comment]
Making multiple comments in one issue now. Is it possible to use code in the dialogue itself in general? I'm looking around for examples of it being done, As I wanted to switch a variable on my player to false (The variable toggles his ability to move.)

**Comment by nathanhoad** [comment]
Modifying how the mouse is handled isn't something that belongs in the Dialogue Manager core - it's something you would implement in your custom balloon.

Affecting code values is something you'd do with [mutations](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md#mutations).

**Comment by TheRealFame** [comment]
> Modifying how the mouse is handled isn't something that belongs in the Dialogue Manager core - it's something you would implement in your custom balloon.
> 
> Affecting code values is something you'd do with [mutations](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md#mutations).

Can i just call a func from a script in the dialogue manager? The documentation really say's nothing about it...

![image](https://github.com/user-attachments/assets/b1002bee-f571-4b92-9816-67eb30f48fd8)
![image](https://github.com/user-attachments/assets/85151558-7d16-4e8d-9768-0bf572871d1d)
