### ISSUE TITLE
Dialogue balloon panel rendering scene (or sprites) inside itself

### ISSUE THREAD

**Issue by mihailides** [nathanhoad/godot_dialogue_manager#628]
**Describe the bug**
The dialogue balloon is rendering a sprite that I have inside the same scene. (I can see the sprite in the background, and once the balloon appears, it renders inside of that as well). Debug printing inside of the sprite seems that it only loads once.

**Affected version**
- Dialogue Manager version:
v2.41.3
- Godot version:
4.2

**To Reproduce**

(Basically straight out of the tutorial)
1. Create a scene with a Node2D
2. Attach one child - a Sprite2D and add a resource
3. Add a script to the root node, the sprite, or to another node2d as a child
4. Create the balloon programmatically inside _unhandled_input (e.g. DialogueManager.show_dialogue_balloon(dialogue_resource, "start")
5. Add a custom balloon via project -> tools -> create copy of dialogue example balloon..
5. Click on Balloon.tscn -> Balloon control node -> open the theme 
6. In the default preview, change type to panel and select the StyleBoxFlat theme
7. Reduce opacity
8. Run and notice sprite has rendered into the panel

**Expected behavior**
Not to have a sprite rendered inside the panel, not sure if I've missed some kind of vital step but I made a whole project from scratch with just these steps to check and had the same issue. It does this with all sprites I add to the scene.

**Screenshots**
![image](https://github.com/user-attachments/assets/59a23e35-a3ff-4e9b-9e45-f66e0570aa26)
![image](https://github.com/user-attachments/assets/1d7136ae-0135-49f2-9d76-1cf1eecf7dff)

**Comment by Selenyhr** [comment]
I've had the same thing with the Vulkan mobile renderer due to [this Godot bug](https://github.com/godotengine/godot/issues/75956).

Since the `Panel` for the example balloon is also using `Clip + Draw`, it will trigger this behavior for Godot 4. This seems to have been resolved for Godot 4.3. Meanwhile, changing the renderer to Forward+ solves the issue for current 4.X :)

**Comment by nathanhoad** [comment]
Closing this as it's not technically a bug in Dialogue Manager itself.

**Comment by mihailides** [comment]
> I've had the same thing with the Vulkan mobile renderer due to [this Godot bug](https://github.com/godotengine/godot/issues/75956).
> 
> Since the `Panel` for the example balloon is also using `Clip + Draw`, it will trigger this behavior for Godot 4. This seems to have been resolved for Godot 4.3. Meanwhile, changing the renderer to Forward+ solves the issue for current 4.X :)

Thankyou for this, you're amazing!
