### ISSUE TITLE
Mutations broken after update (from 1.9)

### ISSUE THREAD

**Issue by ErikW54** [nathanhoad/godot_dialogue_manager#63]
**Describe the bug**
I get an error when running an old, simple, dialogue with mutations. The previous version I used was 1.9
"First argument of yield() not type of object"

Error is on line 93 of dialogue_manager:
		yield(mutate(dialogue.mutation), "completed")

My guess is that mutate should be returning a dialogue_line object

**Comment by nathanhoad** [comment]
It looks like you might have an old compiler result. If you open the dialogue resource in the editor it will recompile and it should be fine after that.

**Comment by weakman54** [comment]
For anyone else running into similar problems, however rare that might be: The above wasn't enough to recompile, I tried some different things, including restarting godot etc. but what I think did it in the end was adding something to the dialogue and resaving it
