### ISSUE TITLE
Memory leak every time a "do" action is performed

### ISSUE THREAD

**Issue by Pesquisador-Stefano** [nathanhoad/godot_dialogue_manager#642]
**Describe the bug**
Everytime a dialogue uses the "do" keyword it seems an node is removed(probably because of a remove_child function) from the tree an it creates and orphan node that can't be deleted and turn into memory leak, idk if it accumulates over time but i feel/see the framerate dropping after some 2/3 hours, this may be because my machine is slower than a fridge but it's still a bug worth reporting

**Affected version**

- Dialogue Manager version: v2.41.3
- Godot version:v 4.3.rc2.official [3978628c6] and v4.2.2.stable.official [15073afe3]

**To Reproduce**
1. Open the Minimal reproduction project (MRP)
2. Run the game and don't click anything
3. Go to the Debug tab on the Godot Editor
4. Go to the Monitor tab on the Debug tab
5. Scroll till you find the orphan nodes parameter
6. Go back to the game and move the window so you can see both the game and the orphan nodes count
7. Click once on the game and watch the orphan node counter go up once

**Minimal reproduction project (MRP)**

[dialogue-manager-memory-leak.zip](https://github.com/user-attachments/files/16568319/dialogue-manager-memory-leak.zip)

**Expected behavior**
To not increase the orphan nodes counter 
**Screenshots**
![image](https://github.com/user-attachments/assets/6b1a8eaf-2b2f-4be4-b137-031c9e8166d8)

**Comment by Fireye04** [comment]
Printing out the orphaned nodes with `Node.print_orphan_nodes()` at runtime gives me the following results after running the convo a few times

`teste
teste
34628175129 - Stray Node:  (Type: Node)
teste
48133833992 - Stray Node:  (Type: Node)
34628175129 - Stray Node:  (Type: Node)`

Hopefully the node type can help narrow down the possibilities for what might be causing the problem.

**Comment by Fireye04** [comment]
Found the issue! `constants.gd` line ~180. Submitting a PR shortly.
