### ISSUE TITLE
I can't get mutation line using get_next_dialogue_line() method

### ISSUE THREAD

**Issue by cortrano** [nathanhoad/godot_dialogue_manager#651]
**Describe the bug**
I'm trying to find out if there is a do something() method after my dialog line. The something() method is in the DialogueScreen node. When I try to check if there is a mutation using get_next_dialogue_line() I get the error "Assertion failed: Method "something" not found. States with directly referenceable properties/methods/signals include "TestScene". Autoloads need to be referenced by their name to use their properties." Although the something() method itself works fine.

**Affected version**

- Dialogue Manager version: 2.41.4
- Godot version: 4.3

**To Reproduce**
1) Create method something() in DialogueScreen node (that contains all balloon logic including responses and DialogueLabel node)
2) Call that method in dialogue resource file after some line (let's say after line 5)
3) Try to check if there is mutation line "do something()" after line 5 using get_next_dialogue_line(dialogue_line.next_id) method

**Comment by nathanhoad** [comment]
Can you attach a tiny project that demonstrates the issue?

**Comment by cortrano** [comment]
Here is project. If you comment 151 line in balloon.gd and run dialogue.dialogue it will work fine and something() func on line 160 will also work. But if you uncomment 151 line and run dialogue again you will get error "Assertion failed: Method "something" not found. States with directly referenceable properties/methods/signals include "TestScene"

[tinyproject.zip](https://github.com/user-attachments/files/16644838/tinyproject.zip)

**Comment by cortrano** [comment]
Alright, after adding temporary_game_states to get_next_dialogue_line, the error does indeed disappear. However, in the resulting DialogueLine, we immediately land on the fifth line. This can still be reproduced in the tiny project I sent earlier.

line 3: Nathan: [[Hi|Hello|Howdy]], this is some dialogue. 
(Here I check if there is any mutation on the next line using resource.get_next_dialogue_line(dialogue_line.next_id, temporary_game_states)) 
line 4: do something() 
line 5: Nathan: Here are some choices. 
(For some reason, get_next_dialogue_line returns this line, skipping the one with the mutation.)
