### ISSUE TITLE
Conditional randomised lines

### ISSUE THREAD

**Issue by AbeVos** [nathanhoad/godot_dialogue_manager#659]
**Is your feature request related to a problem? Please describe.**
I'm working on a project where I use the dialogue manager to describe in-game events.
These events rely heavily on branching based on character skills and random chance.
Individually these two aspects are no problem, but the combination of the two is where I get stuck.

Basically, what I'd like is to have a list of randomised lines (with the `%` syntax) where some outcomes are en- or disabled based on the value of some variable.

**Describe the solution you'd like**
Based on the documentation, the first thing I tried intuitively was the following:

```
% => outcome_1
% => [if SomeGlobal.condition_a == true] outcome_2
% => [if SomeGlobal.condition_b == true] outcome_3
```

In this scenario, outcome_1 is always available.
On the other hand, outcomes 2 and 3 are available depending on some condition.
This means that based on which conditions are true, the outcome probabilities change; if `condition_a` and `condition_b` are both false, outcome 1 has 100% probability to be selected.
When only one of the conditions is true, outcome 1 and either outcome 2 or 3 both have a 50% chance of being selected, etc.

Alternatively, the 

**Describe alternatives you've considered**
I tried three alternative approaches.
The first was to wrap the random outcomes in if-statements, e.g.:

```
% => outcome_1
if SomeGlobal.condition_a == true
    % => outcome_2
if SomeGlobal.condition_b == true
    % => outcome_3
```

However this seems to make the manager think these are three different lists of random outcomes.

Secondly, I tried to put the condition after the title to which the outcome jumps:

```
% => outcome_1
% => outcome_2

~ outcome_2
if SomeGlobal.condition_a == false
    # Return to the random outcomes in some way...
    <
This is the content of outcome_2.
```

I'm sure this could be accomplished through some weird setup of titles, but I feel things start to look like spaghetti very quickly this way.
Moreover, if this approach would work, it could be very inefficient when you repeatedly get sent down a path that sends you back up and getting sent down the same path again.
This would be especially problematic for conditions that rely on computationally expensive function calls.

Next, just to be exhaustive, I tried to set the weights of the randomized outcomes by the value of a property:

```
%1 => outcome_1
%SomeGlobal.some_property => outcome_2
```

But the parser does not seem to even recognize this as a randomized line.

**Additional context**
For now I will try a workaround; I can probably try to do the random sampling of conditional outcomes by calling a global function and returning an outcome index to select a path in the dialogue:

```
do SomeGlobal.select_random_outcome([true, SomeGlobal.condition_a==true, SomeGlobal.condition_b==true])

if SomeGlobal.selected_outcome == 0
    => outcome_1
elif SomeGlobal.selected_outcome == 1
    => outcome_2
elif SomeGlobal.selected_outcome == 2
    => outcome_3
```

However, I do feel the suggested solution would look a lot cleaner.

Finally, I'd like to mention that I love using this plugin, so thank you very much for the work you put in!

**Comment by nathanhoad** [comment]
I've added support for conditional randomised lines in #665 if you wanted to give it a go before I merge it into `main`.
