### ISSUE TITLE
Parser Error: The method "join" isn't declared on base "String"

### ISSUE THREAD

**Issue by godofgrunts** [nathanhoad/godot_dialogue_manager#66]
**Describe the bug**
Just running an empty scene causes this error.

**To Reproduce**

1. Download godot_dialogue_manager-1.13.1.zip from releases
2. Make a new project
3. Extract the addon folder to the root of the new project.
4. Enable the addon
5. Create a new node called "Node"
6. Save scene as "Node.tscn"
7. Run scene

**Expected behavior**
The addon not to throw an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/338843/180665489-9ce813e6-a732-43f9-aff0-fab4f1c8001a.png)

**Comment by nathanhoad** [comment]
Looks like `String.join` is a new thing in Godot 3.5 - I'll change it so it works in Godot 3.4 too.
