### ISSUE TITLE
Responses don't always show up

### ISSUE THREAD

**Issue by gatomesa** [nathanhoad/godot_dialogue_manager#675]
**Describe the bug**
If two responses are in different levels of indentation, only the first response will appear, even though both should appear.

**Affected version**
- Dialogue Manager version: 2.42.2
- Godot version: 4.3.stable

**To Reproduce**
1. Create a dialogue like the following:
```
~ start
- How's it going?
if Flags.found_item:
	- I found this.
=> END
```
The checked variable belongs to a `Flags` global, and is `true`.
2. Run the dialogue.
3. Only the first response will appear. When you select it, the second response will appear.

**Expected behavior**
Both responses appear.

**Comment by nathanhoad** [comment]
That's not how conditions on responses work. If you want to have a condition on a response the syntax is:

```
Character: Here are some responses:
- This one has no conditions
- This one has a condition [if Flags.found_item]
```
