### ISSUE TITLE
Example Balloon not disappearing when it reaches =>END!

### ISSUE THREAD

**Issue by RiddleMajor** [nathanhoad/godot_dialogue_manager#678]
Example Balloon sometimes stays on screen when I clicked a choice that leads to and =>END and it's very annyoing.

**Comment by nathanhoad** [comment]
Can you provide a tiny project that demonstrates the issue?

**Comment by nathanhoad** [comment]
I'm going to close this until someone can replicate it or a sample project is attached.

**Comment by RiddleMajor** [comment]
Oh sorry, I completely forgot about this. I'm not going to be at my computer for a while, but I can send an example project soon.
