### ISSUE TITLE
Dialogue parser thinks color codes are comments (Visual Only)

### ISSUE THREAD

**Issue by godofgrunts** [nathanhoad/godot_dialogue_manager#68]
**Describe the bug**
When using `[color]` codes with a hex value, the Dialogue parser thinks the rest of the line is a comment.

**To Reproduce**
1. Create a Dialogue line with a hexcode color bbcode like so: `[color=#ed81d2]Lana: [color=#ed81d2] How are you?`

**Expected behavior**
The Dialogue parser would understand that this isn't a comment.

**Screenshots**
![image](https://user-images.githubusercontent.com/338843/181286855-645c9308-83e7-479c-860a-10f5b68b6864.png)

This is very low priority, everything runs fine, it just looks strange.

**Comment by nathanhoad** [comment]
Unfortunately I don't have a huge amount of control over how the highlighter works. Things are better in Godot 4 so hopefully I can fix it then.

**Comment by nathanhoad** [comment]
While Godot 4 does add more control over a few highlighting things it doesn't seem to add as much control as I'd like. I'll close this issue for now but reopen it if Godot eventually adds enough highlighting options to make this more possible.
