### ISSUE TITLE
Support for sub-options within the possible responses to a dialogue

### ISSUE THREAD

**Issue by anaelhoffmann2009** [nathanhoad/godot_dialogue_manager#682]
My idea is the following:
When you write a dialogue with options, within those options there should be sub-options, for example:
`
- Yes
	Aida: Can you give me food? I'm so hungry!
	- Yes
		Aida: Thank you so much!
	- Later
		Aida: Ok, but try to do it soon, I'm starving!
	- No, it's the only thing I have to eat right now
		Aida: If you really love me, you would give me your food...
`
I could colaborate with this idea if you feel like it :)

**Comment by nathanhoad** [comment]
That's already possible.
