### ISSUE TITLE
"=> END" Not working inside If statements

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#69]
**Describe the bug**
Trying to end a dialogue with a condition doens'nt work, It took me a while to upgrade to the last version (1.13.4) because I have to rewrite some codes everytime I update the plugin, but when I did it today I noticed that the => END statement doens't work as it used to in Version 1.11 

Here is an example : 
```
~ some_title 
do start_animation("Scene2")
if replay_mode
	=> END
mc : That was scary....
=> END 
```

**Expected behavior**
The dialogue Ends if the replay mode is on 

Notes : 
"Continue Though title after block" is disabled but even if it is active, the dialogue wont exit in replay mode

**Comment by nathanhoad** [comment]
What kinds of changes do you have to make with each update?

**Comment by RedXGames** [comment]
The main ones are : 
1 - Showing certain responses grayed out when their condition is negative but not all of them, So I can't use the option in the settings instead I'm using the command [show] to do that and I make a  new regex for it when I update
2 - I used to keep an ID for the current running dialogue that gets passed in the show_dialog and get_next_dialogue_line functions to deal with some issues when I load the game and have to resume the dialogue  from the last line before saving , I did that because sometimes when you save the game while a mutation is running and you load a new game while the mutation hasn't yielded yet, the new loaded dialogue will crash with the previous one, So I used the unique ID to make sure the dialogue is valid before running it.
However I noticed that this issue is fixed now with the latest version.
3-There are also some other small stuff but they are mainly related to the type of the game I'm making and won't make sense to be included in the plugin itself

Also finally, and this took me a while to realize, Jumping from version 1.11 to 1.12 was frustrating because none of my functions would execute, It turned out it was because in version 1.11 I was baking the dialogue resource so the mutations data was from version 1.11 but when I try to execute them in version 1.12 they wouldn't match the requirements since they don't have the "mutation" object that was added in that version. This took me a while to figure out but all I had to do was disable baking the resource and enable it with the new version. But doing this would cause the game to fail to run any dialogue that was saved with the previous versions as their IDs would be different and sometimes don't exist at all.

**Comment by nathanhoad** [comment]
1. and 2. can probably be moved into your balloon implementation so that you wouldn't have to modify the Dialogue Manager itself each time.

3. might be fixed in one of the recent updates. I noticed Godot was ignoring translations in a CSV file if there was an empty line after the title line.

And 5. will disappear with one of the changes coming in the Godot 4 / GDM 2 update (not sure of the specific timeline on that though)

**Comment by RedXGames** [comment]
> * 
> *
Responses can't be moved into the balloon because the negative responses are not added to the list of responses in the balloon if the "Include responses with failed condition" is off.  
So after creating the regex and adding the show data, I also add it in the dialogue_manager.gd like so by adding " or data.get('show') " : 
```
if settings.get_runtime_value("include_all_responses", false) or data.get("condition") == null or check(data.get("condition")) or data.get('show'):
			var response = DialogueResponse.new(data, auto_translate)
			response.next_id += id_trail
			response.character = get_with_replacements(response.character, response.character_replacements)
			response.prompt = get_with_replacements(response.prompt, response.replacements)
			response.is_allowed = data.get("condition") == null or check(data.get("condition"))
			# Add as a child so that it gets cleaned up automatically
			_trash.add_child(response)
			responses.append(response)
```

If there is another way I can do it through the balloon itself please let me know because it will save me some time.

**Comment by nathanhoad** [comment]
I'll update the example balloons repo with an example for something like this when I get a chance.
