### ISSUE TITLE
Can't load .dialogue files in @export fields inside my resources using quick load

### ISSUE THREAD

**Issue by cortrano** [nathanhoad/godot_dialogue_manager#696]
**Is your feature request related to a problem? Please describe.**
Can't load .dialogue files in @export fields inside my resources using quick load

**Describe the solution you'd like**
Use .tres file extension for dialogues instead of .dialogue

**Describe alternatives you've considered**
Idk if godot provides any tools for adding custom file extensions in quick load, but that would be very useful, because now I have to manually specify the path to .dialogue files every time

**Comment by nathanhoad** [comment]
Can you upload a tiny project that demonstrates the issue? As far as I can tell `.dialogue` files work with `@export` variables set to type `DialogueResource`.

**Comment by nathanhoad** [comment]
I'm closing this until more information can be added.
