### ISSUE TITLE
Unable to access variables in the singleton

### ISSUE THREAD

**Issue by 1609988** [nathanhoad/godot_dialogue_manager#698]
**Is your feature request related to a problem? Please describe.**
I am currently unable to access objects using variables in a conversation. I am using C # and have used singleton mode to manage all the data of my character. However, I have found that I cannot access the data in the singleton. For example, I have a PlayerData class where the singleton is Role, and one of its properties is level, which defaults to 0. In the conversation, I can only access it in this way: {{Level}}, and will always get 0. If I access it in this way, there will be a problem: {{Role. Level}}

**Describe the solution you'd like**
I can access the data in the singleton normally and freely access what I want like writing code

**Describe alternatives you've considered**
I didn't come up with a good solution, maybe I didn't find the right way to use it. If there is a simple way to solve my problem, I hope you can let me know. Thank you very much

**Additional context**
When I try to access the data in the singleton like this: {{Role. Level}}, the following error message appears:Assertion failed: "Role" not found. States with directly referenceable properties/methods/signals include "Main", "PlayerData". Autoloads need to be referenced by their name to use their properties.

**Comment by 1609988** [comment]
Just to add, it seems that we are currently unable to access data from the C # list or dictionary, such as the {{dictionary["key"]}}, or the {{list[0]}}

**Comment by nathanhoad** [comment]
Can you attach a tiny project that demonstrates the issue?

**Comment by 1609988** [comment]
[New.zip](https://github.com/user-attachments/files/17717196/New.zip)
Okay, you just need to download this, run the scenario, and click the buttons separately to reproduce the problem

**Comment by nathanhoad** [comment]
If you change your `NewScript.cs` to be:

```cs
using Godot;
using System;

public partial class NewScript : Node
{
	public static NewScript Player { get; private set; }

	public int Num = 100;

	public override void _Ready()
	{
		/*
		  This pattern is described in the Godot docs:
		  https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html#autoload 
		*/
		Player = this;
	}
}
```
Then you can refer to `Num` in dialogue as just `{{Num}}`:

![image](https://github.com/user-attachments/assets/73e5b0ad-c307-42c0-a0c3-81f7a135e573)
