### ISSUE TITLE
Resizing the window during testing dialogue makes the dialogue disappear.

### ISSUE THREAD

**Issue by Sslaxx** [nathanhoad/godot_dialogue_manager#7]
As of commit 8d44afc46d9acdcceba3163a72a3f7b3afc51c08 at least. Possible regression?

If you resize the test scene while dialogue is displaying, resizing the window causes it to stop displaying any further dialogue. Resizing the window back does not restore the dialogue.

*Before resizing the window:*
![Before](https://user-images.githubusercontent.com/324679/152685532-d6f792d4-8079-4050-9588-848e1d7b7f45.png)

*After resizing the window:*
![After](https://user-images.githubusercontent.com/324679/152685542-7d83b862-ac83-4863-9804-a44718bf5d82.png)

**Comment by nathanhoad** [comment]
Haha yeah looks like I somehow changed a `get_viewport_rect` to a `get_viewport` which meant the position was wrong unless the window was at the actual res.
