### ISSUE TITLE
Variable replacement not working if using translation files

### ISSUE THREAD

**Issue by stesproject** [nathanhoad/godot_dialogue_manager#701]
**Describe the bug**
Variables wrapped in {{}} seem not to be replaced if the string is taken from a translation CSV file (using the id).
The variable is replaced correctly if I leave the string in the Dialogue Manager editor.

**Affected version**

- Dialogue Manager version: 2.42.2
- Godot version: 4.4dev4

**To Reproduce**

1. Define a variable in a Global script (or not Global, it makes no difference)
es: var variable = "Hello"
2. In Dialogue tab create a new file and add a line
es: 
`~ chest_content
Contents found.
=> END`
3. Generate line IDs
4. Add the line to your translations.csv file.
es: td156eb37a6;You found: {{variable}}
5. {{variable}} is not replaced with the variable value ("Hello")
6. {{variable}} is replaced with the variable value if I keep the line in the Dialogue tab, without using the Translation feature

**Expected behavior**
Variables should be replaced even if they are defined in a translation file.

**Comment by nathanhoad** [comment]
Can you provide a tiny project that demonstrates the issue?

**Comment by nathanhoad** [comment]
Closing this until there is more information.
