### ISSUE TITLE
Being able to scroll responses

### ISSUE THREAD

**Issue by FoxReds** [nathanhoad/godot_dialogue_manager#71]
Would it be possible to add responses scrolling in sample ballon like in picture below? It would allow to create longer responses.
![Screenshot 2022-08-02 120634](https://user-images.githubusercontent.com/53920262/182360461-8ab3b45b-1577-44d5-9f72-303119e7ab50.png)

**Comment by RedXGames** [comment]
I think you can just modify your dialogue balloon to achieve that, using a scrollcontainer as a parent of the menus.
And make sure to change any references to the menu if any.

**Comment by nathanhoad** [comment]
Yeah, this is something you'd implement in your own balloon.
