### ISSUE TITLE
Allow passing the Node methods are called on to the DialogueManager

### ISSUE THREAD

**Issue by Flynsarmy** [nathanhoad/godot_dialogue_manager#74]
**Is your feature request related to a problem? Please describe.**
A common trope in RPGs is to have a pathway blocked off until certain conditions are met. Usually trying to navigate through these blocked pathways will present the player with dialogue telling them to turn back.

I made a reuseable 'DialogueTurnback' component (Area2D with CollisionShape2D child) and placed it into my scene. This component has the following code:
```gdscript
extends Area2D

export(Resource) var dialogue_resource: Resource
export(String) var dialogue_title: String

func _on_DialogueTurnaround_body_entered(body: Node) -> void:
	DialogueManager.show_example_dialogue_balloon(dialogue_title, dialogue_resource)

func turn_back() -> void:
	# Add code to turn the player back around here.
	pass
```

An example dialogue would be:
```
~ stairs

You don't need to go up there right now.
do turn_back()
```

The problem is the `turn_back()` method is being called in the active scene, not the component that initialized the dialogue.

**Describe the solution you'd like**
I'd like to pass the component that `do` methods call to the DialogueManager. Something like so:
```gdscript
DialogueManager.show_example_dialogue_balloon(dialogue_title, dialogue_resource, self)
```

Or alternatively it'd be nice to be able to yield the dialogue balloon so when dialogue finishes, I can perform an action in the component I'm in. Something like:
```gdscript
yield(DialogueManager.show_example_dialogue_balloon(dialogue_title, dialogue_resource, self), "dialogue_finished")
turn_back()
```

**Describe alternatives you've considered**
I could perhaps try a `do emit()` which could be listened to in the component. Problem with this is all other `DialogueTurnaround` components in my `current_scene` will also hear it.

**Comment by nathanhoad** [comment]
I've added a third argument to `show_example_dialogue_balloon` for extra states as an array so you would do something like:

`DialogueManager.show_example_dialogue_balloon(dialogue_title, dialogue_resource, [self])`

**Comment by Flynsarmy** [comment]
Wow, thank you very much! You're a legend!

**Comment by Norodix** [comment]
I think this is an awesome feature, this feels to me like a good way to organize code and resources. I only wish it was documented better.
I did not find this feature until I read this issue.
To me it would make sense to add a description of this under: https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md#mutations . 

(Awesome addon btw, thanks a lot!)

**Comment by Norodix** [comment]
Now I see it is documented under the API documentation but I think it would make sense to add it under the mutations description as well. Also the description under API docs makes sense from API and addon development standpoint but I skipped right over it when I was looking for info on how I can run do and set commands on custom nodes because there is no reference to this.

**Comment by nathanhoad** [comment]
@Norodix I've updated the mutation docs to mention being able to pass `extra_game_states` when requesting dialogue lines.

**Comment by RedFoxRU** [comment]
> @Norodix I've updated the mutation docs to mention being able to pass `extra_game_states` when requesting dialogue lines.

could you give an example of use, both in code and in .dialogue files?
