### ISSUE TITLE
Whether you can join a general conversation?

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#75]
For example, many NPC dialogue options can be linked to a common dialogue action 

Such as fighting, or trading, etc

**Comment by nathanhoad** [comment]
I'm going to need more information to understand what you're asking.

**Comment by wayrboy** [comment]
Conversations can jump to conversations on different files

For example, NPC dialogues can be followed by titles from the general dialog library

**Comment by nathanhoad** [comment]
Ah ok. This should be possible once #57 is done. I'll close this issue as a duplicate.
