### ISSUE TITLE
Discrepency between test scene dialogue window and in-game window

### ISSUE THREAD

**Issue by Flynsarmy** [nathanhoad/godot_dialogue_manager#78]
**Describe the bug**
I have a game with a window size of 320x180. The default dialogue window takes up the entire screen when I display it in game but looks correct in the test scene. Ideally the test scene should look the same as in-game.

**To Reproduce**
Set window width/height to 320x180. 
Create some basic dialogue. Here's mine:
```
~ stairs

You don't need to go up there right now.
```
Use the dialogue manager 'Play test scene' button. The dialogue should look as you'd expect:
![image](https://user-images.githubusercontent.com/334808/183334876-243022e8-d305-454e-b737-4301c35334c5.png)

Make a scene with the following GDScript:
```gdscript
func _ready():
    DialogueManager.show_example_dialogue_balloon("stairs", "res://mydialogue.tres")
```
Play the game. The dialogue window won't be the same size as the test scene, it'll be huge.

**Expected behavior**
The dialogue window should be the same in the test scene as in game.

**Screenshots**
Dialogue in game:
![image](https://user-images.githubusercontent.com/334808/183334160-2b62f7ad-9688-40e8-9b8e-bed84b74924c.png)

Dialogue in test scene:
![image](https://user-images.githubusercontent.com/334808/183334554-5ed6763e-42fd-4313-b081-2d3f154cc74e.png)

**Comment by nathanhoad** [comment]
That's how the test scene is supposed to work. You're meant to create your own custom balloons for use in your actual game. I have a few examples available (including a low res one) here: https://github.com/nathanhoad/example_dialogue_balloons
