### ISSUE TITLE
Crash when using two dialogue balloons simultaneously

### ISSUE THREAD

**Issue by Flynsarmy** [nathanhoad/godot_dialogue_manager#79]
**Describe the bug**
I have NPCs talking to each other with balloons popped up over their head. If I then talk to a different NPC directly (with for example a full size dialogue window), a crash will occur if I am presented with replies before the other NPCs have finished talking but I click a reply after they've finished talking.

Example:
* NPC1 starts a conversation with NPC2
* Player starts a conversation with NPC3
* Player is presented with 3 replies to NPC3
* NPC1's conversation ends
* Player clicks any reply
* Crash

**To Reproduce**
I've made a very basic example repository here to showcase the error
https://github.com/Flynsarmy/gd-dialogue-crash-example

Demonstration video
https://user-images.githubusercontent.com/334808/184590870-a3665de5-b6f4-4bc8-a3c0-001fb637a2a2.mp4

_pixel_balloon_ (the bottom dialogue) in this repo is unmodified from your example repo.
_Dialogue/point_n_click_balloon_ (the top balloons) is a super simplified custom balloon that just progresses on a timer.

**Expected behavior**
The game shouldn't crash

**Comment by wayrboy** [comment]
![image](https://user-images.githubusercontent.com/15027345/184580614-f9354063-9ede-4792-90c9-527ac1b1c430.png)

![image](https://user-images.githubusercontent.com/15027345/184580598-7520ab91-35d6-4aca-a862-ada7c9bde581.png)

**Comment by Flynsarmy** [comment]
I'm not sure what you're getting at here. This change doesn't fix the problem. In fact both those two `next()` lines are identical anyway.

**Comment by Flynsarmy** [comment]
I very much appreciate these quick fixes Nathan. Thanks for your hard work!
