### ISSUE TITLE
Translations not working + Solution

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#8]
Version : V1.1 
Godot Version : 3.3

Translations don't seem to work properly.
I'm using the Auto generated keys.

I managed to fix this issue by replacing this line inside dialogue_line.gd:
https://github.com/nathanhoad/godot_dialogue_manager/blob/70caba50368cbc80583db95d25e87727958ba5c4/addons/dialogue_manager/dialogue_line.gd#L30
by this : 
`dialogue = tr(data.get("translation_key")) if should_translate else data.get("text")`

**Comment by nathanhoad** [comment]
Good catch 👍
