### ISSUE TITLE
Cannot use enumerated types

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#80]
Cannot use enumerated types
![image](https://user-images.githubusercontent.com/15027345/185019782-6a3e7836-b19d-4afa-bb3f-127fb7b9417b.png)
![image](https://user-images.githubusercontent.com/15027345/185019810-21e4eab3-5f67-4764-996f-d7a80f6d3b2b.png)

**Comment by nathanhoad** [comment]
You can use enums but you would have to include that `Types` object as a runtime state in the runtime settings.
