### ISSUE TITLE
Disabled options are still able to be selected.

### ISSUE THREAD

**Issue by LostPython1192** [nathanhoad/godot_dialogue_manager#83]
**Describe the bug**
You are still able to select an option that would normally be impossible. (with the mouse)

**To Reproduce**
type this, or anything in which you would NOT want an option to be selected, then turn on the include responses with failed conditions. When you run it, select to option (with the mouse) which would normally be impossible. It shouldn't run, but it does.

Nathan: what's the problem?
- nothing [if problem == false)
    => move_on
- Mouse can select anything no matter what
    => go_to_thing

1. List steps to see error
2. See error, etc

**Expected behavior**
The option should not be selectable.

**Screenshots**

**Comment by LostPython1192** [comment]
Is there a setting to disable mouse input with it? Is that what you mean?

**Comment by nathanhoad** [comment]
No, just that disallowed items will no longer be focusable or clickable in the example balloon.
