### ISSUE TITLE
Dialog Show/Hide Animation

### ISSUE THREAD

**Issue by siempus** [nathanhoad/godot_dialogue_manager#84]
**Is your feature request related to a problem? Please describe.**
How about dialog show/hide animation. when a dialog box disappear and appear instantaneously between dialog lines, it feels robust but honestly, imo, feels flat in the game. looks like not polished.

**Describe the solution you'd like**
Ideally, implementing hide/show animation would be the solution, applying some delay in between dialogs would also make a difference but i'm not sure how to do that.

**Comment by nathanhoad** [comment]
The included example balloon is only meant as a guide. You should be building your own custom balloon to use in your actual game.
