### ISSUE TITLE
Abort/Cancel Dialog Feature

### ISSUE THREAD

**Issue by siempus** [nathanhoad/godot_dialogue_manager#86]
**Is your feature request related to a problem? Please describe.**
This might not be popular request, but i'm thinking about a game where i can leave the conversation even mid sentence (at any point during the dialog). 

**Describe the solution you'd like**
Maybe by adding a new boolean "abort_conversation" to the "DialogueManager.gd" which can be set to true at anytime to skip (or abort) current dialog and stop it after that (before going to the next dialog, if any)

**Comment by nathanhoad** [comment]
This would be something you'd implement in your game.

**Comment by siempus** [comment]
i did managed to do that. i just thought it would be a nice built-in feature for the plugin. i need to be mindful of all those coroutines and trying not to free it at the wrong place. i'm new to godot so i'm not sure how godot handle coroutines, but i assume it works just like unity. but i do get why you want the plugin to be as universal as it can be. keep up the great work man, cheers!
