### ISSUE TITLE
Phrase/Word Shuffle

### ISSUE THREAD

**Issue by siempus** [nathanhoad/godot_dialogue_manager#87]
**Is your feature request related to a problem? Please describe.**
How about a phrase shuffle? I'm not sure how to explain this but i can give you example:

[Hello, Hi there, Hi] welcome to [my place, the most beautiful place in the world, my wife's house].

basically, we choose randomly one of the phrases between the square brackets, separated by commas. i think this will make any conversation become more dynamic. i've seen this feature on "clyde dialog" if i'm not mistaken and i think its a great feature.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nathanhoad** [comment]
This was going to be added in version 2 but it's pretty simple so I've backported it to [v1.15.0](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v1.15.0). The syntax is `[[first thing|second thing|another thing|etc]]`.

**Comment by siempus** [comment]
oh you did? that's great! i'm gonna try it. thank you!
