### ISSUE TITLE
seconds_per_step isn't consistent

### ISSUE THREAD

**Issue by Flynsarmy** [nathanhoad/godot_dialogue_manager#88]
**Describe the bug**
My dialogue with a `seconds_per_step` value of 0.02 runs far slower in a HTML export than in the editor.

This bug is present in the latest 1.15 build of Dialogue Manager.

**To Reproduce**
* Uncheck *Project - Settings - WIndow - Use V-Sync*
* Run a standard *pixel_balloon* example from [the examples repo](https://github.com/nathanhoad/example_dialogue_balloons)
* Export your project as HTML5 then run it again. Notice the dialogue progressing far slower.

I've made a barebones example repo demonstrating the issue [here](https://github.com/Flynsarmy/gd-broken-dialogue).

**Expected behavior**
Dialogue should progress at the same speed regardless of frame rate or export method.

**Comment by nathanhoad** [comment]
This appears to be an issue with Godot's HTML5 export and audio processing. If you set the _Audio > Output Latency.web_ to something smaller (eg. 15) then the delay appears to go away for me. Another option would be to `preload` the talking sound.

**Comment by Flynsarmy** [comment]
I'm not sure that's the case. I disabled audio completely for the pixel balloon by commenting out lines 172 and 174 in [_on_Dialogue_spoke](https://github.com/nathanhoad/example_dialogue_balloons/blob/da54957a76d4a573ffff2843464acfdad9a3e378/pixel_balloon/pixel_balloon.gd#L169) and web is still significantly slower for the dialogue to appear on screen.
