### ISSUE TITLE
How to give menu incoming variables

### ISSUE THREAD

**Issue by wayrboy** [nathanhoad/godot_dialogue_manager#9]
I want to introduce a list of tasks, what do you do?

**Comment by nathanhoad** [comment]
I'm not sure I understand what you're wanting to do.

**Comment by uwidev** [comment]
Using conditions in responses might work, but it's very limited as you'd need to create the responses for all combinations of a set of possibilities. 

I'm doing a workaround where I generate a list of choices based on various game variables and chance, then have the parser parse the raw text and turn it into it's own DialogueResource. I'm having some trouble with the translation_key, as it's somehow lost during the process, but it's a start.

That being said, this would prove useful if you need all sorts of combinations from a set of choices. (e.g. A, B, C, AB, AC, BC, ABC). My initial intent was to allow for quick swapping of responses for speedy prototyping and randomized choices, but the more I think about it, the more I wonder if I'm actually saving time.

**Comment by nathanhoad** [comment]
Hmm yeah I never thought about using the parser at runtime. I might look into making that more possible.

**Comment by nathanhoad** [comment]
The parser can now be used at runtime via `DialogueManager.get_resource_from_text(string)`.

**Comment by Sslaxx** [comment]
Perhaps a `get_resource_from_file` function may also be useful?

**Comment by nathanhoad** [comment]
I feel like if you have the text in a file it should really be a `tres` that has already been parsed. Apart from that it's easy enough to write a file loader that passes its content into the `get_resource_from_text` method anyhow.

**Comment by wayrboy** [comment]
let me try

**Comment by Sslaxx** [comment]
> I feel like if you have the text in a file it should really be a `tres` that has already been parsed. Apart from that it's easy enough to write a file loader that passes its content into the `get_resource_from_text` method anyhow.

Unsure of how much of a use-case something like this may have, but dynamically creating/saving/loading them?
