### ISSUE TITLE
GDM 1.* notifies of 2.* updates

### ISSUE THREAD

**Issue by Flynsarmy** [nathanhoad/godot_dialogue_manager#90]
**Describe the bug**
GDM 1.* in Godot 3.5 notifies of the 2.* updates in the top right corner of the Dialogue screen. This version is incompatible with 3.5. It should only notify of 1.* updates. 

Until this bug is resolved, there is no way to know if there's a 1.* update available without manually coming to the git page and looking at the releases section.

**To Reproduce**
* Install latest GDM 1.* in Godot 3.5
* Enable the plugin and visit the Dialogue screen

**Expected behavior**
We should only be notified about the latest compatible version.

**Screenshots**
![image](https://user-images.githubusercontent.com/334808/187589210-89c471cf-6dbc-4903-8af0-577d43610e87.png)

**Comment by nathanhoad** [comment]
That's already been addressed in [v1.16.0](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v1.16.0)
