### ISSUE TITLE
Dialogue Manager 2.0.1 doesn't work with latest Godot 4 alpha release

### ISSUE THREAD

**Issue by faceze** [nathanhoad/godot_dialogue_manager#91]
**Describe the bug**
*Disclaimer: I suck balls as a programmer (I think that's the technical term) so this may be an easy fix on my part. *
I'm unable to activate Dialogue Manager 2 in Godot 4.
I'm on Windows 10.

**To Reproduce**

1. Download a fresh copy of Godot v4.0.alpha15.official [432b25d36]
2. Download Dialogue Manager 2.0.1
3. Copy the addons folder into a new godot project for desktop folder.
4. Go to the project settings and to the plugins tabs to activate the plugin.
5. Get this error: *"Unable to load addon script from path: 'res://addons/dialogue_manager/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dialogue_manager/plugin.cfg' to prevent further errors."*

**Expected behavior**
Get Dialogue Manager as an addon and fail to make use of it due to my own lack of skills and knowledge.

**Screenshots**
![image](https://user-images.githubusercontent.com/4756334/187748842-f74faad0-befd-4a9d-aa48-b9681c5088b2.png)
Godot is blaming the dialogue_label.gd "which is loaded but not compiled". The dialogue_label.gd in turn complains about the "percent_visible" identifier not being declared in its current scope, and that's where I walked away from the problem and I can't give any more real useful information.

**Comment by nathanhoad** [comment]
They renamed a bunch of things in the latest alpha (as well as a few other hard to pin down breakages). It should be working again in [Dialogue Manager 2.0.2](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.0.2).

**Comment by faceze** [comment]
Thanks! Now I can try to learn how to use your addon which seems to have all the features I need for my little projects. 

**Unrelated question:** BTW is there an example somewhere where I could see some actual implementation besides the examples you provided? I'm dumb and I was having trouble detecting the dialogue finished signal in order to unpause other stuff in the background. Either way, thanks a million for your work!
