### ISSUE TITLE
Error message when start of godot or enable the plugin

### ISSUE THREAD

**Issue by harrisyu** [nathanhoad/godot_dialogue_manager#99]
I am using godot 4 beta.

dialogue manager version v2.2.0

There is 2 error message line when start of godot or enable the addon:

`
modules\gdscript\gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
Parser bug (please report): Trying to check compatibility of unset value type
`

But the addon still function very well.

**Comment by nathanhoad** [comment]
That appears to be an issue with Godot itself. Hopefully it goes away once the betas settle.
